### ISSUE TITLE
write: connection reset by peer should close the connection

### ISSUE THREAD

**Issue by Sytten** [lib/pq#1028]
# Setup
I am using a serverless setup on GCP Cloud Run (knative) with a database in VPC accessed via a serverless connector.
This is a similar to a setup where a server communicates with a database behind an HAProxy or an NGINX.
The only difference is that if the server is not receiving requests, its CPU is heavily throttled.

# Problem
I started receiving errors like:
```
write tcp 169.254.8.1:33834->10.1.0.2:14157: write: connection reset by peer
```
Where `10.1.0.2` is the database, that tells me that most likely the connection to the proxy was maintained but the connection to the host was killed. I would expect `pq` to be able to detect that, kill the connection and retry on a new one. But it seems it is not the case and the pool will happily continue using the connection even if it is effectively dead.

This is patchable with a `SetConnMaxIdleTime` or `SetConnMaxLifetime`, but I feel a network error like that should be able to detected and acted upon directly.

**Comment by Lekensteyn** [comment]
Possibly a duplicate of #835.

**Comment by Sytten** [comment]
Thanks for linking issues! @Lekensteyn 
The answer to it is not super great though: move to pgx :/

**Comment by Lekensteyn** [comment]
Hey @Sytten, can you share which pq version you are running? Is the Postgres connection secured with TLS?

#1013 (>= v1.9.0) should have addressed error handling when sending commands over a closed connection.

**Comment by Sytten** [comment]
For some reason I am using an old version (1.7.0), unsure why goland resolved to that (most likely I already had it downloaded). I will try with a more recent version, thanks a LOT for that.

**Comment by Sytten** [comment]
I still have issue with the latest version, either `driver: bad connection` or `read: connection reset by peer`.

**Comment by Christian-health** [comment]
@Sytten     Did switching your database driver to /jackc/pgx resolve the 'connection reset by peer' issue?
I am using lib/pq/, and the issue I am encountering is that when PostgreSQL stops and then starts, the 'connection reset by peer' problem occurs. The database connection pool still uses invalid old connections to access the PostgreSQL database for a period of time（The time is determined by `SetConnMaxIdleTime` or `SetConnMaxLifetime`.）. It does not establish new connections even after encountering the 'connection reset by peer' error.



I look forward to your reply. Thank you very much.

**Comment by Sytten** [comment]
I dont remember, probably. I dont use golang anymore.
