### ISSUE TITLE
v1.10.8 got undefined: driver.Validator

### ISSUE THREAD

**Issue by angelinahung** [lib/pq#1121]
dear team, 

I got the error:
go: github.com/lib/pq latest => v1.10.8
go: downloading github.com/lib/pq v1.10.8
# github.com/lib/pq
..\..\go\pkg\mod\github.com\lib\pq@v1.10.8\conn.go:2089:7: undefined: driver.Validator

I use go 1.14 version

could you please check if there's an issue for the latest version (v1.10.8) when using go1.14? thanks

**Comment by otan** [comment]
should be fixed on v1.10.9 if your go version is old.
