### ISSUE TITLE
Array types can't convert {NULL}

### ISSUE THREAD

**Issue by AuroraTea** [lib/pq#1131]
pq.Int64Array and other Array types, in {NULL} will report an error pq: parsing array element index 0: strconv.ParseInt: parsing "": invalid syntax
And {NULL} is still very common in LEFT OUTER JOIN

**Comment by cbandy** [comment]
Yep. For nullable values use [[]sql.NullInt64](https://pkg.go.dev/database/sql#NullInt64) and [pq.Array()](https://pkg.go.dev/github.com/lib/pq#Array). From the docs:

```go
var x []sql.NullInt64
db.QueryRow(`SELECT ARRAY[235, 401]`).Scan(pq.Array(&x))
```

**Comment by AuroraTea** [comment]
New to the use of `pq.Array(&x)`, thank you @cbandy very much!

I usually prefer to use *int64 (NULL will be nil), but[]*int64 here is not work with`parsing array element index 0: strconv.ParseInt: parsing "": invalid syntax[]`, []sql.NullInt64 is OK. Is there still a way to use *int64?
