### ISSUE TITLE
pq: unexpected describe rows response: 'D'

### ISSUE THREAD

**Issue by dajohi** [lib/pq#142]
Hello -

I created a prepared select statement.  When I run it within a transaction, I get the follow error:

pq: unexpected describe rows response: 'D'

I believe lib/pq needs to support 'D'

libpq does it like so: http://doxygen.postgresql.org/fe-protocol3_8c_source.html#l00318

**Comment by rubens21** [comment]
Just a heads-up:
I was not starting two transaction, but I was getting the same error.
In my case, the problem was a *sql.Row that I was not closing.
```
returnedRow, err := myTransaction.Query(...)
```
fix:

```
returnedRow, err := myTransaction.Query(...)
// do you job
returnedRow.Close()
```

**Comment by aashishAil** [comment]
I was running to goroutines to update a different table with the same transaction, which was introducing a race condition that sometimes the 1st update query had not finished when the 2nd query started and giving me the error.
Fix: Make the go routines trigger after completion
