### ISSUE TITLE
Deferred rollback vs. panic from the driver

### ISSUE THREAD

**Issue by johto** [lib/pq#178]
Hi,

I briefly derailed the discussion in #177 because @leehambley had experienced the problem reproduced here: https://gist.github.com/johto/7145291.  In short, a deferred rollback will leave the goroutine deadlocked on itself if a panic is raised in a database/sql driver.  I'm not sure why the deadlock detector doesn't have anything to say about this (maybe something to do with the shady goroutine 2 with no stack trace?).  I've also confirmed that it's still reproducible against the development branch (go version devel +0eb6508d3e88), so this is almost certainly going to still be a problem in Go 1.2.

My question is: is there something we should do about this?  Avoid panics at all costs?  Document the issue and perhaps discourage deferring rollbacks?  Can anyone see other ways to reproduce the problem?

Also, is there a documentation on how to write database/sql drivers correctly (because I haven't been able to find any proper docs)?  If that documentation doesn't mention anything about this, I think it would be a good idea to bring this up with the database/sql folks to see what they think.

**Comment by jbowens** [comment]
I know this is an old issue but a fix for _some_ of these cases was added in Go 1.6. https://github.com/golang/go/issues/13677

**Comment by jbowens** [comment]
@johto I believe the rest of these cases were fixed by: https://go-review.googlesource.com/#/c/23576/
