### ISSUE TITLE
pq doesn't appear to support named types

### ISSUE THREAD

**Issue by sjhitchner** [lib/pq#200]
I having some trouble getting the pq library to handle my data.

We have a bunch of structs with custom typed fields i.e. Our User struct has a field Id of type UserId which is just a string. This makes our APIs really clear since the method requires a UserId not just a string. See example code below.

When I try to update or insert data I get the following error:

```
--- FAIL: TestUser (0.01 seconds)
panic: sql: converting Exec argument #0's type: unsupported type domain.UserId, a string [recovered]
        panic: sql: converting Exec argument #0's type: unsupported type domain.UserId, a string
```

UserId is an unsupported type but it's just a string. Is this expected behaviour or a bug? I've seen this issue before where reflect.TypeOf(x) is called instead of reflect.TypeOf(x).Kind().

Thanks

```
type UserId string

type User struct {
    Id      UserId
    Text    string
    Version int64
}
```

**Comment by c4milo** [comment]
@kisielk did you file the issue?
