### ISSUE TITLE
cannot run queries, get "driver: bad connection"

### ISSUE THREAD

**Issue by mnagel** [lib/pq#237]
I am trying to use this driver, but somehow I am failing.

I can connect to my postgresql server allright:

```
michael@diplomarbeit:*fastergo/src/spamdb$ psql spamdb
psql (9.1.11)
Type "help" for help.

spamdb=> \q
```

But when I run the following minimalistic Go program (see http://www.acloudtree.com/how-to-shove-data-into-postgres-using-goroutinesgophers-and-golang/ ):

```
package main

import (
  //"os"
  "log"
  "time"
  "fmt"
  "database/sql"
  _ "github.com/lib/pq"
)

func main() {
  // create the statement string
  var sStmt string = "insert into test (gopher_id, created) values ($1, $2)"

  // lazily open db (doesn't truly open until first request)
  db, err := sql.Open("postgres","host=localhost dbname=spamdb sslmode=disable")
  if err != nil {
    log.Fatal("open ", err)
  }

  stmt, err := db.Prepare(sStmt)
  if err != nil {
    log.Fatal("prepare ", err)
  }

  fmt.Printf("StartTime: %v\n", time.Now())

  res, err := stmt.Exec(1, time.Now())
  if err != nil || res == nil {
    log.Fatal("exec ", err)
  }

  // close statement
  stmt.Close()

  // close db
  db.Close()

  fmt.Printf("StopTime: %v\n", time.Now())
}
```

I get the error mentioned in the title:

```
michael@diplomarbeit:*fastergo/src/spamdb$ go run demo1.go
2014/02/20 15:33:43 prepare driver: bad connection
exit status 1
```

Any ideas?
Best Redards
Michael

**Comment by alberto0186** [comment]
I'm trying to connect my application with postgres. I followed the instructions in :https://libraries.io/go/github.com%2Flib%2Fpq. I tested in the terminal and shows ok github.com/lib/pg.
but when I run my application says can't find import: "github.com/lib/pq"
someone can help me please.

my application looks like:
import (
	"database/sql"

	_ "github.com/lib/pq"
)

**Comment by johto** [comment]
Did you run `go get github.com/lib/pq`?

**Comment by alberto0186** [comment]
yes and my Environment Variables
