### ISSUE TITLE
"Select Case When" Using Float

### ISSUE THREAD

**Issue by ericsalim** [lib/pq#239]
I've found a possible bug when using "case when":

q := `select case when $1 <> 0 then 1 else 0 end as "value"`
rows, err := mydb.Query(q, 25.00)

The err is: pq: invalid input syntax for integer: "25.00000000000000000"

Not sure why float is quoted as if it's a string.

**Comment by rinatio** [comment]
@johto Having similar issues with following kind of query:

```
row := db.QueryRow(`select round(100/$1)`, 1.2)
```

Can you tell if there's a way to tell DB which type to expect as an input from driver side? Otherwise this works well:
```
row = db.QueryRow(`select round(100/$1::float)`, 1.2)
row = db.QueryRow(`select round(100.0/$1)`, 1.2)
```
