### ISSUE TITLE
Serializable Isolation

### ISSUE THREAD

**Issue by benbjohnson** [lib/pq#261]
The [`DB.Begin()`](http://golang.org/pkg/database/sql/#DB.Begin) docs say that the isolation level depends on the driver. I'd assume that pq uses `READ COMMITTED` by default.

Is there any way to specify `SERIALIZABLE` isolation?

**Comment by Kinghack** [comment]
hi, is there any update here since I could not found any information about 'default_transaction_isolation' in [lib/pqdoc](https://godoc.org/github.com/lib/pq) or [postgresqldoc](http://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING)

Thanks.

**Comment by johto** [comment]
The relevant portion in our docs is this:

```
Similarly to libpq, when establishing a connection using pq you
are expected to supply a connection string containing zero or
more parameters. A subset of the connection parameters
supported by libpq are also supported by pq. Additionally, pq
also lets you specify run-time parameters (such as search_path
or work_mem) directly in the connection string.
```

The run-time parameter is documented in the postgres docs [here](http://www.postgresql.org/docs/9.5/static/runtime-config-client.html#GUC-DEFAULT-TRANSACTION-ISOLATION).  There's no point in trying to maintain a copy of the list of all possible options in our documentation.

**Comment by Kinghack** [comment]
Ok then. 

Thanks.
