### ISSUE TITLE
Is there a way to detect and cancel a long-running query?

### ISSUE THREAD

**Issue by grafana-dee** [lib/pq#281]
I'm looking to run queries against a data warehouse, some of these will be quick, some slow... depending on the parameters chosen by users operating a dashboard.

If the query is very slow (does not return in less than 30 seconds), I want to cancel the query and instruct the end user to refine their report parameters further.

PostgreSQL gives a way to cancel a query:

``` sql
SELECT pg_cancel_backend(pid of the postgres process); 
```

But I do not have the pid to give to the backend.

Is there a way to obtain the pid for a query that has been started by lib/pq, from lib/pq?

**Comment by tejasmanohar** [comment]
@johto FYI I think this can be done with https://github.com/lib/pq/pull/535 now.
