### ISSUE TITLE
better error messaging for query parameters exceeding 2^16 values?

### ISSUE THREAD

**Issue by bfallik** [lib/pq#295]
We recently encountered an issue from a pathological query that used >100k query parameters. The result from the driver was an error message like:

```
runAssignment(): pq: got 386795 parameters but the statement requires 59115
```

which comes from https://github.com/lib/pq/blob/master/conn.go#L917. It looks like st.paramTyps is at most 2^16 in length from https://github.com/lib/pq/blob/master/conn.go#L523.

I imagine the 2^16 limit is a limitation of the wire format but I'm wondering if pq could provide better error messaging? The "statement requires" value (59115 above) is wrong but it would have been even more helpful to have an error like "got 386795 parameters but the statement is limited to 65536".

Thanks!

**Comment by galileo-pkm** [comment]
Got the same type of error with a prepared statement. Maybe it would be a good idea to apply the same fix to prepared statements?

**Comment by pureugong** [comment]
> it would be a good idea to apply the same fix to prepared statements?

I have faced the similar issue with a prepared statement and wasted time to look under the hood. 
I agree, @galileo-pkm, it would be really helpful if we can apply the same error message on it.
