### ISSUE TITLE
Notification.Extra property

### ISSUE THREAD

**Issue by nkev** [lib/pq#307]
While running your listen_example, if open pgAdmin and run the SQL statement: 

``` golang
NOTIFY "getwork", 'this is my message';
```

...I can see that the following line is triggered in your example:

``` golang
fmt.Fprintln("received notification, new work available")
```

...which is awesome. But how do I access the text payload (i.e. the text 'this is my message') from the code in your example?  I think what I want is related to your **Notification.Extra** property but I cannot access it.

**Comment by rhacker** [comment]
thanks for the information :)
