### ISSUE TITLE
auto-reconnect?

### ISSUE THREAD

**Issue by Unknwon** [lib/pq#318]
Hi there,

After I use `sql.Open("postgres", ...)`

Will driver reconnect for me if connection is lost when I call `*sql.DB.Ping`? 

Because [docs](https://gowalker.org/database/sql#DB_Ping) says it should, but I'm not sure, so I want to make sure.

Thanks!

**Comment by johto** [comment]
> Will driver reconnect for me if connection is lost when I call *sql.DB.Ping?

In database/sql, that's not up to the driver to decide.  However, Ping() isn't guaranteed to actually try and reach the server, so its usefulness in an attempt to effect a reconnect is questionable (see [here](https://github.com/golang/go/blob/2958860ee86a732e4a5ef55e48f40559858fa82a/src/database/sql/sql.go#L458) and [here](https://github.com/golang/go/blob/2958860ee86a732e4a5ef55e48f40559858fa82a/src/database/sql/sql.go#L652)).  If I was writing an app, I would call Ping() immediately after sql.Open() to know whether a connection could be established at all, and then never call Ping after that.

**Comment by Unknwon** [comment]
I see, thanks!
