### ISSUE TITLE
errors relatively painful to use

### ISSUE THREAD

**Issue by james-lawrence** [lib/pq#324]
Unless I am missing something (and feel free to correct me) in order to determine what kind of error
I've encountered I have to do something like this:
```
if err, ok := err.(*pq.Error); ok {
  switch err.Code.Name() {
    case "unique_violation":
      // ...
    case "deadlock_detected":
      // ....
     default:
       // ....
  }
}
```

Be much nicer if instead each error code had its own error type:
```
switch x := err.(type) {
case nil:
  // ignore
case pq.ConnectionFailure:
  // do something special.
case pq.Deadlock:
  // do something special.
case pq.UniqueViolation:
  // do something special.
default:
  // do something generic
}
```

example implementation: https://play.golang.org/p/AtzpqbMOp7
```
package main

import "fmt"
import "errors"

type PQError interface {
	error
	PQErrorDetails() Details
}

// Implements PQError interface
type Details struct {
	Severity string
	Code string
}

func (t Details) Error() string {
	return t.Severity + ": " + t.Code
}

func (t Details) PQErrorDetails() Details {
	return t
}
// internal function to lib/pq converts codes to their respective types.
func classify(d Details) PQError {
  switch d.Code {
   case "successful_completion":
     return nil
   case "unique_violation":
     return UniquenessViolation{d}
   case "deadlock_detected":
     return Deadlock{d}
   default:
     return d
  }
}

type UniquenessViolation struct { Details }
type Deadlock struct { Details }

func PrintError(err error) {
	switch err := err.(type) {
        case nil:
		fmt.Println("No Error Hurrah")
	case UniquenessViolation:
		fmt.Println("Uniqueness Error Severity:", err.Severity, "Code:", err.Code)
	case Deadlock:
		fmt.Println("Deadlock Error")
	case PQError:
		fmt.Println("Some other pq error")
	default:
		fmt.Println("Wowa wtf", err.Error())
	}
}

func HandlePQError(err PQError) PQError {
	fmt.Println("Handling PQ Error")
	return err  
}

func HandleGenericError(err error) error {
	if err != nil {
		fmt.Println("Handling generic error")
	} else {
		fmt.Println("No Error Hurrah!")
	}
	return err
}

func main() {
	successful_completion := classify(Details{Severity: "error", Code: "successful_completion"})
	unique_violation := classify(Details{Severity: "error", Code: "unique_violation"})
	deadlock := classify(Details{Severity: "error", Code: "deadlock_detected"})
	generic_pq := classify(Details{Severity: "warn", Code: "ghi"})
	PrintError(successful_completion)
	PrintError(unique_violation)
	PrintError(deadlock)
	PrintError(generic_pq)
	PrintError(errors.New("Something Really Unexpected Happened..."))
	HandleGenericError(HandlePQError(deadlock))
	HandleGenericError(successful_completion)
}
// Output
// No Error Hurrah
// Uniqueness Error Severity: error Code: unique_violation
// Deadlock Error
// Some other pq error
// Wowa wtf Something Really Unexpected Happened...
// Handling PQ Error
// Handling generic error
// No Error Hurrah!
```

If we wanted to get really clever we could use stringer to do the mapping from code to name
and define all the codes as constants:
https://godoc.org/golang.org/x/tools/cmd/stringer

**Comment by johto** [comment]
> Be much nicer if instead each error code had its own error type:

Nicer why?  The only difference I can see is that if these were types, the compiler would tell you if you made a typo.  And we don't need to change the entire interface to do that; we could just implement constants for the strings.  The downside of using them would be that the ones added in newer versions would not work with older versions of the driver, but then at least the user had a choice, unlike in your version.

**Comment by james-lawrence** [comment]
nothing stops us from implementing the old interface on the new one. it still has all the information necessary under the hood.

The fact we have to reach into the object to determine the type of error is very messy. expecially when I can see different types of errors returned from a function. And the compiler helping out with the program is definitely a huge plus.

**Comment by james-lawrence** [comment]
the point is if I as a developer using lib/pq have to do this every time I get an error from the driver:
```
err := somefunc()
switch err := err.(type) {
case err := *pq.Error:
  switch err.Code.Name() {
    // handle errors i care about
  }
case DifferentError:
   // ....
 case error:
   // generic
}
```

is very annoying / painful

**Comment by johto** [comment]
> nothing stops us from implementing the old interface on the new one. it still has all the information necessary under the hood.

How would you do it without breaking code like this?

```
if err, ok := err.(*pq.Error); ok {
```

My understanding is that you want to do something like this: http://play.golang.org/p/c_pjuE0gfS which, as demonstrated, breaks that pattern.

> The fact we have to reach into the object to determine the type of error is very messy. expecially when one is dealing with different types of errors returned from a function.

I don't believe it to be messy at all, I think that's just the reality of it.  For example, some code might consider that a `unique_violation` of one constraint is expected, but a violation of any other constraint means something is wrong.  There's no way to model that with types.

> And the compiler helping out with the program is definitely a huge plus.

Like I said, there are other ways to do that.

**Comment by james-lawrence** [comment]
pq.Error is exactly the problem. its a struct so now all code depends on the details of that struct. I'm proposing pq moves away from that so its easier to handle in the future. But generally if they are not reaching into the object (which current mechanism forces them to do because of the current implementation.)

regarding your unique_violation: this is exactly where the types help. with a unique violation type we can give specialised methods for handling that exact type of error.

**Comment by johto** [comment]
> pq.Error is exactly the problem. its a struct so now all code depends on the details of that struct. I'm proposing pq moves away from that so its easier to handle in the future. But generally if they are not reaching into the object (which current mechanism forces them to do because of the current implementation.)

So you *are* proposing to break all error handling logic out there right now?  Or did I misunderstand?

Because if you are, I think the tangible improvements would have to be *way* more substantial than those of this proposal.

> regarding your unique_violation: this is exactly where the types help. with a unique violation type we can give specialised methods for handling that exact type of error.

But you still have to look into the object, which was what you wanted to avoid, no?

**Comment by james-lawrence** [comment]
> So you are proposing to break all error handling logic out there right now? Or did I misunderstand?

Rename in my example Details to Error and all current could would continue to work.

Yes in the case I want to distinguish between that extremely narrow subset of constraints (which lets be honest most of the time we don't care at that level of detail in applications) I would have to reach in (which is not prevented by this proposal).

**Comment by james-lawrence** [comment]
Anyways I was just trying to offer up a better solution than what was there. If project isn't interested its not interested ./shrug.

**Comment by johto** [comment]
> Rename in my example Details to Error and all current could would continue to work.

And now the concrete type returned by the driver is again pq.Error, not pq.UniqueViolation, and we're back at what you do now: if the type is *pq.Error, do something specific to handling that.  And then it's just a different way of presenting the same exact information we already do, with exactly zero improvements over the current interface.

**Comment by james-lawrence** [comment]
Yes I am aware, I was trying to offer an eventual migration path off of the concrete type. Like i said the fact it is a concrete type is a problem. There is a reason error is an interface in the base language.

**Comment by johto** [comment]
> Anyways I was just trying to offer up a better solution than what was there.

I appreciate it, I really do.  And I'm very interested in hearing how the project could be improved.  But any proposal which suggests breaking 100% of the code out there that uses that specific feature **must** be a big improvement in practice for it to be even considered.

**Comment by james-lawrence** [comment]
2.0 release? =P

**Comment by james-lawrence** [comment]
1 option would be to expose a Classify(pq.Error) pq.TypedError method which does the translation.

**Comment by johto** [comment]
> 2.0 release? =P

If we were to ever do that, this would be one thing to consider.  But I'm not aware of any deeply rooted problems with the current implementation which would warrant such a release.

**Comment by james-lawrence** [comment]
I'm just going to write a wrapper which does it for me atm. Just frustrating have to write it in order to handle errors cleanly within my project =/

**Comment by johto** [comment]
> 1 option would be to expose a Classify(pq.Error) pq.TypedError method which does the translation.

I'd much prefer to have constants for the different error names, *unless* we had several methods we'd like to implement for the error-specific types.  I can't come up with any right now, though I didn't try too hard either.
