### ISSUE TITLE
Possible SSL issue with tip and 9.4?

### ISSUE THREAD

**Issue by johto** [lib/pq#334]
[This test](https://travis-ci.org/lib/pq/jobs/49568736) has now failed on two consecutive runs.  There have been recent changes to TLS in Go in tip, and IIRC there were some changes in 9.4 as well, so this might be legitimate.

**Comment by johto** [comment]
Interestingly, I can't reproduce on OS X.

**Comment by uhoh-itsmaciek** [comment]
Interesting. I restarted the Travis build, and it failed again the same way. Do you know what changes happened in 9.4?

**Comment by johto** [comment]
It appears to be caused by ssl_prefer_server_ciphers being 'on'.  I'm not sure why it didn't break on OS X, though.  Will keep investigating..

**Comment by johto** [comment]
OK, looks like a Go bug to me.  Opened https://github.com/golang/go/issues/9808.

**Comment by johto** [comment]
Fixed via [ebe3d693d472f69cb68d945466eac0f770abf29b](https://github.com/golang/go/commit/ebe3d693d472f69cb68d945466eac0f770abf29b).
