### ISSUE TITLE
Connections do not have a read / write deadline

### ISSUE THREAD

**Issue by lmb** [lib/pq#335]
I'm hitting an issue where libpq waits indefinitely on a dropped connection to a remote DB. This is probably b/c of some networking issue. Would it be possible for pq  to support setting deadlines / timeouts on reads and writes?

Obviously this is a symptom of the network going wrong, but then that can always happen.

See the following stackdump for the problem:
```
17:24:23 web.1
goroutine 28 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f9aa1368958, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20807afb0, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20807afb0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc20807af50, 0xc2080e3000, 0x1000, 0x1000, 0x0, b)
	/usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc20803e268, 0xc2080e3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/net.go:122 +0xe7
bufio.(*Reader).fill(0xc208005d40)
	/usr/local/go/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).Read(0xc208005d40, 0xc2080d1920, 0x5, 0x200, 0x5, 0x0, 0x0)
	/usr/local/go/src/pkg/bufio/bufio.go:175 +0x230
io.ReadAtLeast(0x7f9aa1368cf0, 0xc208005d40, 0xc2080d1920, 0x5, 0x200, 0x5, 0x0, 
	/usr/local/go/src/pkg/io/io.go:289 +0xf7
io.ReadFull(0x7f9aa1368cf0, 0xc208005d40, 0xc2080d1920, 0x5, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/io/io.go:307 +0x71
github.com/lib/pq.(*conn).recvMessage(0xc2080d1900, 0xc2080ee460, 0x7f9aa1367c20, 
	/tmp/build/.heroku/g/src/bitbucket.org/lzb/arenad/Godeps/_workspace/src/github.:725 +0x146
github.com/lib/pq.(*conn).recv1Buf(0xc2080d1900, 0xc2080ee460, 0xc2080d1920)
	/tmp/build/.heroku/g/src/bitbucket.org/lzb/arenad/Godeps/_workspace/src/github.:777 +0x31
github.com/lib/pq.(*conn).recv1(0xc2080d1900, 0xc2080ee440, 0xc2080ee460)
	/tmp/build/.heroku/g/src/bitbucket.org/lzb/arenad/Godeps/_workspace/src/github.:800 +0x8b
github.com/lib/pq.(*conn).prepareTo(0xc2080d1900, 0x8ef6f0, 0x1f, 0x88c810, 0x0, )
	/tmp/build/.heroku/g/src/bitbucket.org/lzb/arenad/Godeps/_workspace/src/github.:566 +0x7fc
github.com/lib/pq.(*conn).Query(0xc2080d1900, 0x8ef6f0, 0x1f, 0xc208171b40, 0x1, , 0x0)
	/tmp/build/.heroku/g/src/bitbucket.org/lzb/arenad/Godeps/_workspace/src/github.:635 +0x1bc
database/sql.(*DB).queryConn(0xc20805e700, 0xc208005ec0, 0xc208171b20, 0x8ef6f0, , 0x1, 0x1, 0x18, 0x0, ...)
	/usr/local/go/src/pkg/database/sql/sql.go:942 +0x1da
database/sql.(*DB).query(0xc20805e700, 0x8ef6f0, 0x1f, 0xc208171b00, 0x1, 0x1, )
	/usr/local/go/src/pkg/database/sql/sql.go:929 +0x105
database/sql.(*DB).Query(0xc20805e700, 0x8ef6f0, 0x1f, 0xc208171b00, 0x1, 0x1, )
	/usr/local/go/src/pkg/database/sql/sql.go:915 +0xad
github.com/coopernurse/gorp.(*DbMap).query(0xc208004840, 0x8ef6f0, 0x1f,  0x1, 0x8ef6f0, 0x0, 0x0)
	/tmp/build/.heroku/g/src/bitbucket.org/lzb/arenad/Godeps/_workspace/src/github.rp/gorp.go:1155 +0xb9
github.com/coopernurse/gorp.rawselect(0xc208004840, 0x7f9aa13694b0, 0xc208004840, 8f30, 0x8ef6f0, 0x1f, 0xc208171b00, 0x1, 0x1, ...)
	/tmp/build/.heroku/g/src/bitbucket.org/lzb/arenad/Godeps/_workspace/src/github.rp/gorp.go:1560 +0x372
github.com/coopernurse/gorp.hookedselect(0xc208004840, 0x7f9aa13694b0, 6240, 0xc208318f30, 0x8ef6f0, 0x1f, 0xc208171b00, 0x1, 0x1, ...)
	/tmp/build/.heroku/g/src/bitbucket.org/lzb/arenad/Godeps/_workspace/src/github.rp/gorp.go:1492 +0x103
github.com/coopernurse/gorp.SelectOne(0xc208004840, 0x7f9aa13694b0, 0xc208004840, 8f30, 0x8ef6f0, 0x1f, 0xc208171b00, 0x1, 0x1, ...)
	/tmp/build/.heroku/g/src/bitbucket.org/lzb/arenad/Godeps/_workspace/src/github.rp/gorp.go:1425 +0x1dd
github.com/coopernurse/gorp.(*DbMap).SelectOne(0xc208004840, 0x736240, f6f0, 0x1f, 0xc208171b00, 0x1, 0x1, 0x0, 0x0)
	/tmp/build/.heroku/g/src/bitbucket.org/lzb/arenad/Godeps/_workspace/src/github.rp/gorp.go:1082 +0xdc
```
Around the time where the goroutine hangs the DB logs `LOG:  could not receive data from client: Connection reset by peer`.

**Comment by johto** [comment]
> I'm hitting an issue where libpq waits indefinitely on a dropped connection to a remote DB. This is probably b/c of some networking issue. Would it be possible for pq to support setting deadlines / timeouts on reads and writes?

What would you set those timeouts to?  `pq` can't tell the difference between a query taking literally an hour to execute, and the network connection being broken and the operating system not telling `pq` about it until after an hour.

You should talk to your network engineer about this, since AFAIK there's nothing we can do in application space.

**Comment by peter-mogensen** [comment]
That is not completely true ... There is something the application can do.
If the issue is a NAT router forgetting the connection so it looks like just dead, then supporting keepalives=on (and friends) in the DSN would be useful.

**Comment by johto** [comment]
> If the issue is a NAT router forgetting the connection so it looks like just dead, then supporting keepalives=on (and friends) in the DSN would be useful.

Keepalives are practically only useful for making the connection appear active to such a router.  Once the connection has already been dropped, you'll need TCP_USER_TIMEOUT, which is impossible to use in Go without disconnecting your sockets from the main event loop.

**Comment by peter-mogensen** [comment]
Yes... well... in my use case I know the timeout of the NAT router. So just supporting the standard Postgres keepalives would help me.
Otherwise you are almost correct. You'd have to create the socket yourself with syscall (or unix) packages and use os.NewFIle() to get a *os.File and then net.FileConn() to get a new.Conn to use with your own socket options.
