### ISSUE TITLE
Issue with time.Time

### ISSUE THREAD

**Issue by jamie-stackhouse** [lib/pq#341]
I'm pulling out a TIMESTAMP field, the output of the query from Psql is below.

```
               video_id               |       updated_at
--------------------------------------+-------------------------
 df64a0a4-aa2b-4d96-8956-e9c324550b51 | 2014-12-03 09:50:21.583
```

This populates a struct inside Go.

```
{
 Id: (string) (len=36) "df64a0a4-aa2b-4d96-8956-e9c324550b51",
 Times: (models.Times) {
  CreatedAt: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
  UpdatedAt: (time.Time) 2014-12-03 09:50:21.583 +0000 +0000,
  DeletedAt: (models.NullTime) {
   Time: (time.Time) 0001-01-01 00:00:00 +0000 UTC,
   Valid: (bool) false
  }
}
```

I think the timestamp is incorrectly parsed? Note the double +0000 +0000 at the end of the UpdatedAt.

Or is this because of the usage of FixedZone?

**Comment by jamie-stackhouse** [comment]
My issue is that I am using this to set the Last-Modified HTTP header, which is supposed to be the format RFC1123.

Now, however when I pull the date from Postgres, which is stored as UTC dates, it is stored in a TIMESTAMP field, which doesn't have any TZ information, so in Go, when it does a Format call, this code section runs.

http://golang.org/src/time/format.go?s=12714:12756#L572

Which unfortunately ends up outputting the TZ as +0000 instead of UTC, or GMT.

In my case, I have to use this to get my timestamp to format properly now, but I don't think this is something the driver could/should fix.

```
timestamp.In(GMTLocation).Format(time.RFC1123)
```

**Comment by johto** [comment]
> Or is this because of the usage of FixedZone?

That's exactly what it is, yes.  There's a discussion in #329 on whether this should be changed or not, but that bottom line is that any answer we can give is going to be wrong.

I'd like to point out that storing UTC times in "timestamp without time zone" fields is not idiomatic Postgres.  "timestamp *with* time zone" is much better.

**Comment by jamie-stackhouse** [comment]
For others, if you are explicitly working with times from HTTP, instead of using one of the defined HTTP time specs, it would appear that http.TimeFormat is ideal, it hardcodes GMT as the 3-letter-code for both parses and formats.
