### ISSUE TITLE
is the listener channel a buffered one??

### ISSUE THREAD

**Issue by seshu3564** [lib/pq#343]
is the listener channel which listen to notifications from postgres a buffered one can two signals wait or will they be lost??

**Comment by johto** [comment]
It's [buffered](https://github.com/lib/pq/blob/72d960fe96ac86dfd376b0de7ca81c0334838d0b/notify.go#L648), and it guarantees that [no notifications are ever lost](https://github.com/lib/pq/blob/72d960fe96ac86dfd376b0de7ca81c0334838d0b/notify.go#L736).

**Comment by seshu3564** [comment]
thanks for the info :) :+1:

**Comment by johto** [comment]
Just to make sure there's no miscommunication here, there *is* a case where notifications can be lost.  Quoth the [documentation](http://godoc.org/github.com/lib/pq):

```
A notification channel will remain open until Unlisten is called, though connection
loss might result in some notifications being lost. To solve this problem, Listener
sends a nil pointer over the Notify channel any time the connection is re-established
following a connection loss.
```
