### ISSUE TITLE
Statement with escape

### ISSUE THREAD

**Issue by tux-eithel** [lib/pq#347]
Hello!
I'm using jsonb in Postgres, and I have to escape many character. The query is complex, so i found a simple example where this "bug" came out. I don't know if is a bug or a bad escape from mine.

Here the query example
```go
db.Query(`SELECT E'\'SELECT  $1 \''`,"TEST")
```
And this is the error:
> sql: statement expects 0 inputs; got 1

My complex query who need to be escaped is very similar to this one

```sql
SELECT xmlelement(name stores,
query_to_xml(E'
SELECT
	data->>\'Label\' AS label,
	data->>\'Address\' AS address,
	data->>\'City\' AS city,
	data->>\'Zip\' AS zip,
	data->>\'Province\' AS province,
	data->>\'Region\' AS region,
	data->>\'Lat\' AS lat, 
	data->>\'Log\' AS lng, 
	34 AS promo
from stores WHERE data->>\'Label\' = $1', true, true, '')
) AS xml_column
```
and gives the same error above (data is jsonb column type).
If you replace `$1` with `\'TEST\'` the query works.

**Comment by johto** [comment]
> Here the query example
> 
> db.Query(`SELECT E'\'SELECT  $1 \''`,"TEST")
> And this is the error:
> 
> sql: statement expects 0 inputs; got 1

The placeholder $1 is inside a quoted value, so it's not treated as a parameter.  You probably want something like:

```
db.Query(`SELECT 'SELECT '||quote_literal($1)`, 'TEST')
// or
db.Query(`SELECT format('SELECT %L', $1)`, 'TEST')
```

**Comment by tux-eithel** [comment]
Thanks @johto !
I was not sure to open a bug, because i had some suspect it has been a sql string error.
Thanks again for the help, and sorry for open a ""bug""
