### ISSUE TITLE
JSONB support

### ISSUE THREAD

**Issue by pkieltyka** [lib/pq#348]
Hello,

This is as much a question... does this driver fully support JSONB columns? thank you.

**Comment by johto** [comment]
Yes.  They work exactly the same way as any text columns as far as this driver is concerned.

**Comment by msaron** [comment]
You can use the [JSONText](https://github.com/jmoiron/sqlx/blob/master/types/types.go) type from the sqlx library. According to the type description on the web site:

`JSONText is a json.RawMessage, which is a []byte underneath. Value() validates the json format in the source, and returns an error if the json is not valid.  Scan does no validation.  JSONText additionally implements `Unmarshal`, which unmarshals the json within to an interface{}.`

**Comment by utkarsharma2** [comment]
Hey, I'm trying to run this query via this driver, it's now working for me. I'm not sure if this is an issue with driver or not. Working fine in Postgres console.

UPDATE Vertex SET Save=jsonb_set(Save,'{Schema}', '{"employee_age": "employee_age"}') WHERE Name=test

any pointers?

**Comment by johto** [comment]
> I'm not sure if this is an issue with driver or not. Working fine in Postgres console.
> 
> UPDATE Vertex SET Save=jsonb_set(Save,'{Schema}', '{"employee_age": "employee_age"}') WHERE Name=test
> 
> any pointers?

Surely there's an error for us to look at?
