### ISSUE TITLE
Driver Bad Connection

### ISSUE THREAD

**Issue by ET-CS** [lib/pq#349]
Hello.
Hi, I've created a golang app which uses lib/pq. thank you for a great lib!.

Everything is working fine, and I've just released the app to BETA stages after months of coding, but now - on testing, we discovered a fatal situation. from time to time (day or more), the entire app is failing - and every call to db is failing with "Driver Bad Connection" error. To fix this I just need to reload the entire app, so the connection will be created again. it's not an postgres issue I guess, as I don't need to restart postgres - only the webapp I wrote. then everything goes back to normals, but it's unacceptable to have daily fail of the entire system.

What I did is:
* `db = sql.Open("postgres", connStr)` once in the app loading
* `db.Prepare()` all statments, right after it.

I've talked with the great guys at #go-nuts IRC channel, and they've sayd it's probably a driver bug. the connection should not broken if nothing happens to the postgres service, and I don't set any max to the pool, nor it doesn't seem that I polluted it.

What more information can I supply to help understand why is my db connection is lost?

Meanwhile, I'll try to ping the db before each request to server - and if pq driver will return "Driver Bad Connection" I'll just reinit everything from start, but do you have any idea to you this is happening?

Thank you in advance!,

**Comment by johto** [comment]
First of all, what's the *exact* error you're seeing?  "Driver Bad Connection" is not anything pq or database/sql emits.

Secondly, is that the first error you're seeing?  Are you logging all errors from the application?

**Comment by ET-CS** [comment]
Thank you for your amazingly quick answer. 
For the exact error, I'd wait till it will show again.

For the logging - I am sorry to say I am not. I'll try now to add some logging to see if any error is occurring before. thank you.

**Comment by ET-CS** [comment]
I've implemented now logging on my app.Handler() using supervisord to log all into file. I'll update when the problem will occur again.

Thank you!

**Comment by ET-CS** [comment]
Hi @johto 

I have more details about the error, as It crushed again with : "driver: bad connection" error

I've logged all stdio stderr and nothing special occurred before the problem. There were few errors, but there were hours before.
the last error were at 2015/03/16 16:38:41 where the `driver: bad connection` error problem started at 21:02:23

those are the last lines in the log file:
```
2015/03/16 17:38:24 please login
2015/03/16 17:39:14 please login
2015/03/16 18:08:24 please login
2015/03/16 21:02:23 driver: bad connection
2015/03/16 21:02:26 driver: bad connection
2015/03/16 21:02:27 driver: bad connection
2015/03/16 21:02:28 driver: bad connection
2015/03/16 21:04:01 driver: bad connection
2015/03/16 21:26:54 driver: bad connection
2015/03/16 21:36:00 driver: bad connection
```
Where 'please login' is shouldn't supposed to be an error at all, it's some ajax call i've made that require login, and it's clearly not the problem as it occurred almost 3 hours before the bad connection problem.

While writing those lines, I've tried to login into PhpPgAdmin (to see request log), and it didn't let my login, so I've restarted postgres and could login again...... and the website returned to work without restarting it (Does it suppose to return to itself when db fall and then working again even if I create a db connection once in the app init? because if yes - it's awesome!)... So it clearly a postgres problem (I am running on CentOS 7 btw),
but interesting though, that In the last times it happened - I didn't tried or had to restart postgresql ... by only restarting my app it returned working again. So I don't know now if the problem is in postgres or at the go side.

I never had problems with postgresql, so I guess I'll have to go deeper now to find what really the problem is.

**Comment by ET-CS** [comment]
If anyone gets here, I found the problem:

after some running time, the app started throwing "Driver Bad Connection" on every db access (and phpPgAdmin couldn't login) - so restart of either postgresql or my app both fixed this situation. the problem was that I polluted the connection pool.

I had a `return` statement inside `for rows.Next()` which left an open connection each time the function executed until the db connection was lost.

To find what statement blocked my pool I used: `SELECT * FROM pg_stat_activity;` from `psql` shell.

**Comment by johto** [comment]
Out of interest, were you using an old version of `pq`?  Newer versions should give a better error message in these situations.

**Comment by ET-CS** [comment]
postgres (PostgreSQL) 8.4.20
Postgres log file didn't helped me at all. only by running `SELECT * FROM pg_stat_activity;` I saw exactly what blocking my server

**Comment by alex-fedorov** [comment]
@ET-CS 

Good day,

Sorry for jumping into the thread after so much time of inactivity.

So, how did you manage not to `return`from from `for rows.Next() { ... }`? What should one do, when `err := rows.Scan(...); err != nil`?

**Comment by danmondy** [comment]
That shouldn't be a problem if you already defer rows.Close() ...am i right?

**Comment by juburr** [comment]
Whenever a connection leak results in the database pool being fully consumed, my experience has been that the next call to get a connection will just hang. I haven't noticed a "bad connection" error message in that circumstance. Restarting your service will of course fix the issue, albeit temporarily.

**Comment by prithvihv** [comment]
```go

func main() {
	db := db_psql.DBConnect("postgres", "blah", db_psql.DB_OPTIONS{
		USER: "postgres",
		PASS: "postgres",
		HOST: "localhost",
		DB:   "postgres",
		APM:  false,
	})
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)
	db.SetConnMaxIdleTime(4 * time.Minute)
	db.SetConnMaxLifetime(0)

	fmt.Println("running first query")
	r, err := db.Query(`select * from games`)
	for r.Next() {
		break
	}

	fmt.Println("running second query")
	r, err = db.Query(`select * from games`)
	fmt.Println(err)
}
```

Experiment code to test behavior

**Comment by kcchandra-w6** [comment]
Does the Max Open Connection have something to do with the total Idle Conns? Should we have the same number of open connections as the idle ones?
