### ISSUE TITLE
Syntax error at end of input

### ISSUE THREAD

**Issue by mikeroosa** [lib/pq#350]
Trying to build a sample app and can't open a connection to the database. Everything works fine with psql so not sure what I'm doing wrong.

db, err := sql.Open("postgres", "host=localhost dbname=postgres user=postgres password=postgres sslmode=disable")

This is the error:
pq: syntax error at end of input

If I leave off password or username then I get a different error. For example, if I don't include the password, I get:
pq: password authentication failed for user "postgres"

What is wrong with my code or setup?

**Comment by mikeroosa** [comment]
I'm on Windows 7 running 9.4 for postgres.

**Comment by uhoh-itsmaciek** [comment]
For posterity, what was wrong with your code or setup? At first glance, your connection string looks legit, so we should at least be giving a better error.

**Comment by mikeroosa** [comment]
It was a dumb error on my part. The actual syntax error was from the select statement I had on the next line.
