### ISSUE TITLE
Insert into JSON column using Exec parameters

### ISSUE THREAD

**Issue by bithavoc** [lib/pq#361]
Hi,

I'd like to know how to insert JSON data in a JSON column, currently my program throws:

`2015/04/10 16:44:45 pq: unrecognized node type: 2100`

My code is as simple as:

```go
payloadStr := `
		{
			"input": {
				"name": "johan",
				"tags": ["good", "review", "post", "stuff"],
				"age": 25
			}
		}
		`
		_, err = db.Exec(`INSERT INTO events(time, name, payload) VALUES('2015-02-01', 'trial2', $1);`, payloadStr)
		if err != nil {
			log.Fatal(err)
		}
```

Any tips?

**Comment by johto** [comment]
> 2015/04/10 16:44:45 pq: unrecognized node type: 2100

That looks like a postgres bug to me.

**Comment by bithavoc** [comment]
@johto yeah I thought so it, but then this works so it doesn't make sense :(

```go 
sql := ` INSERT INTO events(time, name, payload) VALUES('2015-02-01', 'trial2', '
		{
			"input": {
				"name": "johan",
				"tags": ["good", "review", "post", "stuff"],
				"age": 25
			}
		}')
		`
		_, err = db.Exec(sql)
		if err != nil {
			log.Fatal(err)
		}
```
looks like it's the parameter pass

**Comment by uhoh-itsmaciek** [comment]
@bithavoc what Postgres version?

**Comment by bithavoc** [comment]
Sorry, false alarm. I've been told by CitusData that CitusDB doesn't support `PREPARE` which I'm guessing is what the parametized values are using.

The CitusData team told me to manually concatenate the INSERT string so it doesn't use `$1`, is there a public method in this library that allows me to escape the JSON value into single quotes like described here? 

http://www.postgresql.org/docs/9.4/static/sql-syntax-lexical.html

If not, feel free to close this issue.

**Comment by johto** [comment]
> The CitusData team told me to manually concatenate the INSERT string so it doesn't use $1, is there a public method in this library that allows me to escape the JSON value into single quotes like described here?

No, there isn't anything in the package.  Note that you also have to pay attention to the server's version and/or the value of standard_conforming_strings to do that correctly.

**Comment by bithavoc** [comment]
thanks, np.

**Comment by cbandy** [comment]
@bithavoc I'm curious, can you provide a link to CitrusData/CitrusDB?

**Comment by cbandy** [comment]
> @bithavoc I'm curious, can you provide a link to CitrusData/CitrusDB?

Nevermind! Reading is not my forte!

**Comment by bithavoc** [comment]
:joy: allright. the `PREPARE` issue I was told via email, the docs are a little bit outdated they say.

**Comment by bithavoc** [comment]
btw, I ended up using [dollar-quoted string constants](http://www.postgresql.org/docs/current/interactive/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) for this.

Example:

```go
    _, err = db.Exec(fmt.Sprintf(`INSERT INTO events(time, name, payload) VALUES('2015-02-01', 'trial2', $$%s$$);`, "O'Connor")
```

**Comment by uhoh-itsmaciek** [comment]
@bithavoc keep in mind if that data is not trusted input, you're leaving yourself open to SQL injection:


```go
    _, err = db.Exec(fmt.Sprintf(`INSERT INTO events(time, name, payload) VALUES('2015-02-01', 'trial2', $$%s$$);`, "$$); DROP TABLE events; --")
```

will drop the events table.
