### ISSUE TITLE
tls: stuck on dead connections

### ISSUE THREAD

**Issue by robx** [lib/pq#367]
We regularly run into situations where a call to `Exec` is uninterruptibly stuck:

```
goroutine 121 [IO wait, 114 minutes]:
net.(*pollDesc).Wait(0xc20b251100, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20b251100, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20b2510a0, 0xc2088b7400, 0x400, 0x400, 0x0, 0x7fcb29416c48, 0xc20a0f0040)
    /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080b84a8, 0xc2088b7400, 0x400, 0x400, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc209f220c0, 0x7fcb29420398, 0xc2080b84a8, 0x5, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20bcd6840, 0x14, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*clientHandshakeState).readFinished(0xc20b6b3a70, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/handshake_client.go:538 +0x5e
crypto/tls.(*Conn).clientHandshake(0xc20bcd6840, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/handshake_client.go:209 +0x1b87
crypto/tls.(*Conn).Handshake(0xc20bcd6840, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:977 +0xf1
crypto/tls.(*Conn).Write(0xc20bcd6840, 0xc209cf6521, 0x64, 0x1ff, 0x0, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:845 +0x57
github.com/lib/pq.(*conn).send(0xc209cf6500, 0xc20b6cbb00)
    /var/chef/cache/src/realzeit.io/rtb/Godeps/_workspace/src/github.com/lib/pq/conn.go:693 +0x194
github.com/lib/pq.(*conn).startup(0xc209cf6500, 0xc20aa6e6f0)
    /var/chef/cache/src/realzeit.io/rtb/Godeps/_workspace/src/github.com/lib/pq/conn.go:997 +0x37d
github.com/lib/pq.DialOpen(0x7fcb294202e0, 0xbaa350, 0xc208235310, 0x4d, 0x0, 0x0, 0x0, 0x0)
    /var/chef/cache/src/realzeit.io/rtb/Godeps/_workspace/src/github.com/lib/pq/conn.go:214 +0xee3
github.com/lib/pq.Open(0xc20803bac0, 0x3e, 0x0, 0x0, 0x0, 0x0)
    /var/chef/cache/src/realzeit.io/rtb/Godeps/_workspace/src/github.com/lib/pq/conn.go:118 +0xa1
github.com/lib/pq.(*drv).Open(0xbaa350, 0xc20803bac0, 0x3e, 0x0, 0x0, 0x0, 0x0)
    /var/chef/cache/src/realzeit.io/rtb/Godeps/_workspace/src/github.com/lib/pq/conn.go:40 +0x56
database/sql.(*DB).conn(0xc20805c000, 0xc20802a8d0, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:664 +0x506
database/sql.(*Stmt).connStmt(0xc208060b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:1398 +0x57b
database/sql.(*Stmt).Exec(0xc208060b00, 0xc20890d278, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:1307 +0xe3
```

As far as I understand, lib/pq doesn't expose any way to timeout such queries.

It seems that usually there is some database "problem" involved. For example, this happened once when  a tables was locked due to a vacuum run. So far, the connection has never recovered.

I'm still trying to reproduce the problem. I assume that some trouble on the network layer is involved.

Any insight appreciated, even if you tell me why lib/pq shouldn't deal with this.

**Comment by robx** [comment]
We have since switched to a tls-less setup, and the stuck connections have not shown up anymore. This doesn't quite prove that it's a tls issue since other factors changed, but a pretty strong indicator.

**Comment by johto** [comment]
Sorry, I must have missed this issue before.

Hmm.  What's weird here is that this happens during the startup sequence, and not later on as practically everyone else's problems.  Which Go version were you running when this happened?

**Comment by robx** [comment]
I'm 99% sure we still saw these on go1.4.2, though the timeline is a bit muddled. I'm also less sure they went away due to not using SSL anymore. We had these issues very reliably while accessing a remote postgres server with SSL. A week ago, we moved servers and are now running postgres locally, so the network is a lot more reliable, which might be why we don't see the problem anymore.

**Comment by robx** [comment]
Let's close this, if this were still an issue with current go versions I'm sure the ticket would have seen some activity.
