### ISSUE TITLE
How do I use parameters in JSON queries

### ISSUE THREAD

**Issue by dlsniper** [lib/pq#368]
Hi,

I'm using this library, on commit 93e9980741c9e593411b94e07d5bad8cfb4809db, with Postgres 9.4.1 and Go 1.4.2 but I can't seem to be able to make a JSON query work as I'd expect it to.

As I'm not sure if this is an issue with the library, my understanding on how Postgres should work, both or none, I kindly ask for some help / advice.

Here's the query, and you can see the rest of the details below:
```sql
SELECT json_data FROM demo_table WHERE json_data @> '{"id": $1, "otherid": $2, "boolfld": $3}'
```

I have the following table:
```sql
CREATE TABLE demo_table (
  json_data JSONB NOT NULL
);
CREATE INDEX ON demo_table USING GIN (json_data jsonb_path_ops);
```

and the following code:
```go
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/lib/pq"
)

func main() {
	var conninfo string = "postgres://user:pass@127.0.0.1/database_name?sslmode=disable"

	db, err := sql.Open("postgres", conninfo)
	if err != nil {
		panic(err)
	}

	query := `SELECT json_data FROM demo_table WHERE json_data @> '{"id": $1, "otherid": $2, "boolfld": $3}'`

	var result string
	err = db.QueryRow(query, "some string", "some other string", true).
		Scan(&result)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Got back %q", result)
}

```

What I get back from Postgres is:
```
panic: pq: invalid input syntax for type json
```

and the server logs say:
```
2015-05-15 13:19:11 CEST [7974-1] user@database_name ERROR:  invalid input syntax for type json at character 57
2015-05-15 13:19:11 CEST [7974-2] user@database_name DETAIL:  Token "$" is invalid.
2015-05-15 13:19:11 CEST [7974-3] user@database_name CONTEXT:  JSON data, line 1: {"id": $...
2015-05-15 13:19:11 CEST [7974-4] user@database_name STATEMENT:  SELECT json_data FROM demo_table WHERE json_data @> '{"id": $1, "otherid": $2, "boolfld": $3}'
```

Is there something I'm missing or should I be better of composing the query myself using ```fmt.Sprintf()`` (for example).

Thank you for your time and help.

**Comment by johto** [comment]
> `'{"id": $1, "otherid": $2, "boolfld": $3}'`

$1, $2 and $3 are not parameter placeholders in this case, since they're inside a string literal.  You'd have to do something like  `json_object(ARRAY['id',$1,'otherid',$2,'boolfld',$3])::jsonb`  or build the entire JSON string in the client and send that over as a single parameter.

**Comment by dlsniper** [comment]
I suspected that this might be the case, thank you for your fast reply!

**Comment by szxp** [comment]
Thank you @johto for your help.
I had a similar issue bit in my case I had values of different types in the json object. What worked for me was something like this:
```
select jdoc from ad_form where jdoc @> json_build_object('formID',$1::text,'userID',$2::bigint)::jsonb
```
