### ISSUE TITLE
Support for Postgres Custom Variables

### ISSUE THREAD

**Issue by ejayben** [lib/pq#369]
Hi,

I'm using database/sql and need to set a custom variable using SET_CONFIG / CURRENT_SETTING functions in postgres but it does not appear to work in golang. The example is showing how I set a custom variable called "custom_class.session_username" with the value "my_username" (some error handling left out for brevity). When I use the SET_CONFIG / CURRENT_SETTING commands inside PSQL it works as expected but does not work in golang with the database/sql library and lib/pq

```
func connectToDB() (db *sql.DB) {
    var err error
    dsn := "postgres://my-dsn-string"
    db, err = sql.Open("postgres", dsn)

    if err != nil {
        log.Fatal(err)
    }

    return db
}
```

And here is the problem example:
```
db := connectToDB()
defer db.Close()

test_tx, err_tx = db.Begin()

if(err_tx != nil) {
    log.Printf("%q", err_tx)
}

query1 := "SELECT SET_CONFIG('custom_class.session_username', $1, FALSE)"
res1, err1 := test_tx.Query(query1, "my_username")

if(err1 != nil) {
    log.Print("Error setting username")
}
res.Close()

query2 := "SELECT CURRENT_SETTING('custom_class.session_username')"
res2, err2 := tx.Query(query2)

if(err2 != nil) {
    log.Print(err2)
} else {
    var username string
    res2.Scan(&username)
    log.Print("session username in postgres=" + username)
   res2.Close()
}

test_tx.Commit()
```

The problem is that the "username in postgres=" print statement is empty. The session username is never coming back correctly from postgres.

I'm new with database/sql but read up on the "gotchas" regarding connections and my understanding is that transactions will guarantee a single connection is used. Therefore my logical conclusion is that the SET_CONFIG and / or CURRENT_SETTING functions in postgres are broken with lib/pq.

**Comment by uhoh-itsmaciek** [comment]
> Therefore my logical conclusion is that the SET_CONFIG and / or CURRENT_SETTING functions in postgres are broken with lib/pq.

Given the way pq works--it doesn't know anything about the content of the queries--this seems unlikely. Are you running the `current_query` setting in the same transaction? With `database/sql`'s built-in pooling and its lack of a concept of sessions, a `set_config` will only effect one of your connections unless you're within a single transaction (or I think a prepared statement).

**Comment by ejayben** [comment]
Yes I am using a single transaction. Part of my concern comes from this page: http://go-database-sql.org/surprises.html. Specifically the "Invoking Stored Procedures" section. My concern is that there is a postgres specific issue hidden within lib/pq that is failing silently.

**Comment by uhoh-itsmaciek** [comment]
I don't think so. Can you provide a standalone test case (or one as part of the test suite)? You should be able to add a test based on your code above and some of our existing tests like say [this one](https://github.com/lib/pq/blob/master/conn_test.go#L673-L686).

**Comment by johto** [comment]
> query1 := "SELECT SET_CONFIG('custom_class.session_username', $1, FALSE)"
> query2 := "SELECT CURRENT_SETTING('custom_class')"

There's a wild difference here; was that unintentional?

**Comment by johto** [comment]
> res2.Scan(&username)

Also, ignoring errors like this is really bad style.  Just use QueryRow() if you only care about the first row in the result set.

**Comment by ejayben** [comment]
Okay, I will add the test.

@johto thanks for the reply. I had to rewrite this code example to remove the company IP specific parts and looks like I typoed.  I did in fact test this and received a "pq: unrecognized configuration parameter" error when they had a mismatch. Also the real code has full error handling. It was simply for brevity.

**Comment by johto** [comment]
> Also the real code has full error handling. It was simply for brevity.

I can't count the number of times people have thought there's something wrong with the driver when the problem is lack of error handling.  With a report like this it's impossible for us to tell.

**Comment by ejayben** [comment]
I will edit the example to properly represent the real code error handling

**Comment by johto** [comment]
I just wrote this and it worked just fine:

```go
package main

import (
	_ "github.com/lib/pq"
	"database/sql"
	"fmt"
)

func main() {
	db, err := sql.Open("postgres", "host=/tmp")
	if err != nil {
		panic(err)
	}

	txn, err := db.Begin()
	if err != nil {
		panic(err)
	}
	_, err = txn.Exec("SELECT set_config('foo.bar', $1, FALSE)", "bar bar bar")
	if err != nil {
		panic(err)
	}
	var foobar string
	err = txn.QueryRow("SELECT current_setting('foo.bar')").Scan(&foobar)
	if err != nil {
		panic(err)
	}
	fmt.Println(foobar)
}
```

**Comment by johto** [comment]
> // check err1, nothing here, the custom variable for this session should be set to my username
> res.Close()

Also, here, don't use Query() if you don't care about the result.  If something went wrong here, the error would be returned by res.Close(), and that doesn't appear to be checked.

**Comment by ejayben** [comment]
Thanks johto. Using your method has resolved the issue.
