### ISSUE TITLE
invalid parameter warning

### ISSUE THREAD

**Issue by tp** [lib/pq#372]
I get the the following panic when running this statement:

panic: 
`panic: pq: got 2 parameters but the statement requires 0`

statement:
```
tx.MustExec(`DO
$do$
BEGIN
IF EXISTS (SELECT 1 FROM dbversion WHERE key = $1 AND intvalue = $2) THEN
  RAISE EXCEPTION 'unexpected version';
END IF;
END
$do$`, dbVersionKey, 10)
```

I can't seem anything wrong with this but did not find any example of using functions with pq, so I am not sure if I am missing something.

**Comment by cbandy** [comment]
`$1` and `$2` are part of the string literal delimited by the `$do$` dollar-quotes.

**Comment by uhoh-itsmaciek** [comment]
To clarify, it's not pq complaining about extra parameters here--it's Postgres. Are you actually getting a panic from pq, though, rather than just an error? That doesn't seem right--we should just return a normal Postgres error in this case.

**Comment by tp** [comment]
I think it just panics because I used "MustExec", that is not an issue. Will try to fix my statement then if it's PSQL's error.

**Comment by tp** [comment]
Thanks for the explanation @cbandy. :clap: 

I was able to gain a better understanding of functions in postgres and have since rewritten the code like this:

```go
		tx.MustExec(`
			CREATE OR REPLACE FUNCTION ensureSchemaVersion(key text, version int) RETURNS INT
			AS $$
				BEGIN
				IF NOT EXISTS (SELECT 1 FROM dbversion dbv WHERE dbv.key = $1 AND dbv.intvalue = $2) THEN
				  RAISE EXCEPTION 'unexpected version';
				END IF;
					RETURN $2;
				END;
			$$ LANGUAGE plpgsql;
		`)

		tx.MustExec("select ensureSchemaVersion($1, $2)", dbVersionKey, 0)
```

Sorry for suspecting pq, when it was my fault.
