### ISSUE TITLE
conn.Exec hangs on `if cn.bad {`

### ISSUE THREAD

**Issue by EricLagerg** [lib/pq#374]
I've this simple query:

```go
_, err := database.DB.Exec(`DELETE
		FROM jobs
		WHERE job_id = $1`, j.ID)
if err != nil { /* handle error */ }
```

I can run the query fine through PostgreSQL's command line, but with Go it hangs.

I get up to https://github.com/lib/pq/blob/master/conn.go#L731, but then it hangs.

Inserting a 
```go
fmt.Printf("%+v\n, cn)
```

before the `if cn.bad ...` outputs this:

```go
&{c:0xc20802abe8 buf:0xc208050a20 namei:0 scratch:[73 0 0 0 5 84 32 52 0 66 75 117 114 77 118 74 71 50 52 103 112 67 51 110 80 53 76 84 112 101 80 55 110 69 78 72 89 99 0 0 0 21 101 114 105 99 64 115 101 114 109 111 100 105 103 105 116 97 108 46 99 111 109 0 0 0 10 50 48 49 53 45 48 55 45 48 50 255 255 255 255 0 0 0 4 0 0 0 0 101 0 0 0 65 39 0 5 0 0 4 58 0 4 255 255 255 255 0 0 106 111 98 95 116 121 112 101 0 0 0 65 39 0 3 0 0 0 23 0 4 255 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] txnStatus:73 parameterStatus:{serverVersion:90404 currentLocation:0xc208050ae0} saveMessageType:0 saveMessageBuffer:[] bad:false disablePreparedBinaryResult:false}
```

Using mailgun's godebug allows me to step up to `if cn.bad ...`, but won't let me print any of the variables or step through anything else -- it hangs.

Adding `SET statement_timeout=10000` doesn't change anything -- it still hangs.

**Comment by uhoh-itsmaciek** [comment]
Do other queries run fine? Is it just this one that hangs? Does setting a much lower statement_timeout help (note that you'll need to do this in a transaction, since `database/sql` doesn't really do sessions).

**Comment by EricLagerg** [comment]
Yes, other queries run fine.

By transaction, you mean outside of `db.Exec(...)`?

**Comment by uhoh-itsmaciek** [comment]
Yes, I mean you want to run [db.Begin](http://godoc.org/database/sql#DB.Begin), and then run the `SET` and the query via the `Tx`, since otherwise, the `SET` and the query could run in two separate connections because `database/sql` doesn't do sessions.

**Comment by uhoh-itsmaciek** [comment]
Also, what Postgres version and what is the exact statement you are running via psql?

**Comment by EricLagerg** [comment]
Gotcha. I'm running PostgreSQL version 9.4.4 on Arch Linux.

The exact statement I'm running is the one in the OP.

It ends up being `DELETE FROM jobs WHERE job_id = IbUjtw28QehVW726KGeSZPSySaCtpTIt`

`job_id` is a random 32-character, alphabetic string.

**Comment by uhoh-itsmaciek** [comment]
Interesting. I thought you might be getting bitten by planning since the pq version includes a parameter whereas you've inlined it in psql, but that shouldn't be the case on 9.4. Can you try running

```sql
PREPARE foo(text) AS DELETE FROM jobs WHERE job_id = $1;
EXECUTE foo('IbUjtw28QehVW726KGeSZPSySaCtpTIt');
```

in psql and see if that hangs? That's closer to what pq is doing under the hood when you pass a parameter. Alternately, can you try inlining that parameter in Go? That is, running something like

```go
_, err := database.DB.Exec(`DELETE
        FROM jobs
        WHERE job_id = 'IbUjtw28QehVW726KGeSZPSySaCtpTIt'`)
if err != nil { /* handle error */ }
```

**Comment by EricLagerg** [comment]
```
go_test=# select * from jobs;
              job_id              |        user_id        | job_type | start_date | end_date 
----------------------------------+-----------------------+----------+------------+----------
 o3QhmM3LGkxqd38ziHD8trHmiyACBbqP | eric@sermodigital.com |        0 | 2015-07-02 | 
 IbUjtw28QehVW726KGeSZPSySaCtpTIt | eric@sermodigital.com |        0 | 2015-07-02 | 
 CswljEpytmshHmgHFf5YCjbEjR6vSFfe | eric@sermodigital.com |        0 | 2015-07-02 | 
 N2nBKurMvJG24gpC3nP5LTpeP7nENHYc | eric@sermodigital.com |        0 | 2015-07-02 | 
 wqFjk6xYHiHb1SfQZHMkDE4fgPT4JCXX | eric@sermodigital.com |        0 | 2015-07-02 | 
 DEHtFxmEdMYiTItBUksFfaRtjNM8vxoq | eric@sermodigital.com |        0 | 2015-07-02 | 
(6 rows)

go_test=# PREPARE foo(text) AS DELETE FROM jobs WHERE job_id = $1;
PREPARE
go_test=# EXECUTE foo('IbUjtw28QehVW726KGeSZPSySaCtpTIt');
DELETE 1
go_test=# 
``

**Comment by EricLagerg** [comment]
Inlining it still causes it to hang.

**Comment by EricLagerg** [comment]
I should also mention that 'hang' means it hangs so much that I need `kill -9 <pid>` in order to kill my server. Normally, even on long-running functions, SIGINT works perfectly.

**Comment by uhoh-itsmaciek** [comment]
Interesting. Do you have `GOMAXPROCS` set?

**Comment by EricLagerg** [comment]
I do not. My app becomes fully unresponsive when it hangs.

**Comment by uhoh-itsmaciek** [comment]
Can you try setting GOMAXPROCS to 2 (or really anything greater than 1)? I've occasionally seen weird lockups when it's just 1, but not in recent Go versions...

**Comment by EricLagerg** [comment]
Hey, I fixed it. It's not an issue with pq.

My `remove` function (where I was executing the statement) is a method on a pointer to a struct, and that struct was being used inside a separate goroutine that I missed.

Commenting out the goroutine causes the statement to work as intended.

Still not 100% sure why the goroutine was causing a separate function to hang, but I'll figure that out.

Thanks for the help, @uhoh-itsmaciek

**Comment by uhoh-itsmaciek** [comment]
Cool, glad you got it figured out.
