### ISSUE TITLE
Not properly escaping passwords?

### ISSUE THREAD

**Issue by eatonphil** [lib/pq#376]
I have a password with a question mark in it.

I am able to call sql.Open with this password:

    sql.Open("postgres", "postgres://postgres:foo?bar@localhost/database?sslmode=disable")

But when I go to start a transmission I get this error:

    2015/07/06 23:09:13 dial tcp: unknown port tcp/<the-password-until-question-mark>

Where it displays my password up to the question mark. For instance if the password were "foo?bar" it displays only "foo".

It appears obvious it is treating the password like a url here but I do not see why the question mark is invalid.

Is there an immediate way around this?

**Comment by uhoh-itsmaciek** [comment]
I don't believe '?' is a valid URI password character (or at least, Go's `net/url.Parse` and Ruby's `URI.parse` don't like it, although the way `net/url.Parse` fails is pretty dumb). Try percent-encoding the question mark to `%3f` and see if that works.

**Comment by uhoh-itsmaciek** [comment]
Hmm, although Python agrees with Go here:

```console
>>> from urllib.parse import urlparse
>>> o = urlparse("postgres://postgres:foo?bar@localhost/database?sslmode=disable")
>>> o
ParseResult(scheme='postgres', netloc='postgres:foo', path='', params='', query='bar@localhost/database?sslmode=disable', fragment='')
```

**Comment by uhoh-itsmaciek** [comment]
And for what it's worth, psql itself seems to like the url just fine...

**Comment by cbandy** [comment]
N.B. https://tools.ietf.org/html/rfc3986#section-3.2

> The authority component is preceded by a double slash ("//") and is **terminated by the next** slash ("/"), **question mark ("?")**, or number sign ("#") character, or by the end of the URI.

**Comment by uhoh-itsmaciek** [comment]
Thanks, @cbandy--I had briefly looked through that but couldn't find the relevant info. So I think in this case, I think Go and Python are doing the right thing (although Python should really reject that as a URI since [PORT is defined to be numeric](https://tools.ietf.org/html/rfc3986#section-3.2.3)), Ruby is off in its own world but at least rejected that, too, and I'm not really sure what psql was doing...

**Comment by johto** [comment]
Percent-encoding the question mark works in both libpq and lib/pq, so I'm closing this issue.  We don't need to be bug-for-bug compatible with libpq, and its behavior is clearly in violation of the spec here.
