### ISSUE TITLE
Integers in scientific notation not properly read

### ISSUE THREAD

**Issue by Canop** [lib/pq#377]
Sometimes, postgresql formats the returned integer using a scientific notation, for example `1.0529587e+07`.

This especially seems to happen when you query an approximation of the number of records in a table with `reltuples`:

	sql := "select reltuples from pg_class where relname='my_table_name'"
	var count int
	db.QueryRow(sql).Scan(&count)
	
The problem here is that count isn't properly parsed, I get `0`.

There's an obvious workaround : read the value in a field of type `string` and parse it in Go but this probably should not be needed.

**Comment by uhoh-itsmaciek** [comment]
It looks like `pg_class.reltuples` is a `float4` not an integer (not sure why). Try casting to integer or bigint? Do you get an error from the `Scan`?

**Comment by Canop** [comment]
Yes, it's a `real`, you're right.
And yes, there's a scan error in the conversion: invalid syntax.

**Comment by Canop** [comment]
Converting to int in the query also works.

**Comment by ralt** [comment]
Or rather, is there an appropriate Go type to represent a `real`?

**Comment by Canop** [comment]
Yes, it works with `float64` too
