### ISSUE TITLE
fails to connect when ssl disable and password not required.

### ISSUE THREAD

**Issue by james-lawrence** [lib/pq#378]
errors with authentication failure. particularly annoying for dev environments

**Comment by uhoh-itsmaciek** [comment]
Can you provide more details? What is your exact connection string (password and any other sensitive information redacted, of course), and how exactly do you connect through an alternate method (e.g., psql) that does work how you expect?

**Comment by james-lawrence** [comment]
I lied =D old environment, just finished debugging it. =)
