### ISSUE TITLE
QueryRow().Scan() Panic: slice bounds out of range

### ISSUE THREAD

**Issue by JamesMcMinn** [lib/pq#379]
I'm occasionally getting a panic while performing QueryRow().Scan(). So far, it has happened twice: once on the 11th of July, and again today on the 22nd. It's a query which gets run very frequently, so it's quite rare.

The relevant code:

    var tid int64
    err := tx.QueryRow("SELECT id FROM users WHERE id = $1", u.ID).Scan(&tid)

and the trace both times has been:
```
goroutine 23 [running]:
github.com/lib/pq.(*conn).errRecover(0xc2b6c6c780, 0xc2df544800)
	/home/james/go/src/github.com/lib/pq/error.go:482 +0x191
github.com/lib/pq.(*rows).Next(0xc2aa324960, 0xc2a2072010, 0x1, 0x1, 0x0, 0x0)
	/home/james/go/src/github.com/lib/pq/conn.go:1322 +0x415
database/sql.(*Rows).Next(0xc28507d7a0, 0x6eb5a0)
	/usr/lib/go/src/database/sql/sql.go:1592 +0x12e
database/sql.(*Row).Scan(0xc280aba240, 0xc2df544a08, 0x1, 0x1, 0x0, 0x0)
	/usr/lib/go/src/database/sql/sql.go:1710 +0x26d
main.(*DatabaseConnection).addOrUpdateUser(0xc20801eec0, 0x3135ae56, 0xc2d6c5ae20, 0x11, 0xc2dc857990, 0xf, 0xc2dc857989, 0x7, 0xc2d6c5ae40, 0x1d, ...)
```

Apart from a few small changes, the services was previously running without any similar issues, and it appears that the first occurrence on the 11th of July was soon after we rebuilt with a more recent version of the pq driver. 

Iit appears that it may be related to a recent commit, more specifically: https://github.com/lib/pq/commit/e93ec67d8918c251d520df5f0c417f79fd09cb65#diff-a2ddca1600f34abb91244424f8431c2cL1292

I'm running Go 1.4.2, so it's possible that it's simply a coincidence, however the timing does align with when we updated and the panics began.

Also possibly related: https://github.com/lib/pq/issues/60

**Comment by johto** [comment]
Hi,

Which exact commit are you running?  The line numbers in the stack trace don't make sense against current HEAD.

**Comment by uhoh-itsmaciek** [comment]
I'm going to close this as obsolete. Please reopen if you're still seeing this issue and can give us more information.
