### ISSUE TITLE
INSERT using now() and nextval() won't work

### ISSUE THREAD

**Issue by caarlos0** [lib/pq#380]
I'm trying to do this:

```go
sql := "INSERT INTO apps values(nextval('seq_apps'), ?, now())"
_, err := db.Exec(sql, "My App")
```

What I got is `pq: syntax error at or near ","`

I don't know if this is expected, if it's a bug, or if I'm doing something wrong.

BTW: I'm new to Go

**Comment by johto** [comment]
We don't use question marks for placeholders; use $1, $2, etc.  See https://godoc.org/github.com/lib/pq

**Comment by caarlos0** [comment]
ohhh, sorry.

Thanks!
