### ISSUE TITLE
Empty password makes host be lost

### ISSUE THREAD

**Issue by Unknwon** [lib/pq#382]
For example my connection string:

```
cnnstr: user=root password= host=10.0.0.10 port=5432 dbname=gogs sslmode=disable
```

In this case, the password somehow became `host=10.0.0.10` and so my host is default to localhost, which is not right.

**Comment by johto** [comment]
> In this case, the password somehow became host=10.0.0.10 and so my host is default to localhost, which is not right.

Looks like the correct behavior to me.  The parsing is supposed to be compatible with the C interface `libpq`, which behaves [the exact same way](https://github.com/postgres/postgres/blob/16c4e6d8dc8fb98cd32d9af473fb06a730fb40d3/src/interfaces/libpq/fe-connect.c#L4314).

If you really want to send the empty string as the password, use `password=''`.
