### ISSUE TITLE
IN Operator with composite keys

### ISSUE THREAD

**Issue by mission-liao** [lib/pq#385]
Is there a way to apply 'in' operator on composite keys? Suppose we have a table like that:
```sql
CREATE TABLE comments
(
   id   bigint,
   uid bigint,
   comment text,
   PRIMARY KEY(id, uid)
);
```

I can select via 'in' operator like this:
```sql
select * from comments where (id, uid) IN ((3, 1), (2, 1))
```

According to https://github.com/lib/pq/issues/240, 'IN (1, 2, 3)' would be converted to 'ANY(ARRAY[1, 2, 3])', but could this conversion be able to apply on composite keys? Or is there an alternative to 'in' operator I can try?

**Comment by johto** [comment]
Hrmph.  Seems like there's a missing feature or two in postgres here.  The best I can come up with is doing:

```sql
create type iduidtyp as (id bigint, uid bigint);

select * from comments where (id,uid) in
    (select (u).* from
        (select u from unnest($1::iduidtyp[]) uu(u) offset 0) ss );
```

and then pass an array of records as the input for $1, for example `{"(3,1)","(2,1)"}`.

Another way would be preparing a list of parameters and interpolating that into the query string so that the query looks like:

```sql
WHERE (id,uid) IN (($1,$2),($3,$4))
```

and then passing 3,1,2,1 as the parameters.

**Comment by cbandy** [comment]
JSON has a function to "unnest" only one "level." Here's something similar with JSON:

```sql
select * from comments where (id,uid) in
  (select (x->>0)::bigint, (x->>1)::bigint from json_array_elements($1) y(x));
```

Pass a JSON array of arrays: `'[[1,1],[2,2]]'`, i.e. `json.Marshal([][]int{{1,1},{2,2}})`.

**Comment by mission-liao** [comment]
@johto 
I tried the statement "create type ..." and result in
```
ERROR: pq: syntax error at or near "{"
```
However, I got your point, thanks.
As I sought in postgresql document for definition of _uu_ and _ss_, nothing is found. Could you give me some hint/keyword on that?

@cbandy 
It works! thanks.
I also tried to find the definition of _y(x)_ in document and got nothing, could you give some keyword or hint?

**Comment by cbandy** [comment]
`uu(u)`, `ss`, and `x(y)` are all aliases of the expressions that produced a set of rows.

http://www.postgresql.org/docs/current/static/queries-table-expressions.html

**Comment by mission-liao** [comment]
Thanks, that explained why I can't find them in document.
