### ISSUE TITLE
Prepared Statement doesn't support timestamptz interval syntax

### ISSUE THREAD

**Issue by jbrodriguez** [lib/pq#386]
given a table
`CREATE TABLE item (
	id 	serial PRIMARY KEY,
        name  text,
	added timestamp without time zone
);`

The following sql can't be prepared (but it works from the cli tool)

`SELECT name, added
FROM item
WHERE added::TIMESTAMPTZ AT TIME ZONE INTERVAL $1::INTERVAL > $2`

I've tried a couple variations, but it always chokes on $1.

Any suggestions ?

**Comment by uhoh-itsmaciek** [comment]
@jbrodriguez how does it choke? What variation works through which cli tool (I assume you mean psql)?

**Comment by jbrodriguez** [comment]
hi @uhoh-itsmaciek, it says

> pq: syntax error at or near "$1"

I tried the straight sql from psql (without the prepared statement)

**Comment by uhoh-itsmaciek** [comment]
Try it with the prepared statement in psql. You'll get the same error. I don't think this is a `pq` issue:

```console
maciek=#  CREATE TABLE item ( id serial PRIMARY KEY, name text, added timestamp without time zone );
CREATE TABLE
maciek=# prepare foo(interval, interval) as SELECT name, added FROM item WHERE added::TIMESTAMPTZ AT TIME ZONE INTERVAL $1::INTERVAL > $2;
ERROR:  syntax error at or near "$1"
LINE 1: ...em WHERE added::TIMESTAMPTZ AT TIME ZONE INTERVAL $1::INTERV...
                                                             ^
```

I don't really get what you're trying to do: `AT TIME ZONE` takes a time zone literal string as far as I know, so I'm not sure what you mean by providing the comparison of intervals.

**Comment by jbrodriguez** [comment]
Thanks @uhoh-itsmaciek, you're right, psql gets me the same error.

I was trying to avoid using time zone literals ('America/New_York') and use "hours" ('-05:00').

If you do

`INSERT INTO item (name, added) VALUES ('item4', '2015-08-19 00:30:00');`

then

`select id, added, added::timestamptz at time zone interval '-05:00'::interval as interval, added::timestamptz at time zone 'America/New_York' as literal, added::timestamptz at time zone '-05:00' as hours
from item;`

you get

> id |        added        |      interval       |       literal       |        hours
> ----+---------------------+---------------------+---------------------+---------------------
>  1 | 2015-08-19 00:30:00 | 2015-08-18 19:30:00 | 2015-08-18 20:30:00 | 2015-08-19 05:30:00

the interval and literal columns are fine, but the hours column is wrong.

**Comment by jbrodriguez** [comment]
Well, in the end it has nothing to do with pq, so I'm closing the issue.

Strangely, that select statements actually works with literals such as '-05:00', but have to reverse the -/+ signs to get the correct answer.

In other words,

`select id, added, added::timestamptz at time zone interval '-05:00'::interval as interval, added::timestamptz at time zone 'America/New_York' as literal, added::timestamptz at time zone '+05:00' as hours from item;`

shows 

> id |        added        |      interval       |       literal       |        hours
> ----+---------------------+---------------------+---------------------+---------------------
> 1 | 2015-08-19 00:30:00 | 2015-08-18 19:30:00 | 2015-08-18 20:30:00 | 2015-08-18 19:30:00

**Comment by johto** [comment]
The `typename 'literal'` syntax only works with literals.  The equivalent for with placeholders is $1::typename.

**Comment by cbandy** [comment]
> Strangely, the select statements actually works with literals such as '-05:00', but you have to reverse the -/+ signs to get the correct answer.

This sounds like the difference between POSIX and ISO 8601 zone offsets.

**Comment by johto** [comment]
> I was trying to avoid using time zone literals ('America/New_York') and use "hours" ('-05:00').

I would also like to add that this is almost certainly going to get you into trouble.  New York is -05 from UTC only around every other day.

**Comment by jbrodriguez** [comment]
@cbandy Thanks, I've read something about it now.
@johto Hehe, thanks ... currently NY is -04 due to daylight savings, it was just an example.
