### ISSUE TITLE
Add support for scanning postgresql `uuid` type

### ISSUE THREAD

**Issue by dxvgef** [lib/pq#400]
When the field type is UUID and the recordset is empty, rows.Next () return TRUE

**Comment by johto** [comment]
There's not even nearly enough information to do anything here.  The exact Go version and `pq` git commit you're using, the relevant portions of the code (or, preferably, a self-contained test case), etc..

I tried this and it works just fine (prints "false"):

```go
package main

import (
	_ "github.com/lib/pq"
	"database/sql"
	"fmt"
)

func main() {
	db, err := sql.Open("postgres", "")
	if err != nil {
		panic(err)
	}
	err = db.Ping()
	if err != nil {
		panic(err)
	}
	rows, err := db.Query("SELECT NULL::uuid WHERE FALSE")
	if err != nil {
		panic(err)
	}
	fmt.Println(rows.Next())
}
```
