### ISSUE TITLE
Why we required to set sslmode as default ?

### ISSUE THREAD

**Issue by clongbupt** [lib/pq#403]
https://github.com/lib/pq/blob/master/conn.go#L911

I mean if I was just doing some tests. Force users set sslmode, makes old tests broken and can not share with other programming languages using the same dsn.

Like: 
- [ruby-pg](https://github.com/ged/ruby-pg/blob/master/lib/pg/connection.rb#L14)
- [php-pg](http://php.net/manual/en/function.pg-connect.php)

Thanks.

**Comment by freeformz** [comment]
Other libraries probably just wrap libpq, who's default is "prefer". I assume (since I do not know the specifics), in an attempt to err on the side of security, the default of ["require"](https://github.com/lib/pq/blame/master/conn.go#L899) was chosen.

**Comment by uhoh-itsmaciek** [comment]
Right. Probably at least in part because we don't support prefer (see #175).

**Comment by uhoh-itsmaciek** [comment]
I'm going to close this issue because the reason why we do this is understood. I think if one were to write a `prefer` that's on par with the one in libpq, we'd be happy to change the default.

**Comment by clongbupt** [comment]
Ok.

Thanks for your answer.
