### ISSUE TITLE
Document mapping between postgres (oid) and golang types

### ISSUE THREAD

**Issue by hnsl** [lib/pq#404]
Right now I had to read (uncommented) source code for example to understand that null values when scanned/read will map to a golang nil value. This is not an obvious choice. A design where you had chosen to map the null value to a corresponding NullTime, NullInt64 etc with Valid = false (preserving the oid type information) would have been just as likely from my perspective.

**Comment by johto** [comment]
> A design where you had chosen to map the null value to a corresponding NullTime, NullInt64 etc with Valid = false (preserving the oid type information) would have been just as likely from my perspective.

That's not up to us to decide if we want to conform to the database/sql interface.  See e.g. [driver.Value](https://golang.org/pkg/database/sql/driver/#Value) and [driver.Rows.Next](https://golang.org/pkg/database/sql/driver/#Rows).

**Comment by cbandy** [comment]
The `sql` package also mentions that `nil` represents `NULL`, but not very prominently: https://golang.org/pkg/database/sql/#Scanner

**Comment by hnsl** [comment]
The "database/sql/driver" documentation documents the interface for drivers which is irrelevant for users of "lib/pq" and "database/sql". It doesn't document an interface "end users" actually use.

This is from the (rs *Rows) Scan documentation:
"If an argument has type *interface{}, Scan copies the value provided by the underlying driver without conversion."

The above means "lib/pq" needs to document what Postgres types map to what golang types. This is currently impossible to know without reading the source code of lib/pq which means there is a hole in the documentation. Currently you have to rely on undocumented behaviour if you want to scan data into an interface{} pointer.

**Comment by hnsl** [comment]
I don't seem to have the permission to reopen a ticket so I hereby declare my intent to reopen this ticket if I could since this information would get lost otherwise.

**Comment by johto** [comment]
> The above means "lib/pq" needs to document what Postgres types map to what golang types. This is currently impossible to know without reading the source code of lib/pq which means there is a hole in the documentation. Currently you have to rely on undocumented behaviour if you want to scan data into an interface{} pointer.

Yeah, that's an actual thing we could improve.
