### ISSUE TITLE
Support for range types?

### ISSUE THREAD

**Issue by davisford** [lib/pq#406]
Does lib/pq support range types?  I see the type OID in the source, but what does something like `tstzrange` map to in golang, since it is a tuple of timestamps.  If I make my own struct with a begin and end `time.Time` will that work?

**Comment by cbandy** [comment]
> will that work?

Almost. You will need to implement the `sql.Scanner` interface to parse the [text that the server sends](http://www.postgresql.org/docs/current/static/rangetypes.html#RANGETYPES-IO).

**Comment by davisford** [comment]
Ah, that makes sense.  I see now it maps it to type `[]uint8`, thanks for the quick response.
