### ISSUE TITLE
Scan returning malformed data

### ISSUE THREAD

**Issue by JDWardle** [lib/pq#410]
Been having issues with receiving malformed data when implementing a custom sql.Scanner interface. It seems to be just an issue with this driver, but I've only tested it with the github.com/mattn/go-sqlite3 driver.

I'm not sure if what I'm doing is incorrect, but from what I can tell my implementation of the Scan() method returns everything correctly. Something happens after that method that changes the beginning of the string from the expected $2a$10$ to 1$10$.

I have a relatively contained example of this, you'll need to setup a test database and go get the golang.org/x/crypto/bcrypt and of course this driver:
https://gist.github.com/JDWardle/c09dbb552640e59848d8

**Comment by johto** [comment]
Without looking at this too closely, I'd guess it's the same problem known to plague json.RawMessage, i.e. database/sql thinking it can avoid a copy when it really shouldn't.  If you do e.g. this:

```go
-type EncryptedPassword []byte
+type EncryptedPassword struct { []byte }
```

does it still break?

**Comment by johto** [comment]
> Without looking at this too closely, I'd guess it's the same problem known to plague json.RawMessage, i.e. database/sql thinking it can avoid a copy when it really shouldn't.

Actually, that's not it.  It looks like database/sql assumes that the Scanner makes a copy if one needs to be made.  So it the scanner should look something like this:

```go
    switch t := src.(type) {
    case string:
        *e = EncryptedPassword([]byte(t))
        break
    case []byte:
        cp := make([]byte, len(t))
        copy(cp, t)
        *e = EncryptedPassword(cp)
        break
    default:
        return errors.New("Incompatible type for EncryptedPassword")
    }
```

The reason you're getting garbage results is that the byte array is reused by the driver.  Other drivers might reuse memory in different ways (or not reuse it at all), so the fact that it only breaks with this driver doesn't mean that the problem is in the driver.

**Comment by JDWardle** [comment]
Ah, I see. That does clear things up for me. I guess the documentation does mention it make a copy under certain circumstances. I guess it's just a weird thing I'll have to look out for if I ever implement the Scanner interface for anything else.

Anyway not an issue, just weird database/sql stuff.

Thanks for the help @johto.
