### ISSUE TITLE
missing information in error

### ISSUE THREAD

**Issue by rand99** [lib/pq#412]
Hello,

I get database errors from time to time on uuid fields.
``` 
(pq: invalid input syntax for uuid: "67055b54-aaaa-xxxx-b405-02e96bbfa47e") 
[2015-12-15 13:48:21]  

(pq: invalid input syntax for uuid: "67055b54-aaaa-xxxx-b405-02e96bbfa47e") 
[2015-12-15 13:48:21]  
```

I think to make these errors useful they should include ***tablename.columnname***

best

**Comment by johto** [comment]
I think you'll find that no driver actually provides this information, since the server doesn't send it.  There's nothing we can do here.
