### ISSUE TITLE
How to get INOUT value from  a function (stored procedure)?

### ISSUE THREAD

**Issue by nwaycn** [lib/pq#413]
HI, ALL
     How to get a INOUT parameter value from a function(stored procedure) so as,I want to get the value of v_id :

-----------------------------------------------------------------------------------------------------------------------------
	CREATE OR REPLACE FUNCTION mytest(
	    IN v_name character varying,
	    INOUT v_id bigint)
	  RETURNS bigint AS
	$BODY$  
	    Begin  
	        v_id := 99;
	        select  v_name;
	        return ;
	    END;
	    $BODY$
	  LANGUAGE plpgsql VOLATILE
	  COST 100;

**Comment by nwaycn** [comment]
When I call this func, look this:

func main() {
	dbstring := "user=postgres dbname=nway_voicecode password=nway2013 host=127.0.0.1 port=5432 sslmode=disable"
	db, err := sql.Open("postgres", dbstring)
    db.SetMaxIdleConns(4)
	db.SetMaxOpenConns(10)
	if err != nil {
        panic(err)
    }
    
	
	var mynum int64 = 0
	var s string
	a, err2 :=  db.Query("SELECT mytest($1::TEXT,$2::bigint)","lihao",mynum)
	if err2 != nil {
		fmt.Fprintln(os.Stderr, "Error sending mytest:", err)
		//os.Exit(1)
	}else{
		fmt.Fprintln(os.Stdout, "a is:",a)
		fmt.Fprintln(os.Stdout, "mynum is:",mynum)
	}
	for a.Next() {
        err = a.Scan(&s, &mynum)
        if err != nil {
            panic(err)
        }
       fmt.Fprintln(os.Stdout, "mynum is:",mynum)
    }
	
}
-----------------------------------------------------------------------------------------------
it is panic, so here:

D:\Go>fs_con.exe
Error sending mytest: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x48d4b9]

goroutine 1 [running]:
database/sql.(*Rows).Next(0x0, 0xc082028018)
        c:/go/src/database/sql/sql.go:1633 +0x29
main.main()
        D:/Go/fs_con.go:35 +0x48d

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc0820683c0)
        c:/go/src/database/sql/sql.go:634 +0x4c
created by database/sql.Open
        c:/go/src/database/sql/sql.go:481 +0x33d

**Comment by uhoh-itsmaciek** [comment]
It's a panic because you continue after getting the error instead of calling the `os.Exit` you have commented out. And you're printing `err` instead of `err2`, so you're masking the actual error. Print `err2` instead (or just drop `err2` and reuse `err`, which is more idiomatic Go) and you'll see why it's failing.

**Comment by johto** [comment]
```go
a, err2 :=  db.Query("SELECT mytest($1::TEXT,$2::bigint)","lihao",mynum)
if err2 != nil {
     //os.Exit(1)
} else {
    // [ .. ]
}
for a.Next() {
```

You can't do this.  If Query() returns an error, you can't call Next() on the returned rows.

I think if you print the correct error (`err2` instead of `err`) here:

```go
   fmt.Fprintln(os.Stderr, "Error sending mytest:", err)
```

you'll see what the problem is.
