### ISSUE TITLE
Scan to map[string]interface{} with datatype

### ISSUE THREAD

**Issue by kirubasankars** [lib/pq#415]
I wanted to scan all column to map since I don't know how many column exists on my query. Dynamic generated query.

I can able get values as sql.Rawbytes, how to get datatype information of each column

**Comment by uhoh-itsmaciek** [comment]
You can get the number of columns (and their names) via `sql.Rows.Columns()`, but the `database/sql` interface doesn't really support dealing with types dynamically. You can kind of hack around it a bit by implementing your own [`sql.Scanner`](https://golang.org/pkg/database/sql/#Scanner) and scanning differently based on the runtime type of the `src` argument, but that's about it. I don't think we can work around this in a reasonable manner, but let us know if you have concrete suggestions.

**Comment by cbandy** [comment]
This is discussed, though somewhat indirectly, in https://github.com/golang/go/issues/5606.

**Comment by kirubasankars** [comment]
I used my own Scanner implementation to scan values. I found "character varying" column comes as []byte not string. is it a bug ?

**Comment by benedictjohannes** [comment]
I used the function in this [gist](https://gist.github.com/heyimalex/075bb442af0ecbf3e5f561336101e4f7) and it works great.
