### ISSUE TITLE
QueryRow() returns "unsupported driver" Error on instead of sql.ErrNoRows

### ISSUE THREAD

**Issue by mankyd** [lib/pq#421]
I am getting an unexpected result where I am simply expecting a no-rows err. Basic example:

    var name, email, password string
    id := 2

    row := service.db.QueryRow(
        `SELECT name, email, password
         FROM users
         WHERE id=$1`, id)
    err = row.Scan(&name, &email, &password)
    if err != nil {
      log.Println(err)
      log.Println(err == sql.ErrNoRows)
      return
    }

I see the following get logged when the id does not exist in the database:

> 2016/01/23 11:32:34 sql: Scan error on column index 0: unsupported driver -> Scan pair: \<nil\> -> *string
> 2016/01/23 11:32:34 false

When the id does exist, everything works as expected.

**Comment by johto** [comment]
The error suggests that the id exists, but "name" is NULL.  Are you absolutely sure the id doesn't exist?

**Comment by mankyd** [comment]
Crap, you're completely right. I was looking at the wrong column in my db.
