### ISSUE TITLE
require tls mode

### ISSUE THREAD

**Issue by richo** [lib/pq#424]
in `ssl`, it says the default is `"require"`, but inspection of the code reveals that `"require"` doesn't verify peer. Is this expected behaviour, or am I reading this wrong?

EDIT: Forgot to link to source: https://github.com/lib/pq/blob/master/conn.go#L972-L1013

**Comment by uhoh-itsmaciek** [comment]
The Postgres sslmode parameter behavior is described [here](http://www.postgresql.org/docs/current/static/libpq-ssl.html). I think we're in line with that, no?

**Comment by cbandy** [comment]
> The Postgres sslmode parameter behavior is described [here](http://www.postgresql.org/docs/current/static/libpq-ssl.html). I think we're in line with that, no?

There is a note on that page that `require` is the same as `verify-ca` _when there is a root certificate present_, though users should not rely on that behavior.

The short explanation in the [connection parameters docs](http://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNECT-SSLMODE) says the same thing, though maybe not as clearly.

**Comment by uhoh-itsmaciek** [comment]
Fair point. This could be made more conformant.
