### ISSUE TITLE
Support parameter markers on `COMMENT` queries.

### ISSUE THREAD

**Issue by homme** [lib/pq#426]
Currently the following produces an error:
```
err = tx.Exec("COMMENT ON TABLE mytable IS $1", "my comment")
```

`err` is a `*pq.Error` with the following fields set:

```
code=42601 
message=syntax error at or near "$1" 
file=scan.l 
line=1082 
position=72 
routine=scanner_yyerror 
severity=ERROR
```

An alternative solution would be to export a `pq.EscapeString(input string) (output string)` type function.

**Comment by uhoh-itsmaciek** [comment]
Our parameter support is based on what Postgres itself supports, and I don't believe `COMMENT` queries are parameterizable. Postgres has something like the `EscapeString` you propose via [quote_literal](https://github.com/postgres/postgres/blob/ee943004466418595363d567f18c053bae407792/src/backend/utils/adt/quote.c#L77); adding that could be useful.

**Comment by uhoh-itsmaciek** [comment]
To clarify, `quote_literal` is the internal Postgres function; it is exposed in the libpq client library via http://www.postgresql.org/docs/9.1/static/libpq-exec.html#LIBPQ-EXEC-ESCAPE-STRING

**Comment by homme** [comment]
If `COMMENT` queries can't be parameterised then yes, an escaping/quoting function would be great to replace the hack I currently have.  Maybe `pq.QuoteString` to complement `pq.QuoteIdentifier`?  I'm not sure how the difference between the `PQescapeStringConn` and `PQescapeString` C functions in the above link would apply to the Go package?

**Comment by johto** [comment]
> If COMMENT queries can't be parameterised then yes, an escaping/quoting function would be great to replace the hack I currently have. Maybe pq.QuoteString to complement pq.QuoteIdentifier?

Please don't deviate from the standard terminology.  Call it pq.QuoteLiteral.

> I'm not sure how the difference between the PQescapeStringConn and PQescapeString C functions in the above link would apply to the Go package?

You should be looking at PQescapeLiteral, specifically this part:

```C
    /*
     * If we are escaping a literal that contains backslashes, we use the
     * escape string syntax so that the result is correct under either value
     * of standard_conforming_strings.  We also emit a leading space in this
     * case, to guard against the possibility that the result might be
     * interpolated immediately following an identifier.
     */
    if (!as_ident && num_backslashes > 0)
    {
        *rp++ = ' ';
        *rp++ = 'E';
    }
```

You are fortunately allowed to assume that client_encoding is set to UTF-8.

**Comment by homme** [comment]
@johto Thanks for the information.
> You are fortunately allowed to assume that client_encoding is set to UTF-8

Fortunate indeed!  The simple hack I mentioned is as follows and makes that assumption, although doesn't support backslashes.
```go
// escapeString escapes and quotes a string literal for inclusion in a
// PostgreSQL query.
func escapeString(input string) string {
	return fmt.Sprintf("E'%s'", strings.Replace(input, "'", "\\'", -1))
}
```
