### ISSUE TITLE
Can I receive the data from OUT cursor?

### ISSUE THREAD

**Issue by maliutin** [lib/pq#434]
Hi

I have to call following procedure.

```
PROCEDURE get_active_its_rules(OUT p_result refcursor) IS
BEGIN
    OPEN p_result FOR
    SELECT *
    FROM its_rule
    WHERE SYSDATE BETWEEN effective_date AND expiration_date
        AND deleted_flag=0;
END;
```

Can I receive the data from `p_result` cursor using pq functionlity? And how can I do it?
Please, write an example.

**Comment by uhoh-itsmaciek** [comment]
Isn't that PL/SQL? pq is a driver for Postgres, not Oracle.

**Comment by maliutin** [comment]
Hi

Yes. Now we are using Postgres. And this procedure is declared in Postgres server. But it is not mine.

**Comment by maliutin** [comment]
In theory. Can we retrieve data from the cursor?

**Comment by johto** [comment]
> Yes. Now we are using Postgres. And this procedure is declared in Postgres server.

Certainly this one isn't, since it doesn't even resemble anything postgres would accept.

> In theory. Can we retrieve data from the cursor?

Sure: http://www.postgresql.org/docs/current/static/sql-fetch.html  You'll have to call the function first to get the name of the cursor, and then FETCH from it.

But using cursors like this isn't idiomatic postgres usage at all.  Why not simply return the results directly from the function?  Or use a view, since the function takes no parameters in the first place?

**Comment by maliutin** [comment]
@johto Thanks for answer.

But I asked about pq functionality. For example, in [ora](https://github.com/rana/ora) for Oracle we can use the special  type [Rset](https://github.com/rana/ora/blob/master/rset.go#L67) which can work with cursor:
```
...
rset := &ora.Rset{}

stmt, _ := ses.Prep("CALL get_active_its_rules(:1)")
stmt.Exe(rset)

var row []interface{} = rset.NextRow()
...

``` 

Does pq have same functionality to work with cursor?

**Comment by johto** [comment]
> Does pq have same functionality to work with the cursor?

No.

I've also described how to do this, and it's practically identical to your "ora" example:

```Go
var cursor string
_ = tx.QueryRow("SELECT foof()").Scan(&cursor)
rows, _ := tx.Query("FETCH ALL " + pq.QuoteIdentifier(cursor))
for rows.Next() {
    /* .. */
}
```

**Comment by maliutin** [comment]
@johto Thanks for answer.

It is working scenario.
