### ISSUE TITLE
Can't figure out how to INSERT "Range Types"

### ISSUE THREAD

**Issue by mikegleasonjr** [lib/pq#439]
As per:
http://www.postgresql.org/docs/9.4/static/rangetypes.html. I am using the `tsrange` type.

If I'm doing...

```
INSERT INTO x(a) VALUES('[$1, $2)')
```

I am getting `pq: invalid input syntax for type timestamp: "$1"`. Clearly the parameter `$1` is not getting evaluated and is passed as is to the engine.

How can I get this kind of query to work?

**Comment by mikegleasonjr** [comment]
I found a workaround by building the query myself. I don't have any fear of SQL injections since I have the control on the input but still, I find it hacky:

```
fmt.Sprintf("INSERT INTO x(a) VALUES('[%s, %s)')", d1.Format(time.RFC3339), d2.Format(time.RFC3339)
```

I won't close until I hear the opinion of someone with more experience with the driver...

**Comment by mikegleasonjr** [comment]
As per #406 I will implement the `Valuer` interface:
https://golang.org/pkg/database/sql/driver/#Valuer

**Comment by johto** [comment]
Just use the constructor:

```SQL
INSERT INTO x(a) VALUES (tstzrange($1, $2, '[)'));
```

**Comment by mikegleasonjr** [comment]
@johto Thanks man I took a walk before starting working on it so you saved me some time :)
