### ISSUE TITLE
Conversion of some types.

### ISSUE THREAD

**Issue by rvlander** [lib/pq#445]
Where can we see a table that show matching between PostgreSQL types and Go types?

Particularly, the following types:
* oid
* pg_lsn
* xid

**Comment by johto** [comment]
Nobody's written such a piece of documentation yet.  There's an open issue #404 to do that, but nothing's happened there.

There's no special handling for pg_lsn, but you can scan its text representation into a `string` or a `[]byte` values.  Both `oid`s and `xid` are essentially uint32, and scanning them into one should work.
