### ISSUE TITLE
Postgres memory leak if prepared statement is not closed

### ISSUE THREAD

**Issue by kushtrimjunuzi** [lib/pq#446]
Postgres db Server is crashed with error about memory not available.
if stm, err:= db.Prepare('something') is not stm.Close()

**Comment by uhoh-itsmaciek** [comment]
From [the database/sql docs](https://godoc.org/database/sql#DB.Prepare):

>Prepare creates a prepared statement for later queries or executions. Multiple queries or executions may be run concurrently from the returned statement. **The caller must call the statement's Close method when the statement is no longer needed**. 

(emphasis added)

So yes, you need to close prepared statements once you're done with them. That's how database/sql (and just about any database API) works.

I'm closing this as not-a-bug but please reopen with more details if I've misunderstood your report.
