### ISSUE TITLE
Queries made by pq wont show in pg_stat_activity

### ISSUE THREAD

**Issue by caarlos0** [lib/pq#448]
Seems like queries made with `pq` driver show as empty in `pg_stat_activity`.

Any reason for that? Any ways to fix it?

**Comment by johto** [comment]
There's no way for the driver to affect that.  Are you querying `pg_stat_activity` as a superuser?

**Comment by caarlos0** [comment]
cc/ @cleitondomazak

**Comment by cleitondomazak** [comment]
Yes, I'm querying with superuser and the user is the database owner in PostgreSQL 9.4.1. Only in old version of the PostgreSQL(<8.*) you could change a parameter stats_command_string to not show the query values.

**Comment by marcio-mutti** [comment]
Sorry if I say newbie stuff but, did you set up the application_name
connection parameter?

Em Qui, 17 de mar de 2016 16:11, Cleiton Domazak <notifications@github.com>
escreveu:

**Comment by caarlos0** [comment]
@marcio-mutti I think not, I'm doing:

```go
db, err := sqlx.Open("postgres", url)
	if err != nil {
		log.Fatal(err)
	}
	if err := db.Ping(); err != nil {
		log.Fatal(err)
	}
```

**Comment by johto** [comment]
There's no evidence suggestive of a problem in `pq` here, so closing this one.
