### ISSUE TITLE
ReadOnly mode support

### ISSUE THREAD

**Issue by garrypolley** [lib/pq#451]
I think it would be great to support the read only mode for the connection string to postgres. 

I know I can create a readonly user, but it'd be nice if I could use the read only support in the connection.

**Comment by johto** [comment]
You can set `default_transaction_readonly` in the connection string.

**Comment by garrypolley** [comment]
Awesome, I did not know I could pass that setting directly.  Thanks!

**Comment by garrypolley** [comment]
That did the trick `default_transaction_read_only=true`. Thanks for the help.
