### ISSUE TITLE
How to craft an IN condition?

### ISSUE THREAD

**Issue by didip** [lib/pq#457]
I couldn't find instructions in godocs on how to do it.

This is the query that i tried:
```go
hosts := []*HostRow{}

query := "SELECT * from hosts where hostname IN ($1)"
// I tried this as well: "SELECT * from hosts where hostname IN $1"

db.Select(&hosts, query, []string{"example.com"})
```

**Comment by uhoh-itsmaciek** [comment]
Unfortunately, Postgres does not support parameters for `IN` lists. You can either generate your query like

```go
	params := []interface{}{"example.com", "foo.example.com"}
	query := "SELECT * from hosts where hostname IN ("
	for i, _ := range params {
		query += fmt.Sprintf("$%d", i + 1)
		if i < len(params) - 1 {
			query += ","
		}
	}
	query += ")"
```

Or use an array parameter and change your query to be `SELECT * FROM hosts WHERE hostname = ANY $1`.

**Comment by didip** [comment]
Thanks @uhoh-itsmaciek ! I will give these a try.
