### ISSUE TITLE
Array type support, like that jackx/pgx

### ISSUE THREAD

**Issue by dxvgef** [lib/pq#464]
jackc/pgx support query postgresql array type and json/jsonb type, hope lib/pq can support.
I really need this feature, thank you!

**Comment by freeformz** [comment]
Dupe of #327 (which may be a dupe of #49) ?

**Comment by uhoh-itsmaciek** [comment]
Agreed, although if pgx already supports arrays, it may be worth looking at their interface.

**Comment by freeformz** [comment]
@uhoh-itsmaciek :+1: I was looking at those issues on Monday and trying to make heads or tails of the various proposals and their status.

**Comment by johto** [comment]
json and jsonb have always worked.  You just get the value back as a string and feed that to `encoding/json`.  I just merged array support from #466.
