### ISSUE TITLE
Query breaks ORDER BY when parametrized

### ISSUE THREAD

**Issue by jforcada** [lib/pq#465]
When doing:
`queryString := "SELECT * FROM city ORDER BY id DESC OFFSET 16 ROWS FETCH NEXT 8 ROWS ONLY;"
rows, err := db.Query(queryString)`

The result is different than:
`queryString := "SELECT * FROM city ORDER BY $1 DESC OFFSET $2 ROWS FETCH NEXT 8 ROWS ONLY;"
rows, err := db.Query(queryString, "id", 16)`

It happens to ignore the `DESC` part of the query in the second version.

**Comment by jforcada** [comment]
In the mean time, is there any way I can escape the parameters myself easily and then construct the query with `fmt.Sprintf`?

**Comment by johto** [comment]
> The result is different than:
> queryString := "SELECT * FROM city ORDER BY $1 DESC OFFSET $2 ROWS FETCH NEXT 8 ROWS ONLY;" rows, err := db.Query(queryString, "id", 16)
> 
> It happens to ignore the DESC part of the query in the second version.

No, the ORDER BY is working just fine.  It's just completely nonsensical.  You're ordering by the unknown type constant 'id'.

Identifiers (such as table and column names) can not be parameterized.

**Comment by johto** [comment]
> In the mean time, is there any way I can escape the parameters myself easily and then construct the query with fmt.Sprintf?

Sure, but there's nothing in `pq` to help you do that.

**Comment by hochhaus** [comment]
Wouldn't [QuoteIdentifier](https://godoc.org/github.com/lib/pq#QuoteIdentifier) help?

**Comment by jforcada** [comment]
Thanks, just saw the mistake. Closing.
