### ISSUE TITLE
table name like a param

### ISSUE THREAD

**Issue by EagleMoor** [lib/pq#467]
Hi, i want set a table name like a params.

```go
var count int
row := db.QueryRow("SELECT COUNT(*) FROM $1", "public.table_name")
err := row.Scan(&count)
log.Println(count, err)
```

return error

`0 pq: syntax error at or near "$1"`

**Comment by johto** [comment]
That's not possible.  You can't parameterize identifiers.

You'd have to interpolate the table name into the query string.  You can use [pq.QuoteIdentifier](https://godoc.org/github.com/lib/pq#QuoteIdentifier) to make sure the table name doesn't cause any issues.  You'd have to quote the schema and the table names separately, though.

**Comment by freeformz** [comment]
Should this be added to a FAQ? I know I've seen this or something similar come up a few times.

		_____________________________
