### ISSUE TITLE
~/.pgpass

### ISSUE THREAD

**Issue by ghost** [lib/pq#47]
Support for ~/.pgpass files would be really useful (description: https://wiki.postgresql.org/wiki/Pgpass)

**Comment by dugwood** [comment]
For future users who come accross this bug, please note that it's implemented using `PGPASSFILE`:
https://github.com/lib/pq/blob/90697d60dd844d5ef6ff15135d0203f65d2f53b8/conn.go#L166

So you need to specify an environment variable `PGPASSFILE` which gives the full path to the `.pgpass` file.
