### ISSUE TITLE
supports setting schema in search-path during connection

### ISSUE THREAD

**Issue by CzechJiri** [lib/pq#471]
since 9.4 postgres supports setting schema in search-path via `currentSchema` URL connection parameter, it would be nice if this could be supported

https://jdbc.postgresql.org/documentation/head/connect.html

e.g.
```
postgresql://localhost:5432/mydatabase?currentSchema=myschema
```

**Comment by johto** [comment]
> since 9.4 postgres supports setting schema in search-path via currentSchema URL connection parameter, it would be nice if this could be supported

Pretty sure this is a JDBC-only setting.  `pq` already supports setting search_path by simply setting search_path directly.

**Comment by CzechJiri** [comment]
yes, this is JDBC setting, I was asking whether similar setting could be supported in pq during connection

**Comment by uhoh-itsmaciek** [comment]
You can use the `search_path` parameter in the connecting string--does that not do what you need?

**Comment by CzechJiri** [comment]
I know you can set it that way, having it as part of connection string and mimicking to some degree jdbc connection string makes it a bit more standardized and requires one less parameter to worry about in the configs or/and login screens

**Comment by uhoh-itsmaciek** [comment]
Again, you can use `search_path` in the connection string: `postgres:///mydb?search_path=foo` works just fine. Beyond that, I don't think it makes sense to try to pursue jdbc compatibility by supporting different names for the same thing, since we could only manage a superficial compatibility at best.
