### ISSUE TITLE
How can count number of rows in query?

### ISSUE THREAD

**Issue by thanhngvpt** [lib/pq#472]
Hello Sir.
Your job so great, but i have a question how can i count number of rows in query. as below example.

`rows, err := db.Query("SELECT id, created, state, price FROM orders")`

how can i count rows? 
Many thanks.

**Comment by ajvb** [comment]
@thanhngvpt I don't think you can do this with a simple method call through Go's `database/sql` interface, which is what you are using when you use `lib/pq`. Your best bet is to iterate through `rows` using the `.Next()` func ([here](https://golang.org/pkg/database/sql/#Rows.Next).

**Comment by uhoh-itsmaciek** [comment]
Hi, @ajvb is right here--there's no built-in support for this: you have to count the rows yourself.

**Comment by thanhngvpt** [comment]
Now i use a count variable when iterate through rows using row.Next() to count. But i think sometime no need to iterate through all rows (does it need much time to process?). there is a solution is return count from sql statement.
Many thanks.

**Comment by ajvb** [comment]
@thanhngvpt Using SQL you can do:

```go
row := db.QueryRow("SELECT count(id) FROM orders")
```

**Comment by thanhngvpt** [comment]
@ajvb yes, current i am doing that, but with that way i must query twice to get number of rows in query and a query to get data.

**Comment by johto** [comment]
You can also use a window function:

```SQL
SELECT foo.f1, foo.f2, count(*) OVER() FROM foo
```

This way you only have to peek at the first row to get the total number of rows in the result set.

**Comment by xiaopeng-han** [comment]
it is not right!
