### ISSUE TITLE
Support Transactions with different isolation levels

### ISSUE THREAD

**Issue by jtaekema** [lib/pq#476]
Postgres supports several isolation levels: see https://www.postgresql.org/docs/current/static/transaction-iso.html
- Read Uncommitted (internally the same as Read Committed)
- Read Committed (default)
- Repeatable Read
- Serializable

Some types of systems need the guarantees provided by the more strict isolation levels.

To get around this support I have been running a simple command to upgrade the transaction, but it would be nice if there was an easy way to start the transaction that way.

Like:

```
conn.BeginTransaction(IsolationLevel.RepeatableRead)
```

There are other options that would be useful for performance tuning, such as  `READ WRITE`, `READ ONLY`, and `[ NOT ] DEFERRABLE`.

**Comment by johto** [comment]
> To get around this support I have been running a simple command to upgrade the transaction, but it would be nice if there was an easy way to start the transaction that way.

Unfortunately I don't see how this could possibly work given that we have to work with the interface database/sql provides.

**Comment by uhoh-itsmaciek** [comment]
I agree--I think the limited `database/sql` API ties our hands here. Do you have a concrete suggestion as to how to approach this?

**Comment by itsjamie** [comment]
This issue should be able to be fixed with the introduction of IsolationLevels to database/sql with 1.8 assuming enough implementation happens with #531 for it not to be pulled.

**Comment by ThomasHabets** [comment]
This is in 1.8 and lack of it is preventing me from cleaning up code manually setting isolation level inside every transaction.

**Comment by mattyw** [comment]
Has this not been fixed now that https://github.com/lib/pq/commit/ed1a26d9e1fd4eb1cc491e6d688467f4e81a413c has landed?

**Comment by ThomasHabets** [comment]
I can confirm that it works perfectly for me.
