### ISSUE TITLE
Drop Go 1.4 support

### ISSUE THREAD

**Issue by freeformz** [lib/pq#482]
goimports, a tool we use in our .travis.yml setup no longer supports go1.4 because it imports the `runtime/trace` package w/o a build tag guard.

See also: https://github.com/golang/go/issues/16661

**Comment by freeformz** [comment]
https://github.com/golang/go/issues/16434

**Comment by cbandy** [comment]
See also #479

**Comment by freeformz** [comment]
FWIW: I'd rather drop go1.4 support. It's already dropped upstream. go1.5 support is going to be dropped soon (probably next week).

**Comment by johto** [comment]
There's really nothing to gain from dropping the support, so I don't see what the problem is.  If goimports doesn't support 1.4, we don't have to use it.

**Comment by uhoh-itsmaciek** [comment]
There's probably not much to gain, but on the other hand supporting Go versions long since unsupported upstream seems quixotic...

**Comment by freeformz** [comment]
I'd like to continue using goimports as a test hook, although TBH it doesn't need to run for each version of Go. Not sure that's possible though.

The solution in #479 could theoretically lead to false positives if goimports fails to compile for all versions of go. That's unlikely though.

wrt go1.4: The go team itself doesn't support it anymore. And go1.5 support is also being dropped once go1.7 comes out (next weekish). I'd say drop go1.4 now and once 1.8 comes out we drop 1.5, etc. Basically whatever the go team supports +1 version.

**Comment by johto** [comment]
> There's probably not much to gain, but on the other hand supporting Go versions long since unsupported upstream seems quixotic...

Sure.  But there's more work in dropping support than not dropping it, at least currently.  If there was something that 1.5 had but 1.4 didn't I wouldn't object, but currently there isn't anything.
