### ISSUE TITLE
Weird "pq: deadlock detected" error

### ISSUE THREAD

**Issue by azr** [lib/pq#486]
Hello there,

I have a view count that is backed by psql; now I probably should do it another way but; when I stress test it, from time to time I get this`pq: deadlock detected` error. Call is a `DB.Exec()`
When this happened I had 7 goroutines panicking at the same line `DB.Exec()`.

Is there a way to have more output/debug on this ?

I'd be glad to help :)

The psql db is a heroku hobby-dev with a limit of 20 simultaneous connections.

**Comment by johto** [comment]
> I have a view count that is backed by psql

I don't know what that means.

> Is there a way to have more output/debug on this ?

The way to debug deadlock errors is to look at the error message in the server log (it'll show the last statements executed by each transaction involved) and then analyze everything done in those transactions carefully.

**Comment by azr** [comment]
Hey johto,
> I have a view count that is backed by psql 
means every time a user views something, I increment a dumb counter.

There is no transaction, its a `DB.Exec()`

**Comment by johto** [comment]
> There is no transaction, its a DB.Exec()

You can't execute SQL statements in postgres without being in a transaction.  If you didn't explicitly start one and you're not already in a transaction, postgres will start a transaction, execute your SQL statement and then commit (or roll back) that transaction.

> Edit: do you mean psql server logs or mine ?

When I said "server logs", I meant postgres server logs.

**Comment by azr** [comment]
Ah okay, thanks for the explanations johto, on heroku `Logs are not available on hobby-tier databases.` :'( which means I'll have to find this in production logs...

But reading what you just said my guess is that because the increment is done on the same ROW (by id) , that row might be the deadlocking piece, could it be ?

In the meantime I'll try to dig for that error in the logs.

cheers

**Comment by azr** [comment]
Yup, guessing is not good.

Okay, thanks for all your answers and time.
I think I'll figure it out from here :)

BTW. I think you should document somewhere in the code that the `pq: deadlock detected` can only happen in psql side. Just for noobs like me; at some point, because the error was prepended with `pq` I thought it was a deadlock problem inside the go code.

Cheers o/

**Comment by azr** [comment]
Okay I got the error !!

```
postgres_1  | ERROR:  deadlock detected
postgres_1  | DETAIL:  Process 16468 waits for ShareLock on transaction 195059; blocked by process 16475.
postgres_1  |  	Process 16475 waits for ShareLock on transaction 195058; blocked by process 16468.
postgres_1  |  	Process 16468: UPDATE users SET view_count = view_count + 1 WHERE id IN (8,10,12,11,2,15,5,4,9,17,16,6,14,3,7,18,20,19)
postgres_1  |  	Process 16475: UPDATE users SET view_count = view_count + 1 WHERE id IN (9,12,11,14,15,16,8,10,2,6,4,5,3,7,18,20,17,19)
postgres_1  | HINT:  See server log for query details.
postgres_1  | CONTEXT:  while locking tuple (0,17) in relation "users"
postgres_1  | STATEMENT:  UPDATE users SET view_count = view_count + 1 WHERE id IN (8,10,12,11,2,15,5,4,9,17,16,6,14,3,7,18,20,19)
```

Given that you said everything would be locked before an update, that's really weird !
I would be thinking they could be done sequentially.

How would you fix that ? 
Do I need to protect my update request with a BEGIN/END statement?

**Comment by kshvakov** [comment]
D'oh! It is a "classic deadlock" . You take locks in a different order, use update with order by pk (sort 'in' parameters) and read this doc https://www.postgresql.org/docs/current/static/explicit-locking.html

**Comment by azr** [comment]
hehe will try them all :D **thanks** a lot for you help. You pbbly can close that issue btw :)
Sorry I asked those noob questions here !

cheers

**Comment by kshvakov** [comment]
@azr You can use explicitly lock for rows, see this: 
http://dba.stackexchange.com/questions/68388/optimizing-concurrent-updates-in-postgres

Explanation: http://big-elephants.com/2013-09/exploring-query-locks-in-postgres/

**Comment by azr** [comment]
Yay, just sorting the ids by increasing number did it :).
Thanks again for your helps guys !!!
