### ISSUE TITLE
Reusing connection to db vs. reopening connection to db each query

### ISSUE THREAD

**Issue by serv** [lib/pq#487]
Is there a good way to retain the connection to the db once you open a connection?

```
func randomDBQuery() {
  ...
  db, err := sql.Open("postgres", "user=postgres dbname=go_pg_prac_dev sslmode=disable")
  ...
}
```

Let's say I have a function like that above. I am assuming when the function gets executed, the local variable in `randomDBQuery` gets garbage collected away. So `randomDBQuery` is gone.
Does `pq` package somehow support retaining this connection to the DB?

I guess I'll also ask this, is it worth keeping the connection open? Would it be too costly to open connection to postgres each time I want to query it?

Thanks for the help.

**Comment by johto** [comment]
> Does pq package somehow support retaining this connection to the DB?

No.  sql.Open() in the caller and pass the handle to randomDBQuery().  Or create a struct and make randomDBQuery() one of its methods.

> I guess I'll also ask this, is it worth keeping the connection open? Would it be too costly to open connection to postgres each time I want to query it?

Whether it's "too costly" or not depends on numerous factors I could possibly have no idea about.  But in my opinion it would be really silly to write a program that doesn't keep an *sql.DB handle around for more than one query.

**Comment by cbandy** [comment]
> Is there a good way to retain the connection to the db once you open a connection?

I'd also like to point out that `*sql.DB` is not _a connection_; it's a [pool](https://golang.org/pkg/database/sql/#DB) of connections.

**Comment by uhoh-itsmaciek** [comment]
@serv if you really want to keep a connection, or rather connection pool as @cbandy pointed out, open without having to pass the reference around, you can declare a package-global `*sql.DB` and connect in your package's `init`. This is okay for small, simple programs but I would avoid that in anything reasonably complex.

**Comment by minervadata** [comment]
@uhoh-itsmaciek why would you avoid this solution in big complex program? we have been using it for a while for an ERP and works well (concurrent connections less than 8 at most), but I was wondering if what we been doing is the right way for an enterprise applications.

**Comment by uhoh-itsmaciek** [comment]
Well, for one, testing that can be awkward. But if it works for you, great.
