### ISSUE TITLE
Documentation: TLS SNI

### ISSUE THREAD

**Issue by Superdominik** [lib/pq#488]
It would be great if the readme would reflect whether pq supports TLS SNI. 

I couldn't find any info about it. It's a very important piece of information for everyone who runs his PostgreSQL server behind a reverse proxy and wants to use SSL.

Does it support TLS SNI?

**Comment by johto** [comment]
Like most Go programs, it uses [crypto/tls](https://golang.org/pkg/crypto/tls/) underneath, which supports SNI.

I don't think this needs any documentation.  Anyone who cares about this can just take a look at the source code or test it with a 10-line program.

**Comment by johto** [comment]
Well, just as I hit send there I just realized that it's not actually completely true.  The postgres protocol has its own plaintext handshake before the TLS connection is established, which renders SNI useless unless the proxy/whatever you're interested in knows how to read that handshake.

**Comment by cbandy** [comment]
We only set `tls.Config.ServerName` when `sslmode=verify-full`. I'll check what `libpq` does later today.

**Comment by cbandy** [comment]
`libpq` never calls `SSL_set_tlsext_host_name` that I can see. A suggestion to add it was dismissed some time ago: https://www.postgresql.org/message-id/20131129201943.GA28300@gmail.com

If you have a compelling case for hosting multiple instances on a single port, we can reopen the discussion.

**Comment by sudeeptoroy** [comment]
If the server is behind a reverse proxy which can proxy/route on SNI, in such scenario we  will require pq to support SNI

**Comment by petr4** [comment]
Do you have any progress on it? We use many postgres instances on K8s and want to route traffic over ingress.

**Comment by cbandy** [comment]
> We use many postgres instances on K8s and want to route traffic over ingress.

Kubernetes Ingress does not natively support TCP applications or services. What controller are you using that can?

**Comment by sudeeptoroy** [comment]
Contour ingress support TCP application.
https://projectcontour.io/guides/tls/

**Comment by cbandy** [comment]
> Contour supports HTTPS (TLS/SSL) ingress…

I see a lot about HTTP and HTTPS at https://projectcontour.io/ and nothing about TCP routing or ingress.

**Comment by sudeeptoroy** [comment]
> > Contour supports HTTPS (TLS/SSL) ingress…
> 
> I see a lot about HTTP and HTTPS at https://projectcontour.io/ and nothing about TCP routing or ingress.

Coutour does support TCP proxying.  I have used it extensively in my projects. More information here.   
 
https://projectcontour.io/docs/v1.18.1/config/tls-termination/#tls-session-proxying
https://projectcontour.io/docs/v1.18.1/config/tls-termination/#tls-session-passthrough
