### ISSUE TITLE
Permission check on postgresql.key doesn't work on Windows

### ISSUE THREAD

**Issue by Superdominik** [lib/pq#489]
I've run into a problem with client-side certificates on Windows. Even after changing the permissions on the key-file, I get 

> pq: Private key file has group or world access. Permissions should be u=rw (0600) or less.

I've investigated the problem a bit and found that [here](https://github.com/lib/pq/blob/55196ec83d60d789e27b2627549bf00974a70084/conn.go#L1099) in the code it checks for the `Mode()`of the file via the `os` package. This seems to return `-rw-rw-rw-` on Windows though, no matter how I change the permissions.

Is this a `pq` problem or maybe an upstream problem of the `os` package?

**Comment by cbandy** [comment]
It looks like the `os` package is doing it: https://github.com/golang/go/blob/go1.7/src/os/types_windows.go#L31-L50

We should probably look to how `libpq` behaves on Windows.

**Comment by cbandy** [comment]
It looks to me like `libpq` completely skips this check on Windows: https://github.com/postgres/postgres/blob/REL9_5_4/src/interfaces/libpq/fe-secure-openssl.c#L1192-L1200

**Comment by freeformz** [comment]
It looks like it may work properly if the file is set to "Read Only". @Superdominik you said you changed the permissions, but I'm not sure if that's what you tried.

**Comment by Superdominik** [comment]
@freeformz I've tried setting it to read-only. Go then thinks the file has `-r--r--r--` permissions. Which still doesn't allow it to be used with pq.
I've additionally removed inheritance and all principals from the file. Then added just the local user back and only gave read access. Changing anything in the Windows security model doesn't have any effect on the permissions read by `Mode()` though. So I don't think it's possible to work around this problem.

**Comment by freeformz** [comment]
Ahhh Yeah, `0444` is > `0600`. :-( We should maybe skip the check on windows too then.
