### ISSUE TITLE
cannot convert <nil> to Int64Array

### ISSUE THREAD

**Issue by romesh-mccullough** [lib/pq#490]
Hello!  I am hoping that someone here may be able to provide some guidance on how to properly handle null values for array columns using the new array support. 

Here's a trivial example:

```
var a []int64

row := d.conn.QueryRow("SELECT NULL as a")
err := row.Scan(pq.Array(&a))
if err != nil {
	log.Printf("%v", err)
}
```
Which returns the following error:
`sql: Scan error on column index 0: pq: cannot convert <nil> to Int64Array`

Does anyone have a strategy for handling this?  For now I am just doing `COALESCE(column, '{}')` in my queries that could possibly return a null value for an array column, but I want to make sure I'm not missing something.

Thanks!

**Comment by cbandy** [comment]
The convention for this is to build a `Null` type, for example, [`NullInt64`](https://golang.org/pkg/database/sql/#NullInt64). In this case, you can do something like

```go
type NullInt64Array struct {
  Int64s []int64
  Valid  bool
}

func (n *NullInt64Array) Scan(value interface{}) error {
  if value == nil {
    n.Int64s, n.Valid = nil, false
    return nil
  }
  n.Valid = true
  return pq.Array(&n.Int64s).Scan(value)
}
```
```go
var a NullInt64Array
err := db.QueryRow(`SELECT NULL`).Scan(&a)
// ...
if a.Valid {
  // use a.Int64s
} else {
  // NULL value
}
```

**Comment by romesh-mccullough** [comment]
Perfect!  That's exactly what I was looking for.  Thanks so much for the example and quick response!
