### ISSUE TITLE
Cannot make a query containing the ILIKE matching pattern

### ISSUE THREAD

**Issue by mhdaouas** [lib/pq#495]
I have a query containing the string "WHERE param_one || ' ' || param_two ILIKE ('%$1%')". When I pass it to `db.Query(queryString, filter)` (with `filter` replacing `$1`), I get the following error:
`pq: got 1 parameters but the statement requires 0`
I tried also replacing `$1` with `?` but it didn't work too.
How to deal with this?

**Comment by jmscott** [comment]
i believe $1 is not replaced inside a string.  try changing

     ILIKE ('%$1%')

to something like

     ILIKE ('%' || $1 || '%')

-j

**Comment by mhdaouas** [comment]
Thank you very much, it resolved my problem :)
