### ISSUE TITLE
Bad insert not returning error

### ISSUE THREAD

**Issue by beppeben** [lib/pq#502]
I'm executing a bad insert (violating a constraint) followed by a good insert in an sql transaction. My issue is that I don't get any error for the first command, but I get one for the second: "pq: current transaction is aborted, commands ignored until end of transaction block". Is there a way to actually show some more informative detail concerning the first command (i.e. the real issue?).
Below a short code snippet:

    tx, _ := db_connection.Begin()
    _, err = tx.Exec(insert_statement, bad_values...)
    if err != nil {
        panic(fmt.Sprintf("Error in table %s: %v", table, err)) //this goes right, while it shouldn't
    }
    _, err = tx.Exec(insert_statement, good_values...)
    if err != nil {
        panic(fmt.Sprintf("Error in table %s: %v", table, err))  //this throws, but it's too late!!
    }
    ...
    tx.Commit()

**Comment by cbandy** [comment]
Things seem to work alright for me. What version of this package are you using? Can you provide some SQL to reproduce?

```go
     1  package pq
     2
     3  import "testing"
     4
     5  func TestIssue502(t *testing.T) {
     6          db := openTestConn(t)
     7          defer db.Close()
     8
     9          _, err := db.Exec(`CREATE TABLE IF NOT EXISTS issue502 (i int PRIMARY KEY)`)
    10          if err != nil {
    11                  t.Fatal(err)
    12          }
    13
    14          tx, err := db.Begin()
    15          if err != nil {
    16                  t.Fatal(err)
    17          }
    18          _, err = tx.Exec(`INSERT INTO issue502 VALUES (1), (1)`)
    19          if err == nil {
    20                  t.Fatal("Expected error, got none")
    21          }
    22
    23          t.Log(err)
    24  }
```
```
=== RUN   TestIssue502
--- PASS: TestIssue502 (0.01s)
        regression_test.go:23: pq: duplicate key value violates unique constraint "issue502_pkey"
PASS
```

**Comment by beppeben** [comment]
it turned out to be related to a mistake in the creation of the database, closing the issue.
