### ISSUE TITLE
Support returning database types

### ISSUE THREAD

**Issue by freeformz** [lib/pq#510]
If this lands: https://go-review.googlesource.com/#/c/29961/

cc @johto @uhoh-itsmaciek (maybe others) want to comment on the CL?

**Comment by itsjamie** [comment]
This relates to #531. Linking so that it contains all the issues related.

**Comment by egravert** [comment]
I'm interested in adding this feature, and would love some suggestions on how best to get the nullability of the returned rows. From my reading of the protocol docs, it seems the best option is to parse the row description and use the row modifier value. Any suggestions/pointers would be appreciated!

**Comment by runner-mei** [comment]
?
