### ISSUE TITLE
pg.StringArray is nil when db array is empty

### ISSUE THREAD

**Issue by kokteyldev** [lib/pq#513]
When an empty db array is mapped to pg.StringArray using sqlx.Select, the resulting field has nil value. 
Go version: 1.7.1

**Comment by cbandy** [comment]
So this SQL `SELECT ARRAY[]::text[]` with code similar to `var x pq.StringArray ; ... .Scan(&x)` causes `x == nil` ?

**Comment by kokteyldev** [comment]
Not exactly, we have a column which is of type `text[]`. I am not casting the result using `::text[]`, but I don't think that would make a difference. Yes in that case the Scan() returns nil.

**Comment by kokteyldev** [comment]
I found out that the problem is while converting to json the empty StringArray is converted to null. The library maps the correct result but json conversion doesn't work. Closing the issue.
