### ISSUE TITLE
Use binary_parameters?

### ISSUE THREAD

**Issue by danilobuerger** [lib/pq#514]
In which situation is it wise to use `binary_parameters=yes`? In my benchmark, this seems to be significantly faster for non-simple queries. Shouldn't this always be on if []byte is truly meant as bytes and not just a cast from string? If so, is it just off by default for compatibility reasons but recommended to be on?

**Comment by freeformz** [comment]
Closing in favor of #435.

**Comment by danilobuerger** [comment]
@freeformz how does #435 answer my question?

**Comment by freeformz** [comment]
It's a issue asking for documentation for binary_parameters. I also merged https://github.com/lib/pq/commit/068cb1c8e4be77b9bdef4d0d91f162160537779e as well, which should help describe what it's doing.

**Comment by danilobuerger** [comment]
I know what it is doing. My question is if it is recommended.

**Comment by freeformz** [comment]
Recommendation is something we can handle in the docs., but I would say that it's not recommended unless you are have an interest in doing your own marshaling of data to []byte.

**Comment by cskr** [comment]
@freeformz What do you mean by "your own marshaling of data to []byte"? The driver [seems to use text encoding][1] for types other than `[]byte`, even if `binary_parameters` is enabled.

However, it always uses 2 roundtrips for parameterized queries if it is not enabled. So it seems like a good idea to enable it always. What am I missing?

[1]: https://github.com/lib/pq/blob/ed1a26d9e1fd4eb1cc491e6d688467f4e81a413c/conn.go#L1451
