### ISSUE TITLE
Wrong Scan after NULL values

### ISSUE THREAD

**Issue by palestamp** [lib/pq#516]
In case when `price` field is NULL in postgres result set all fields AFTER it also parsed as nil values of corresponding types
```
    defer rows.Close()
	for rows.Next() {
		row := new(gl.DCAdAggregate)
		rows.Scan(&row.AdID,
			&row.Subject,
			&row.Body,
			&row.Status,
			&row.Category,
			&row.Price,
			&row.ImageCount,
			&row.Names,
			&row.Values)
		adAgg = append(adAgg, row)
	}
```

Struct definition is next
```
type DCAdAggregate struct {
	AdID       int
	Subject    string
	Body       string
	Status     string
	Category   int
	Price      int64
	ImageCount int64
	Names      pq.StringArray
	Values     pq.StringArray
}
```

May be it is not a bug, but how to properly deal with such kind of issue?

**Comment by cbandy** [comment]
[`rows.Scan`](https://golang.org/pkg/database/sql/#Rows.Scan) returned an error. There are [lots of places](http://go-database-sql.org/retrieving.html) that return `error` when retrieving results and it is important to check them all.

The [`NullInt64` type](https://golang.org/pkg/database/sql/#NullInt64) does not error when receiving a NULL value..
