### ISSUE TITLE
why bytea field only  return the Length of field?

### ISSUE THREAD

**Issue by hzmnet** [lib/pq#519]
i have a field store file. but when i query . it only return the Length of field. how can i get the content?

**Comment by mjibson** [comment]
Can you show some code that does this?

**Comment by hzmnet** [comment]
i just select full table and scan in to a map[string]interface{]. and Print it

**Table**
`CREATE TABLE public.sys_attachment
(
  id integer NOT NULL DEFAULT nextval('sys_attachment_id_seq'::regclass),
  create_id integer,
  create_time timestamp without time zone,
  write_id integer,
  write_time timestamp without time zone,
  name character varying NOT NULL,
  file_name character varying,
  description character varying,
  res_name character varying,
  res_model character varying(255),
  res_id integer,
  create_date timestamp without time zone,
  company_id integer,
  type character varying(255),
  url character varying(1024),
  datas bytea,
  store_fname character varying,
  db_datas bytea,
  file_size integer,
  checksum character varying(255),
  mimetype character varying,
  index_content text,
  public boolean,
  datas_fname character varying,
  CONSTRAINT sys_attachment_pkey PRIMARY KEY (id)
)`

**Code:**

`
tempMap := make(map[string]interface{})		
res_err = lRows.ScanMap(&tempMap)
			if res_err != nil {
				return
			}
			logger.Dbg("SqlQuery tempMap :", tempMap)`


**Print:**
[SqlQuery tempMap : map[datas:16 kB ]]

**Comment by hzmnet** [comment]
sorry i think i found what problem it happened
