### ISSUE TITLE
Using io.Reader and io:Writer

### ISSUE THREAD

**Issue by FnuGk** [lib/pq#520]
Would it be possible to implement using`io.Reader` and `io.Writer` to stream data to and from the database.
fx. writing a `http.Response.Body` directly into the database instead of using`ioutil.ReadAll` to first pull the body into memory and then transfer it to the database.

**Comment by mjibson** [comment]
I don't think this is useful because the pgwire protocol dictates that messages start with their length. Thus, lib/pq would have to read the entire io.Reader into memory itself to figure out the length.

**Comment by FnuGk** [comment]
is it not possible to implement using `COPY FROM`? I don't really know how the pgwire protocol works but in #213 it is proposed that copy from and copy to should be conforming to io.Reader and io.Writer

**Comment by mjibson** [comment]
That may be a good API choice, but the copy messages still have to prepend the length of bytes they are sending. Making copy not use the sql package as a wrapper would be a requirement for that, and that's a larger change.

**Comment by kardianos** [comment]
The way the database/sql package works, unfortunately this probably won't be useful. Unless the Rows struct grew a "ScanInto" method that is called before Rows.Next(), and the type checks were modified to allow Readers, this wouldn't be useful in that context.

**Comment by freeformz** [comment]
You can probably do this if you made a struct that takes a http.Response and implements the driver.Valuer interface. But that would likely need to read in all of the Body anyway (negating a good chunk of it's usefulness) to return a value that [driver.Value](https://golang.org/pkg/database/sql/driver/#Value) can contain. The same is likely possible on the inverse using the sql.Scanner with similar caveats.

If you proof something and you think it's generally useful please let us know.

Thx.
