### ISSUE TITLE
Support for setting transaction isolation level

### ISSUE THREAD

**Issue by mastersobg** [lib/pq#526]
It would be nice to have ability to configure transaction isolation level https://www.postgresql.org/docs/9.3/static/sql-set-transaction.html

**Comment by uhoh-itsmaciek** [comment]
You can run this as a SQL statement at the beginning of the transaction. I don't think a nicer interface is possible given the constraints of the `database/sql` API--there's no way to configure a transaction when starting it.

**Comment by mastersobg** [comment]
Oh, yes, indeed, it's impossible to do without breaking sql API. Closing the issue then.
