### ISSUE TITLE
Go 1.8 support

### ISSUE THREAD

**Issue by c4milo** [lib/pq#549]
Here is the list of changes in `database/sql` for 1.8: 
https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit 

So far this driver was working fine for me in Go 1.8 until this change got included in tip:
https://github.com/golang/go/commit/0d163ce1c95d03a173eba246de6d45db69e678ac

**Comment by mjibson** [comment]
What isn't working for you? We have a test passing as of (https://travis-ci.org/lib/pq/jobs/179911281)

`go version devel +4822e76 Tue Nov 29 21:38:45 2016 +0000 linux/amd64`

**Comment by c4milo** [comment]
A transaction I have is being cancelled before finishing. 
```
Database error: context canceled
unexpected postgres error
```

I will try to come up with test case, also to see if I'm misusing the library somehow. However my test have always run fine without golang/go@0d163ce

**Comment by mjibson** [comment]
Ok, I'm interested to see that test case. I also have https://github.com/lib/pq/pull/535 which would add explicit support for many of the Context methods. I'm interested to see if that would fix the issue too (but obviously it needs to be fixed for the case without the PR too).

**Comment by c4milo** [comment]
So I have this piece of code that was committing the transaction: 

```
	defer func() {
			if e := tx.Commit(); e != sql.ErrTxDone {
				err = database.Error(e, errorsMap)
			}
		}()
```

It was always returning an error of type `sql.ErrTxDone`, with Go 1.8 it returns an internal error

**Comment by c4milo** [comment]
Ok, this doesn't seem to be an issue with `pq` https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1452-L1456
