### ISSUE TITLE
QueryRow, connection does not close

### ISSUE THREAD

**Issue by JosefWN** [lib/pq#550]
I'm using QueryRow with "RETURNING id", and I'm not always using the id, so the row.Scan(...) does not always occur... in which case the connection does not close. Is this intended? It's not long before I run into MaxOpenConns and the server stops responding.

I have the same issue with certain Exec-calls. Didn't think I needed to Scan QueryRow or do anything to Exec-calls to close them?

**Comment by cbandy** [comment]
It's true, I don't see anything in the database/sql docs saying that you must call Scan. (There's also nothing saying you must call Close...) The way database/sql interacts with drivers, including lib/pq, the answer is "yes" leaving sql.Rows or sql.Row open/unused leaves the connection hanging.

More practically speaking, Scan is the only way to gather an error from QueryRow. If you don't call Scan, you're not going to know if the query failed!

**Comment by Puffton** [comment]
So to make sure I got this right. In essence, to make sure I have no open connections:

**Query (in function):**
```go
if err == nil {
  defer rows.Close()
  // Do stuff...
}
```

**Query (in inf-loop such as service):**
```go
if err == nil {
  // Do stuff...
  rows.Close()
}
```

**QueryRow:**

Always
```go
Query(...).Scan(...)
```

**Exec:**
No need to do anything?

**Comment by mjibson** [comment]
I think that's a correct summary, yes.

**Comment by Puffton** [comment]
```sql
SELECT * FROM pg_stat_activity;
```

This shows some idle connections from my app (I've made sure all Query/QueryRow/Exec's are on the form mentioned in my previous post). I'm not sure if the thread pool keeps them open for longer periods of time by default (and keeps opening new ones until it reaches MaxOpenConnections), or if I'm still leaking connections for some reason?

Server has max connections 100, in Go I've SetMaxOpenConns(20).

**Comment by cbandy** [comment]
You can use DB.Stats() to check the number of open connections in a pool.
