### ISSUE TITLE
Support for typed nil from Value() function

### ISSUE THREAD

**Issue by hamaxx** [lib/pq#551]
It took me a couple of hours to figure out why a small code cleanup of a struct which implements Valuer interface resulted in failed database updates, so I decided to open this issue even though I'm not sure if it makes sense for pq to handle this special case.

Here is the problem:

Value() function has to return [driver.Value](https://golang.org/pkg/database/sql/driver/#Value) interface. If the returned driver.Value is nil, pq will set the database field to NULL.

One of the allowed types for driver.Value is []byte, so this code looks correct (to me):

	func (x *X) MarshalJSON() ([]byte, error) {
		if x == nil {
			return nil, nil
		}
		return json.Marshal(x.someValue)
	}

	func (x *X) Value() (driver.Value, error) {
		return x.MarshalJSON()
	}

But it has an interesting bug. If x is nil, MarshalJSON will return nil, but the nil will be typed to []byte, so when Value returns []byte(nil), the returned driver.Value interface won't be equal to nil since it will have a type. Assuming the database field is of type json, pg will return "invalid input syntax for type json".

This might be the expected result, but it's very unintuitive.

It might make sense for []byte encoder to handle nil []byte slices as NULL but I'm not sure if this can be done in 100% backwards compatible way.

Any thoughts?

**Comment by cbandy** [comment]
You are correct about the types and the interaction with `database/sql` and `lib/pq`.

I wish the `sql` or `driver` packages spoke more directly about how to expect/handle NULL values. There are a handful of places from which to infer the policy:

1. https://golang.org/pkg/database/sql/#Scanner
2. https://golang.org/pkg/database/sql/driver/#NotNull
3. https://golang.org/pkg/database/sql/driver/#Null

In these cases, NULL means `interface{}(nil)` and `driver.Value(nil)`. I think `lib/pq` is correct to interpret and return (only) these values for NULL.

That being said, I don't think your code is doing what you expect. `(*X)(nil).MarshalJSON()` does not return valid JSON. You are likely using `json.Marshal((*X)(nil))` which detects a nil pointer and returns `[]byte("null"), nil`. Try a panic inside `if x == nil` and I think you will see no panics (when rendering JSON.)

`database/sql` will also detect a nil pointer, but [only if that pointer doesn't already implement `Valuer`](https://github.com/golang/go/blob/go1.7/src/database/sql/driver/types.go#L211-L232). Change your receivers to values and I think everything will work the way you want:

```go
func (x X) MarshalJSON() ([]byte, error) { return json.Marshal(x.someValue) }
func (x X) Value() (driver.Value, error) { return x.MarshalJSON() }
```

**Comment by cbandy** [comment]
@hamaxx did you find a solution?

**Comment by matthewmueller** [comment]
One solution seems to be:

```go
var meta []byte
if len(t.Meta) == 0 {
	meta = []byte("{}")
} else {
	meta, err = json.Marshal(t.Meta)
	if err != nil {
		return t, err
	}
}
```

Pretty easy to forget though.

**Comment by hamaxx** [comment]
@cbandy thank you very much for the explanation. My solution was to check for nil and return untyped nil from Value()

    func (x *X) Value() (driver.Value, error) {
	val := x.serialize()
        if val == nil {
            return nil, nil
        }
        return val
    }

It looks a bit strange, but it works. I'll close this issue since it seams pq works as intended.

**Comment by matthewmueller** [comment]
Quick question: is `x.serialize()` something you implemented?

**Comment by hamaxx** [comment]
@matthewmueller yes, it's just an example. It can be any method that returns []byte. In our case it's a method that return nil or json serialized value. I changed the name from MarshalJSON because cbandy is correct that returning nil from MarshalJSON is invalid.

**Comment by cbandy** [comment]
> Also pretty strange that postgres accepts the string "null" for a JSON field.

`null` is a valid JSON value. This SQL returns three `json` columns; one with no value, one with a JSON null and one with a JSON string:

```sql
SELECT null::json, 'null'::json, '"null"'::json
```

To send the first with `database/sql`, use `nil`.
