### ISSUE TITLE
listener.Notify panic when listener gets (temporarily) disconnected

### ISSUE THREAD

**Issue by matthewmueller** [lib/pq#560]
I've been testing out what happens if you lose the DB connection and it seems to crash the process. 

```
2017/01/29 21:35:35 error error listening           error=pq: terminating connection due to administrator command
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x217b]

goroutine 1 [running]:
panic(0x1cf660, 0xc42000c0d0)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:500 +0x1a1
main.main()
```

Here's the example code:

```go
package main

func main () {
        conn := "postgres://localhost:5432/test?sslmode=disable"
	listener := pq.NewListener(conn, 10*time.Second, time.Minute, func(ev pq.ListenerEventType, err error) {
		if err != nil {
			fmt.Println(err)
		}
	})

	listener.Listen("a")

	for {
		n := <-listener.Notify
		fmt.Println(n.Channel)
	}
}
```

To reproduce:

1. postgres
2. go run main.go
3. stop postgres
4. start postgres

**Comment by johto** [comment]
From the documentation:

> A notification channel will remain open until Unlisten is called, though connection loss might result in some notifications being lost. To solve this problem, Listener sends a nil pointer over the Notify channel any time the connection is re-established following a connection loss.

So your Println is dereferencing a nil `n`.
