### ISSUE TITLE
Connection pooling (pq vs pgx)

### ISSUE THREAD

**Issue by u89012** [lib/pq#561]
Can someone throw some light on why the following code fails with "pq: sorry, too many clients already"? I'm using the postgres 9.6.1, golang go1.8rc3 darwin/amd64.

Using db.SetMax* doesn't seem to help either (and results in "dial tcp [::1]:5432:  socket: too many open files" during later runs)

Oddly, I've another prototype which uses the pgx adapter that seems to have no issues at all.

```
package main

import (
	"database/sql"
	"log"
	"sync"

	_ "github.com/lib/pq"
)

func main() {
	if db, e := sql.Open("postgres", "user=a dbname=a sslmode=disable"); e != nil {
		panic(e)
	} else {
		defer db.Close()
		db.SetConnMaxLifetime(0)
		// db.SetMaxOpenConns(100)
		// db.SetMaxIdleConns(100)

		wg := sync.WaitGroup{}
		for i := 0; i < 100000; i++ {
			go func() {
				wg.Add(1)
				defer wg.Done()

				if tx, e := db.Begin(); e != nil {
					panic(e)
				} else {
					if r, e := tx.Query("select id from users"); e != nil {
						panic(e)
					} else {
						defer r.Close()
						for r.Next() {
							//
						}
					}
					tx.Rollback()
					log.Println("tx closed")
				}
			}()
		}
		wg.Wait()
	}
}

```

**Comment by kardianos** [comment]
You may want to run `go vet` on the above code. I think it misuses the WaitGroup.

Do you have the `db.SetMaxOpenConns` uncommented in the actual test?
Why do you have `db.SetConnMaxLifetime` set to zero?

**Comment by u89012** [comment]
Thanks for your reply and your time.

I'm afraid `go vet` doesn't seem to report anything for me (I'm running go 1.8)

Per the docs setting `db.SetConnMaxLifetime` to zero allows connections to be reused forever (which I thought that might help in this case).

I've tried setting `db.SetMaxOpenConns` and `db.SetMaxIdleConns` but they result in "too many open files".

**Comment by carlmjohnson** [comment]
You're definitely misusing the `WaitGroup`. You need to call `Add` _before_ starting the goroutine, otherwise, the order of events is unknown.

**Comment by kardianos** [comment]
@u89012 In case I wasn't clear before, please correct the above usage of WaitGroup, retest and post that code. Then we can look into the issue further.

**Comment by cbandy** [comment]
Using the OP code, I get ~650 `tx closed` messages, then `fatal error: runtime: out of memory`.

```
db.SetConnMaxLifetime(0)
// db.SetMaxOpenConns(100)
// db.SetMaxIdleConns(100)
```

When I change the above lines to the following, I get ~14k `tx closed` messages, then an error from `db.Begin()`: `pq: remaining connection slots are reserved for non-replication superuser connections`. (My backend is set to 100 `max_connections`, 3 reserved.)

```
db.SetConnMaxLifetime(0)
db.SetMaxOpenConns(100)
// db.SetMaxIdleConns(100)
```

When I change the above lines to the following, I get exactly 100k `tx closed` messages (18 seconds start-to-finish.)

```
db.SetConnMaxLifetime(0)
db.SetMaxOpenConns(90)
// db.SetMaxIdleConns(100)
```

All this over a unix domain socket; `go version go1.7.1 linux/amd64`.
Tried the final case over TCP as well; no trouble.

**Comment by u89012** [comment]
Thanks everyone for your time.

@carlmjohnson I looked at the docs and yes you're right, `WaitGroup.Add` should be called before spawing a goroutine. So, thank you. But I've tried moving `Add` inside and out of the goroutine and it doesn't seem make any difference at all. Also I'm not sure not calling `Add` before spawing the goroutine creates confusion in the order of events, well, at least here. The error messages clearly shows the order.
@kardianos Really? In case I wasn't clear before? Did you even read my reply that `go vet` didn't report anything? While I appreciate all the work you've probably (pardon me but I can't find you on the contributors list) done here, being condescending isn't really useful to anyone and only portrays you in a bad light especially when the problem at hand wasn't really about `WaitGroup` at all but thank you, nonetheless, for your contribution.
@cbandy That did it! The only thing that seems to matter is calling SetMaxOpenConns(). Thank you so much! 

```
// db.SetConnMaxLifetime(0)
db.SetMaxOpenConns(100)
// db.SetMaxIdleConns(100)

```

**Comment by kardianos** [comment]
I maintain database/sql in the stdlib. I may know what I'm talking about.

**Comment by u89012** [comment]
Perhaps, but you inquiring why SetConnMaxLifetime was set to 0 or pointing vaguely and repeatedly at WaitGroup doesn't really help your case! Also what good is knowing when you can't help or guide your own users? That said, please accept my sincere thanks for all your work! My work wouldn't be possible without yours!
