### ISSUE TITLE
How do you deal with `Register called twice for driver postgres` when using multiple libs?

### ISSUE THREAD

**Issue by dgellow** [lib/pq#569]
Hi,

I'm trying to use two packages, both importing `github.com/lib/pq`. As expected I get the error `panic: sql: Register called twice for driver postgres`. 

How do you handle that situation? Do I have to reimplement both packages parts that are using postgres so that I don't register twice or is there another solution?

For informations I'm trying to use [mattes/migrate](https://github.com/mattes/migrate) and [go-macaron/session](https://github.com/go-macaron/session).

**Comment by lakeo** [comment]
this [comment](https://github.com/lib/pq/issues/238#issuecomment-250018321) may help
