### ISSUE TITLE
Concurrent map writes

### ISSUE THREAD

**Issue by piotrkowalczuk** [lib/pq#570]
Hi,

i have faced such issue today:

```
fatal error: concurrent map writes
goroutine 4155 [running]:
runtime.throw(0xb18b1d, 0x15)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420672af0 sp=0xc420672ad0
runtime.mapassign(0xa80880, 0xc4204898c0, 0xc420672c08, 0x0)
	/usr/local/go/src/runtime/hashmap.go:589 +0x2a1 fp=0xc420672b90 sp=0xc420672af0
<PROJECT_PATH>/vendor/github.com/lib/pq.ssl(0xc4204898c0, 0x0)
	/go/src/<PROJECT_PATH>/vendor/github.com/lib/pq/ssl.go:34 +0x27d fp=0xc420672da0 sp=0xc420672b90
<PROJECT_PATH>/vendor/github.com/lib/pq.(*conn).ssl(0xc420a178c0, 0xc4204898c0)
	/go/src/<PROJECT_PATH>/vendor/github.com/lib/pq/conn.go:1033 +0x40 fp=0xc420672e40 sp=0xc420672da0
<PROJECT_PATH>/vendor/github.com/lib/pq.(*conn).cancel(0xc420b3a2c0)
	/go/src/<PROJECT_PATH>/vendor/github.com/lib/pq/conn_go18.go:81 +0xf2 fp=0xc420672ef0 sp=0xc420672e40
<PROJECT_PATH>/vendor/github.com/lib/pq.(*conn).(<PROJECT_PATH>/vendor/github.com/lib/pq.cancel)-fm()
	/go/src/<PROJECT_PATH>/vendor/github.com/lib/pq/conn_go18.go:19 +0x2a fp=0xc420672f08 sp=0xc420672ef0
<PROJECT_PATH>/vendor/github.com/lib/pq.watchCancel.func1(0xece220, 0xc42040f170, 0xc420493400, 0xc4203674a0)
	/go/src/<PROJECT_PATH>/vendor/github.com/lib/pq/conn_go18.go:67 +0xc4 fp=0xc420672fc0 sp=0xc420672f08
runtime.goexit()
```

**pq version**: `ba5d4f7a35561e22fbdf7a39aa0070f4d460cfc0`
**postgres version**: `9.2`
**go version**: `1.8`

**Comment by cbandy** [comment]
Thank you for the report. This is happening because the [connection settings mutate](https://github.com/lib/pq/blob/ba5d4f7a35561e22fbdf7a39aa0070f4d460cfc0/ssl.go#L34)&sup1; during context cancel. We should be more careful with these options now that they are being used by more than one connection.

&sup1; The mutation was [added here](https://github.com/lib/pq/commit/d8a8e22c510f757bde3d4e2a47a5878994edfedf) to emulate some [quirky behavior of `libpq`](https://github.com/lib/pq/pull/431#issuecomment-181650478).

**Comment by tamird** [comment]
I've been unsuccessfully trying to reproduce this. It's true that connection settings mutate during context cancellation, but I'm not seeing how that races with anything.

Connection settings are instantiated during `DialOpen()`, which creates a new `conn`. It is not possible to have more than one query pending on a `conn` at a time (which precludes the possibility of multiple cancellations racing with one another). This seems to point to the possibility of cancellation racing with `DialOpen` itself, though this seems impossible by definition.

@piotrkowalczuk could you provide some additional details on this? Have you been able to reproduce it consistently? It's unfortunate that you only seem to get the cancelling goroutines' stack trace (but perhaps if you've been able to reproduce, you occasionally got the other writer's stack?).
