### ISSUE TITLE
how to view the raised notices from postgresql

### ISSUE THREAD

**Issue by whiskas** [lib/pq#580]
hi! thank you for gread pg driver.

I was not found where postgresql raised messages stored in *sql.Conn

ex. in pg:

create function show_mes() returns int as $$
begin
     raise notice 'test message from pg';
     return 1;
end
$$ language plpgsql;

from go app I call this function and can get the result.

But how can i access to that messages from go app?

thank you!

**Comment by whiskas** [comment]
find related questions in stackoverflow:
[http://stackoverflow.com/questions/42070023/how-do-i-get-postgresql-procedure-warning-messages-in-golang](url)

**Comment by uhoh-itsmaciek** [comment]
Unfortunately these [are ignored](https://github.com/lib/pq/blob/master/conn.go#L973-L974) by pq. Given the design of database/sql, I don't think there's a good way to expose them.

**Comment by whiskas** [comment]
I's very sad (
I think lot of people using pg need this feauture..

**Comment by uhoh-itsmaciek** [comment]
I agree, it's sad. If you have suggestions on what the API might look like given the constraints of database/sql, I think the implementation would be straightforward, but I don't see a reasonable way to support it at all.

**Comment by whiskas** [comment]
maybe we can import lib/pq not as named import

like 

import pq "github.com/lib/pq"
....
pq.logNotice(true)

and here
```

switch t {
		case 'A', 'N':
             if notice == true {
                 log.Print(........
             }
          // ignore
```

**Comment by whiskas** [comment]
or set some handler like

```
pq.logNotice(handler)
...
```
```
and^
.....
case 'A', 'N':

                 cn.noticeHandler(buf)
   
```

**Comment by whiskas** [comment]
[http://i.imgur.com/1YN2CUP.png](image)

**Comment by cbandy** [comment]
As I recall, package-level features like this apply to all connections and have no way to indicate to you which `sql` call/DB/Txn raised the notice.

**Comment by whiskas** [comment]
I think we can specify notice whene DialOpen called and conn created.

DialOpen
![http://i.imgur.com/INRX9HR.png](http://i.imgur.com/INRX9HR.png)


conn struct

![http://i.imgur.com/gSocGyN.png](http://i.imgur.com/gSocGyN.png)
