### ISSUE TITLE
Parameterized Queries Issue

### ISSUE THREAD

**Issue by abhisheksp** [lib/pq#582]
`query := "WITH b(ColA, ColB) AS (VALUES ($1,$2)) UPDATE schema_name.table_name AS a SET ColC = b.ColB FROM b WHERE a.ColA = b.ColA AND a.ColB = b.ColB"`
`res, err := db.Exec(query, 1, 1)`

The above code fails with the following error:
"pq: operator does not exist: bigint = text"
"ColC" is of type BIGINT
From my investigation, the driver is inserting the values as text instead of ints.

**Comment by johto** [comment]
> From my investigation, the driver is inserting the values as text instead of ints.

No, it's postgres doing it.  Viz:

```SQL
=> prepare qwr as with c(f1) as (values($1)) select pg_typeof(f1) from c;
PREPARE
=> execute qwr('');
 pg_typeof 
-----------
 text
(1 row)
```

Add casts into your VALUES to fix this, or remove the pointless CTE.

**Comment by abhisheksp** [comment]
@johto There would be multiple rows for temp table which is the reason behind using CTE.
I am going to add explicit casts anyway to solve this issue.
