### ISSUE TITLE
Goroutine leak on context timeout

### ISSUE THREAD

**Issue by azr** [lib/pq#594]
Howdy,

I have a system stress testing some sql queries, using context cancellation.

I basically do a lot of requests that take more than 25 seconds and have a context that cancels them after 25 seconds. But for every iteration of this stress test I get goroutine leak.

```
goroutine profile: total 105
74 @ 0x42e70a 0x42e7ee 0x40597d 0x40568d 0x8fc44e 0x45b971
#	0x8fc44d	.../api/vendor/github.com/lib/pq.(*conn).watchCancel.func1+0xcd	.../api/vendor/github.com/lib/pq/conn_go18.go:65
```

Then another test:

```
108 @ 0x42e70a 0x42e7ee 0x40597d 0x40568d 0x8fc44e 0x45b971
#	0x8fc44d	.../api/vendor/github.com/lib/pq.(*conn).watchCancel.func1+0xcd	.../api/vendor/github.com/lib/pq/conn_go18.go:65
```

**Comment by tamird** [comment]
It would be helpful if you could share some code. You can replace the body of the query with a `sleep`.

**Comment by azr** [comment]
I think this is mainly because the timeout cancellation doesn't work.
Here is one case:

```
func TestPsql(t *testing.T) {
	testsService := setup(t, setting{})
	defer testsService.teardown(t)

	wg := errgroup.Group{}
	test := func() error {
		ctx, _ := context.WithTimeout(context.Background(), time.Millisecond)
		for i := 0; i < 3; i++ {
			wg.Go(func() error {
				_, err := testsService.DB.ExecContext(ctx, "SELECT pg_sleep(20)")
				if err == nil {
					t.Error("No error ?")
				}
				return nil
			})
		}
		// cancel() ignoring cancel
		return nil
	}

	dumpGoroutines := func() {
		for i := 0; i < 3; i++ {
			log.Printf("there is %d goroutines right now", runtime.NumGoroutine())
			time.Sleep(25 * time.Millisecond)
		}
	}

	for i := 0; i < 1000; i++ {
		test()
	}
	dumpGoroutines()

	for i := 0; i < 1000; i++ {
		test()
	}
	dumpGoroutines()

	wg.Wait()

	for i := 0; i < 1000; i++ {
		test()
	}
	dumpGoroutines()
	wg.Wait()
}
```

**Comment by azr** [comment]
But shouldn't the context be auto cancelled after a millisecond ??????

**Comment by tamird** [comment]
Your code is racy.
```go
	for i := 0; i < 1000; i++ {
		test() // spawns 3 goroutines for 1ms each
	}
	dumpGoroutines() // may be called less than 1ms after the last goroutines are created
```

**Comment by azr** [comment]
the 3 goroutines take forever to leave

**Comment by azr** [comment]
We can do like this if it makes you feel better :)
```
func TestPsql(t *testing.T) {
	testsService := setup(t, setting{})
	defer testsService.teardown(t)

	wg := errgroup.Group{}
	test := func() error {
		ctx, _ := context.WithTimeout(context.Background(), time.Millisecond)
		for i := 0; i < 3; i++ {
			wg.Go(func() error {
				_, err := testsService.DB.ExecContext(ctx, "SELECT pg_sleep(20)")
				if err == nil {
					t.Error("No error ?")
				}
				return nil
			})
		}
		// cancel() ignoring cancel
		return nil
	}

	dumpGoroutines := func() {
		for i := 0; i < 3; i++ {
			log.Printf("there is %d goroutines right now", runtime.NumGoroutine())
			time.Sleep(25 * time.Millisecond)
		}
	}

	for i := 0; i < 1000; i++ {
		test()
	}
	wg.Wait()
	dumpGoroutines()
}
```

**Comment by azr** [comment]
Also, this returns quickly: 

```
func TestContext(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), time.Microsecond)
	wg := errgroup.Group{}
	for i := 0; i < 400; i++ {
		wg.Go(func() error {
			<-ctx.Done()
			return nil
		})
	}
	wg.Wait()
	cancel()
}
```

**Comment by azr** [comment]
do you have the same behavior @tamird ?

**Comment by azr** [comment]
Okay, So my example is bad and it's not expressing my problem, the number of goroutines go up because it's using contexts with timeout... That I don't cancel. They create the goroutines.

--------
The following example demonstrates the real problem the example I gave; 
we use up the number of connections and then Locking the connection to `Exec` will block until one of the request returns, but they all take 20s and start approximatively at the same time, that's why it takes too much time : 
```
func TestPsql(t *testing.T) {
	testsService := setup(t, setting{})
	defer testsService.teardown(t)

	topWG := errgroup.Group{}
	for i := 0; i < 1000; i++ {

		ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
		topWG.Go(func() error {
			downWG := errgroup.Group{}
			for i := 0; i < 3; i++ {
				downWG.Go(func() error {
					_, err := testsService.DB.ExecContext(ctx, "SELECT pg_sleep(20)")
					if err == nil {
						t.Error("No error ? ", ctx.Err())
					}
					return nil
				})
			}
			downWG.Wait()
			cancel()
			return nil
		})
	}
	topWG.Wait()
}
```
Here, depending on the number of db connection and `GOMAXPROCS`, the tests can take more than 20s and I think it should not.
But I think this is not something you could fix simply because `mutex.LockContext(ctx)` or similar doesn't exist yet.

--------

I'll try to give a reproduction of the lock in `watchCancel  / conn_go18.go:65`

**Comment by mjibson** [comment]
Why shouldn't it take more than 20s? The postgres default is 100 connections. You are starting 3000 go routines there, that should all take 1s to complete. 3000s / 100 connections = 30s. Seems correct to me.

**Comment by azr** [comment]
@mjibson oooooooh, right, sorry, this is not a problem then. Sorry I am confusing >.<

**Comment by azr** [comment]
@mjibson I still have the original issue, should I make a new one ?

The original issue is that I have these `pq.(*conn).watchCancel.func1+0xcd` leaking.

**Comment by azr** [comment]
I think this is due to the fact that I call `Done` after `rows.Next` does it. that func from watchCancel is expecting to be called only once I guess.

**Comment by mjibson** [comment]
Which is the test code demonstrating the leaking? There is a lot of code above.

**Comment by azr** [comment]
None of those, I was trying to reproduce but failed lamentably, I'll try to bring you a proper case

**Comment by ainar-g** [comment]
@azr Look into #617. You might've had the same issue as me, so my fix might've worked for you.

**Comment by azr** [comment]
Hey @ainar-g  very cool, thanks ! I'll try it right away

**Comment by azr** [comment]
yup all fixed ! cheers !
