### ISSUE TITLE
Failed QueryContext followed by Query/Exec causes unexpected error

### ISSUE THREAD

**Issue by jwilander** [lib/pq#611]
I commented with this on #577 but in case it got missed because that issue is closed, I've opened a new issue. Here's my comment from the other thread:

I believe I've found a related unhandled case that is causing me issues. If I make a query using `db.QueryContext(...)` that fails and then try a `db.Exec(...)`  or `db.Query(...)` I'm getting the `pq: canceling statement due to user request` error.

Modifying the `TestContextCancelQuery` test like below reproduces the error:

```Go
func TestContextCancelQuery(t *testing.T) {
	db := openTestConn(t)
	defer db.Close()

        // removed some code not needed to demonstrate the example

	for i := 0; i < contextRaceIterations; i++ {
		func() {
			ctx, cancel := context.WithCancel(context.Background())
			rows, err := db.QueryContext(ctx, "select * from tablethatdoesnotexist") // select from non-existent table to cause failure
			cancel()
			if err != nil {
				return // don't fail on error so we get to the query below
			} else if err := rows.Close(); err != nil {
				t.Fatal(err)
			}
		}()

		if rows, err := db.Query("select 1"); err != nil {
			t.Fatal(err)
		} else if err := rows.Close(); err != nil {
			t.Fatal(err)
		}
	}
}
```

In the test I just switched the QueryContext to fail and removed the fatal so that the test does not stop

**Comment by ainar-g** [comment]
@jwilander This might've got fixed along with #617. Can you please update and check it out?

**Comment by jwilander** [comment]
Yes, I can check and let you know

**Comment by jwilander** [comment]
@ainar-g seems to have worked, thanks!

Let me know if it would be worthwhile for me to submit a unit test covering this case and I can submit one.
