### ISSUE TITLE
Support for []string in arguments

### ISSUE THREAD

**Issue by bartgrantham** [lib/pq#615]
It would be helpful for the pq driver to support []string as an argument type:

`rows, err := Db.Query("select * from foo where bar in ($1)", slice_of_strings)`

I may have overlooked something, but I don't see an easy way to express that query without ugly string/sql munging.  Worse, because PostgreSQL requires numbered parameters and doesn't support "?" as a placeholder, you have to track the current parameter number as you construct the query.

PostgreSQL seems to support this (see the first INSERT example [here](https://www.postgresql.org/docs/9.5/static/xfunc-sql.html#XFUNC-SQL-FUNCTION-ARGUMENTS)), but I'm not sure how the driver would know the array datatype context in this type of query.  It may boil down to a bunch of string munging, which may be more trouble than its worth.

If there's a simple, idiomatic way to do this type of query (IN clause with variable parameters) that negates the need for this request, please share it and feel free to close this issue.

**Comment by johto** [comment]
`WHERE bar = ANY($1)`.  Though you'll still need to use the [proper class](https://godoc.org/github.com/lib/pq#StringArray) to get the slice passed to the database as an array.

**Comment by bartgrantham** [comment]
That worked beautifully.  I completely glossed over the pq Types, I should've looked more carefully.  Thank you!
