### ISSUE TITLE
How to call a remote procedure (stored procedure)

### ISSUE THREAD

**Issue by the42** [lib/pq#62]

**Comment by victorhugoviiii** [comment]
This work for me, Greetings

fmt.Print("inserting Persona => ")
sqlStatement := "select * from crear_persona('" + persona.Ci + "','" + persona.Nombre + "','" + persona.App + "','" + persona.Apm + "','" + persona.Cuenta + "','" + persona.Contrasenia + "','" + persona.Estado + "')"
_, err := db.Exec(sqlStatement)
if err != nil {
	fmt.Println("Error inserting Persona")
	fmt.Println(err)
	panic(err)
}
fmt.Println("Persona inserted")

**Comment by steevel** [comment]
@victorhugoviiii I sure do hope that was a joke! (A bad joke at that!)
