### ISSUE TITLE
Final stmt.Exec() on CopyIn produces invalid sql.Result object

### ISSUE THREAD

**Issue by djoyner** [lib/pq#626]
The docs for CopyIn state that a final call to `stmt.Exec()` should be made to flush buffers. Although the example in the docs discards the `sql.Result`-typed return value from this call, there is one actually returned by `database/sql` in the non-error case. Unfortunately this is a broken `sql.driverResult` object in the sense that no `driver.Result` was actually returned from the code here: https://github.com/lib/pq/blob/master/copy.go#L231-L233.

Any attempt to use this object results in a panic, e.g. by calling `RowsAffected()` with a panic at https://github.com/golang/go/blob/master/src/database/sql/sql.go#L2843.

I recognize that it's not particularly useful to call `RowsAffected()` in this case. However we wrap the `database/sql` API with tracing/logging code that wants to inspect `sql.Result` objects without regard for where they came from.

**Comment by FdeFabricio** [comment]
Is there a reason to RowsAffected be zero after a CopyIn?
