### ISSUE TITLE
some issue(s) when using with Redshift-Specturm

### ISSUE THREAD

**Issue by siddharth178** [lib/pq#629]
I tried using it. For simple queries it works perfectly fine. But when query has $1 like arguments, Select(...) call fails with following error -
``pq: could not open relation with OID <some number>``

Is it anything related to pq driver or its mostly AWS side issue?
Has anyone used/actively-using pq with AWS's Redshift-Specturm?

**Comment by cbandy** [comment]
That message is coming from Redshift. Can you perhaps provide the query that triggers this?

**Comment by siddharth178** [comment]
Sorry for late reply.

Here is the sample query I am trying to run against Spectrum -
```
query := `SELECT
    *
FROM
    sample_table
WHERE
  age = $1
`
_, err := Select(&records, query, 42)

```

**Comment by siddharth178** [comment]
Did anyone got a chance to look at this failure?
Which are possible areas in the code to look into related to this issue?

**Comment by johto** [comment]
> Which are possible areas in the code to look into related to this issue?

This is almost certainly not a problem in `pq`.  My money's on gorp, but it could be an issue in the server as well.

I'd first figure out which exact query is failing and then work from there.

**Comment by johto** [comment]
> My money's on gorp, but it could be an issue in the server as well.

Oh, just saw that this is Redshift; I change my bet to the server in that case.

**Comment by siddharth178** [comment]
Better to check on AWS forum then?

**Comment by siddharth178** [comment]
It was something to do with AWS Redshift Spectrum implementation. Its working now.
