### ISSUE TITLE
Caching rows

### ISSUE THREAD

**Issue by tclass** [lib/pq#631]
It would be nice, if there would be an option to cache rows. I have the problem that I sometimes work with big datasets (> 50m rows) it would be nice to let the driver cache the results so that he doesn't have to ask that database for every row but reads a batch in a buffer.

I might be wrong, but I couldn't find an option for this or that it's already implemented.

**Comment by cbandy** [comment]
> it would be nice to let the driver cache the results so that he doesn't have to ask that database for every row

Rows come from the database in a stream, and there's no acknowledgment or other communication from the client to the server per row.

> I might be wrong, but I couldn't find an option for this or that it's already implemented.

Correct. There is no batching or buffering of multiple rows that takes place in the driver.

> I sometimes work with big datasets (> 50m rows)

What inefficiency are you experiencing, exactly?

**Comment by tclass** [comment]
I thought why can't I pass a channel and then read from that channel so that there's a constant stream of results and the channel would be the buffer. It's not that I have hard numbers to proof a bottleneck it's just, that it would be a more sophisticated workflow, because when I work on 50m rows, I obviously don't save them in memory, I have a stream that processes the rows and writes them into other systems
