### ISSUE TITLE
Single round-trip parameterized queries without binary_parameters

### ISSUE THREAD

**Issue by cskr** [lib/pq#636]
When `binary_parameters` is not enabled, all parameterized queries take 2 round-trips for execution. Given the PostgreSQL protocol does not require this, single-roundtrip execution must be the default for all unprepared queries, irrespective of whether `binary_parameters` is enabled.

**Comment by johto** [comment]
> Given the PostgreSQL protocol does not require this, single-roundtrip execution must be the default for all unprepared queries, irrespective of whether binary_parameters is enabled.

It's really not that simple.  The root of the problem is that strings and byte slices are guaranteed to be interchangeable.  This decision was made a long time ago, and you could argue that it wasn't maybe the right decision, but it's done, and breaking that contract will break a significant number of applications.

**Comment by cskr** [comment]
@johto I didn't quite get what you mean. I'm not suggesting that `binary_parameters` should be enabled by default. I'm only suggesting that `pq` should not wait for the response of `Parse` message before sending `Bind`, without changing the encoding of parameters.

**Comment by johto** [comment]
> It has nothing to do with how parameters are encoded.

But of course it does.  How are you going to do [this](https://github.com/lib/pq/blob/dd1fe2071026ce53f36a39112e645b4d4f5793a4/encode.go#L35) if you don't know what the types of the parameters are going to be?

**Comment by cskr** [comment]
Ah, makes sense now. Thank you, @johto.

What kind of use-cases may break by switching to always sending `[]byte` and `string` as is?

**Comment by cskr** [comment]
Reopening this because I'm unable to see what existing code will break if `binary_parameters` is enabled by default. I tried a few things and they didn't break:

1. Created a table with a `bytea` column and inserted random bytes into it. It behaved the same with and without `binary_parameters` enabled.
1. Created a database with `LATIN1` encoding and tried to insert text with Chinese characters. It failed both with and without `binary_parameters` enabled.

**Comment by johto** [comment]
> Reopening this because I'm unable to see what existing code will break if binary_parameters is enabled by default.

Try something like this:

```SQL
CREATE TABLE foo(a int);
```

```Go
db.Exec(`INSERT INTO foo VALUES ($1)`, []byte("1234"))
```

**Comment by cskr** [comment]
Thanks you, @johto.

Circling back to the original goal of the issue, can we not avoid waiting for response to `Parse`, without enabling binary encoding? Essentially, can we always use the protocol as in [sendBinaryModeQuery](https://github.com/lib/pq/blob/a8186bb1f92e6ce783019d6f2c511c985b4b746c/conn.go#L1491), but set all format codes to 0 [here](https://github.com/lib/pq/blob/a8186bb1f92e6ce783019d6f2c511c985b4b746c/conn.go#L1460). Will it break anything?

**Comment by cskr** [comment]
Closing this as pq relies on result for prepare to handle `bytea` and there is no way to avoid it without breaking compatiblity.
