### ISSUE TITLE
arrays are not properly escaped in ilike statements

### ISSUE THREAD

**Issue by ptravis** [lib/pq#642]
the following fails:
	_, err = db.Exec("select * from temp where 'a' ilike any($1::text[])", Array([]string{"\\"}))
with the error:
        conn_test.go:1637: pq: LIKE pattern must not end with escape character

for an example test:
 https://github.com/lib/pq/pull/641

**Comment by johto** [comment]
```Go
[]string{"\"}
```

I wouldn't have expected that to even compile: https://play.golang.org/p/XQ2ElBsYxn

Having said that, I'm not sure why you're expecting this to work.  Backslash is an escape character in LIKE:

```SQL
=# select 'a' like '\';
ERROR:  LIKE pattern must not end with escape character
```

**Comment by ptravis** [comment]
that was cut-n-paste issue in the browser, the code has two back slashes...

I was expecting the library to protect me from having to escape every member of the array I pass.  I see your point, but would it be possible to escape invalid escapes, e.g. if the \ is not followed by %|_ escape the \

**Comment by johto** [comment]
> I was expecting the library to protect me from having to escape every member of the array I pass. I see your point, but would it be possible to escape invalid escapes, e.g. if the \ is not followed by %|_ escape the \

That makes no sense.  The driver doesn't know you're doing a LIKE, nor should it.  It's up to you to escape the input correctly.

Also arrays are completely irrelevant here, you have the same problem if you do:

```SQL
SELECT * FROM foo WHERE bar LIKE $1
```

It's *not* the driver's job to try and guess which context you're in and escape the values for you.

**Comment by ptravis** [comment]
Ok - feel free to close
