### ISSUE TITLE
Is local passwordless (peer) authentication possible?

### ISSUE THREAD

**Issue by hectorj** [lib/pq#645]
Hi!

I may be missing something obvious (in which case I'll be very sorry), but I can't find how to connect to my DB using "peer" authentication with `pq`.

Here is my `pg_hba.conf` : 
```
local all root             peer
host  all all 127.0.0.1/32 md5
host  all all ::1/128      md5
```

Using `plsql`, logged in as `root`, I can do `psql -d postgres` and be successfully connected.

But I tried many DSNs for `pq` without success (`database=postgres`, `dbname=postgres sslmode=disable`, `postgres:///tmp/postgres?sslmode=disable`, `dbname=postgres sslmode=disable requirepeer=root`, and a few others).

If I don't include `sslmode=disable` I get `pq: SSL is not enabled on the server`, which is fine.

But then I get `pq: password authentication failed for user "root"` though I'm not trying to do a password authentication.

Any idea of what I'm doing wrong?

Thanks in advance.

**Comment by uhoh-itsmaciek** [comment]
Try adding `host=/tmp/postgres` (or wherever the socket file resides on your system) to the DSN. I haven't been able to get it to work with the URL syntax DSN; I'm not sure what's up there.

**Comment by hectorj** [comment]
`dbname=postgres host=/tmp` worked, thanks a lot!

Yeah, it's weird for the URL syntax. Not sure if it's a bug.
I'm gonna close this as the problem is solved for me. Feel free to reopen if you think the URL syntax is worth looking into.

Thanks again!

**Comment by uhoh-itsmaciek** [comment]
Well, I'm not sure about that. In the URL syntax for psql, you have to escape `/` as it's a special character:

```
maciek@mothra:/tmp$ psql postgres://%2frun%2fpostgresql
Pager usage is off.
Null display is "💩".
psql (9.6.3)
Type "help" for help.

maciek=# \q
````

but Go doesn't seem to like that syntax:

```
maciek@mothra:/tmp$ cat test.go 
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/lib/pq"
	"os"
)

func main() {
	conn, err := sql.Open("postgres", os.Args[1])
	if err != nil {
		panic(err)
	}
	if err := conn.Ping(); err != nil {
		panic(err)
	} else {
		fmt.Println("connected")
	}
}
maciek@mothra:/tmp$ go run test.go postgres://%2frun%2fpostgresql
panic: parse postgres://%2frun%2fpostgresql: invalid URL escape "%2f"

goroutine 1 [running]:
panic(0x6a6640, 0xc820014930)
	/home/maciek/code/go1.6/go/src/runtime/panic.go:464 +0x3e6
main.main()
	/tmp/test.go:16 +0xf8
exit status 2
```

the old connection string syntax works fine:

```
maciek@mothra:/tmp$ go run test.go host=/run/postgresql
connected
```

**Comment by cbandy** [comment]
There is a tangle of Go issues surrounding `net/url` encoding and parsing. Notably, they've [abandoned full RFC compatibility](https://github.com/golang/go/commit/83676d694b64205e80c042ca7cf61f7ad4de6c62).
