### ISSUE TITLE
DECIMAL (and probably NUMERIC) types Scanned as []uint8

### ISSUE THREAD

**Issue by shtrom** [lib/pq#648]
When `Scan()`ing a row containing records from a table with `DECIMAL` columns (and likely `NUMERIC`, too), the data is deserialised as an `[]uint8`.

Golang doesn't have an exact decimal type, but converting those PG types to some sort of inexact floating point type would be more practical.

Alternatively, perhaps an intermediate type could be created to return the data without losing its exactitude, so it can be further manipulated from the rest of the code (e.g., serialising to JSON).

**Comment by cbandy** [comment]
I'm not in front of a terminal right now, so I can't check myself...

Have you tried the following?
```go
var x float64
err := db.QueryRow(`select 3.14159::decimal`).Scan(&x)
```

Also, my intuition is that the following works:
```go
var x json.Number
err := db.QueryRow(`select 3.14159::decimal`).Scan(&x)
```

**Comment by shtrom** [comment]
Ok, your example kinda works, but it's not exactly my issue:
```go
var x float64
var y string
db.QueryRow(`select 3.14159::decimal, 'y'`).Scan(&x, &y)
fmt.Printf("%v %f %T; %v %s %T\n", x, x, x, y, y, y)
```
gives
```
3 3.000000 float64; y y string
```
It's missing the decimal part of the number, though.

However, if I want to write generic code that doesn't know the type of the columns in advance, I use arrays of `interface{}`, and that's where the issue appears:
```go
out := make([]interface{}, 2)
outptr := make([]interface{}, 2)
for i := range out {
    outptr[i] = &out[i]
}
db.QueryRow(`select 3.14159::decimal, 'y'`).Scan(outptr...)
fmt.Printf("%v %f %T; %v, %s %T\n",
    out[0], out[0], out[0],
    out[1], out[1], out[1],
)
```
In this case, the `decimal` is just mapped to an `[]uint8`
```
[51] [%!f(uint8=51)] []uint8; y, y string
```

(Note: just this morning, I was working with an old version of the library (69552e54d2a9d4c6a2438926a774930f7bc398ec), which did not seem to have any handling of the Data Types (the section was missing from the README), and I had the very same issue with `varchar`s being converted to `[]uint8`, rather than `string`; updating to the latest `master` fixed that issue).

**Comment by shtrom** [comment]
Ah, interesting. I was running this against RedShift. The first oddity vanishes when using a normal PostgreSQL.
```
3.14159 3.141590 float64; y y string
```

But my core problem persists.
```
[51 46 49 52 49 53 57] [%!f(uint8=51) %!f(uint8=46) %!f(uint8=49) %!f(uint8=52) %!f(uint8=49) %!f(uint8=53) %!f(uint8=57)] []uint8; [121], y []uint8
```

The `apd.Decimal` could be useful, but I think my issue is with the _default_ type that is `Scan` converts a `DECIMAL` to when given an `interface{}`: it goes for an `[]int8`, while I think a `floatXX` would a more immediately practical compromise.

Oddly enough, now that I'm hitting a PG server, the string is also back to an `[]int8` 🤔

**Comment by mjibson** [comment]
It's not safe to use a float64 type for a decimal because floats can't represent all decimals. For example, decimals support exponents much larger than floats, and the coefficients of floats, when converted to their base-2 representation, will change. It is trivial in go to convert a string to a float, so we are going to keep this behavior.
