### ISSUE TITLE
pq Error: could not find array type for data type text[]

### ISSUE THREAD

**Issue by psankar** [lib/pq#650]
I have a string that has a query and an []interface that has the parameters. The second and fourth parameters in the query expect an `[]TEXT` and so I have used both `pq.Array` as well as `ps.StringArray` but could not get the query to execute correctly.

```
q := `SELECT * FROM (
	SELECT WorkerID FROM ResumeConstraints WHERE ConstraintID = $1 AND  StringValue = ANY($2)
	INTERSECT
	SELECT WorkerID FROM ResumeConstraints WHERE ConstraintID = $3 AND  ArrayOfStringValues = ANY($4) ) AS Res1 LIMIT $5`
```

The value for Params which is what is used to execute as: `rows, err = s.db.Query(q, params...)` is as follows.

```
2017/08/24 19:02:13 DB.go:800: Params are:
2017/08/24 19:02:13 DB.go:801: [Str1 [Yes] Str2 [Breakfast Lunch] 4]
2017/08/24 19:02:13 DB.go:815: ERROR: DATABASE failure:  pq: could not find array type for data type text[]
```

If I have to map the params to the query placeholders, it will be like:
```
$1 = "Str1"
$2 = [Yes] 
$3= "Str2"
$4 = [Breakfast Lunch]
$5 = 4
```

Am I doing something wrong ? Is there anything that we should do to make this query work fine ? Thanks.

**Comment by johto** [comment]
```SQL
SELECT WorkerID FROM ResumeConstraints WHERE ConstraintID = $3 AND  ArrayOfStringValues = ANY($4)
```

You're doing  text[] = ANY (text[])  here, which makes no sense.  I'm guessing you want one of:

```SQL
ArrayOfStringValues = $4
-- or
ArrayOfStringValues && $4
-- or
ArrayOfStringValues @> $4
```

**Comment by psankar** [comment]
ah damn. I have somehow misunderstood my query. You are right, what I wanted was the `ArrayOfStringValues @> $4` variant only. (Rows containing any element in $4, as one of the values for the column ArrayOfStringValues) Sorry for the noise.

**Comment by psankar** [comment]
I realised why I have made this mistake. For an earlier query, where I had to check "AllOf" I used the above query and for "AnyOf", I used the ANY variant. I now realise that the mistake is in my query and not in the pq driver. Sorry for the noise.

```
if i.AggregationType == constraint.AllOf {
        q += fmt.Sprintf(" ArrayOfStringValues @> $%d ", pos)
	pos++
	params = append(params, pq.StringArray(i.StringArrayCriteria))
} else i.AggregationType == constraint.AnyOf {
	q += fmt.Sprintf(" ArrayOfStringValues = ANY($%d) ", pos)
	pos++
	params = append(params, pq.StringArray(i.StringArrayCriteria))
}
```

**Comment by brdacost** [comment]
Hi there, I actually had a similar problem, but using the ARRAY_PREPEND function. I created a test database and table as follows:

```
CREATE DATABASE local_tests;

CREATE TABLE tutorials(
	id INT PRIMARY KEY NOT NULL,	
	"name" VARCHAR(20),
	contacts TEXT[]		
);

-- inserting sample data
INSERT INTO tutorials VALUES(1, 'Test', '{"123","456"}'), (2, 'Test2', '{"456"}');

-- query for any rows containing value '123' -> returns only the row whose id = 1
SELECT *
FROM tutorials
WHERE '123' = ANY(contacts);

-- throws the error 
SELECT ARRAY_PREPEND(contacts, '0') AS extended_contacts
FROM tutorials
WHERE '123' = ANY(contacts);
```

As you can see the any() function is not the issue here, but apparently the text[] is not natively recognized as an array type in postgres (at least not by the prepend or append functions).

Any help would be very much appreciated.

**Comment by johto** [comment]
> -- throws the error 
> SELECT ARRAY_PREPEND(contacts, '0') AS extended_contacts
> FROM tutorials
> WHERE '123' = ANY(contacts);

This has nothing to do with this driver.  This is not a general postgres help forum.

Having said that, you have the arguments backwards.  You want `ARRAY_PREPEND('0', contacts)`.

**Comment by brdacost** [comment]
> > -- throws the error
> > SELECT ARRAY_PREPEND(contacts, '0') AS extended_contacts
> > FROM tutorials
> > WHERE '123' = ANY(contacts);
> 
> This has nothing to do with this driver. This is not a general postgres help forum.
> 
> Having said that, you have the arguments backwards. You want `ARRAY_PREPEND('0', contacts)`.

Sorry about that, I was searching for someone with the same issue and thought this would be an appropriate place for that. But you're right, that is a postgres issue only.

But your suggestion worked like a charm, thanks a lot!

**Comment by johto** [comment]
> But you're right, that is a postgres issue only.

Yeah.  I didn't mean to be rude, but if you can reproduce the issue by copy-pasting to psql, you ought to look a bit closer ;-)
