### ISSUE TITLE
Using INTERVAL

### ISSUE THREAD

**Issue by facundomedica** [lib/pq#656]
I want to use interval as this:

```sql
...transactions.timestamp > (NOW() - INTERVAL $4);
```

also tried:

```sql
...transactions.timestamp > (NOW() - INTERVAL $4::varchar);
```

The parameter I'm passing is a string that contains "10 days" or "1 hour" for example.

The error I'm getting is not very descriptive: `pq: syntax error at or near "$4"`

Am I doing something wrong here?

**Comment by johto** [comment]
> Am I doing something wrong here?

Yeah, you want `WHERE transactions.timestamp > now() - $4::interval`.

There's nothing special about the interval data type; the `typename '..'` syntax works with any type.  However, it only works when the type name is followed by a literal and not a parameter placeholder.

**Comment by facundomedica** [comment]
@johto worked great! Thanks! Closing.
