### ISSUE TITLE
Make megacheck pass (mostly) cleanly

### ISSUE THREAD

**Issue by ainar-g** [lib/pq#662]
In this issue I suggest additional changes, that will make [megacheck](https://github.com/dominikh/go-tools) pass mostly cleanly. I say "mostly" because there is SA1019 check, which raises an error when a deprecated type is used, and we need to use both `driver.Execer` and `driver.Queryer` for compatibility reasons. I've already made some changes in #661. The changes that I want to make are mostly simplifications, e.g.
```diff
-       var s sql.Scanner
-
-       s = Array(&[]bool{})
+       var s sql.Scanner = Array(&[]bool{})
```
and
```diff
-       err = boolSetting("binary_parameters", &cn.binaryParameters)
-       if err != nil {
-               return err
-       }
-       return nil
+       return boolSetting("binary_parameters", &cn.binaryParameters)
```
I can also do this to `.travis.yml`:
```diff
   - ./.travis.sh client_configure
-  - go get golang.org/x/tools/cmd/goimports
+  - go get golang.org/x/tools/cmd/goimports honnef.co/go/tools/cmd/megacheck
```
```diff
   - go vet ./...
+  # Ignore SA1019 in conn_test.go because we need compatibility with Go 1.5, so
+  # we have to use driver.Execer and driver.Queryer.
+  - megacheck -ignore 'github.com/lib/pq/conn_test.go:SA1019'  ./...
   - PQTEST_BINARY_PARAMETERS=no  go test -race -v ./...
```

What do you think?

**Comment by mjibson** [comment]
Yes, I like all of these changes.

**Comment by ainar-g** [comment]
@mjibson There is a possibility that an update to megacheck will break the build on a random PR(s), e.g. they might add a new check that finds new issues. The way to solve this situation is making a new commit solving the issue or disabling the check and rebasing the PR(s). We can prevent that if we checkout a specific revision of megacheck (the 2017.1 release), but that would require some additional typing.

Should I lock the version, or we are OK with occasional new findings?

Either way, I'm going to do this after #661 is merged.
