### ISSUE TITLE
Golint and Godoc issues

### ISSUE THREAD

**Issue by ainar-g** [lib/pq#669]
Both golint and godoc.org show some issues in packages' documentation. The linter mostly complains about "malformed" or missing doc comments, e.g. `notify.go:63:1: comment on exported function NewListenerConn should be of the form "NewListenerConn ..."`. It also complains about package `listen_example`'s name containing an underscore. Godoc is mostly fine, aside from the missing comments, but some code and lists are not aligned to the 80 char mark, and thus the scroll bars appears at https://godoc.org/github.com/lib/pq#pkg-constants. Thus, some proposals:

* Align all code and lists to the 80 char mark.

* Add missing documentation and fix documentation golint complains about.

* Move `listen_example` to `examples/listen`.

* Add a link to godoc.org to the README.

Adding golint to the Travis builds is doable, but I am not sure if it's worth it.

Thoughts?

**Comment by tamird** [comment]
Go for it. Please add golint to Travis.
