### ISSUE TITLE
Very slow execution of the query

### ISSUE THREAD

**Issue by mannol** [lib/pq#671]
The following query takes 10 seconds to execute on a very small dataset (1 row for each table).
```sql
SELECT users.username,users.name,blocks.score
FROM users
JOIN blocks
blocks.blocker = $1 AND blocks.blockee = users.uid AND blocks.score > $2
ORDER BY blocks.score ASC LIMIT 21;
```
Even tho EXPLAIN ANALYSE returns reasonable results:
```
Planning time: 0.341 ms
Execution time: 1.513 ms
```
When running the same query using psql everything is ok.

Both psql and lib-pq produce the same execution plan:
```
                                                    QUERY PLAN                                                    
------------------------------------------------------------------------------------------------------------------
 Limit  (cost=15.52..15.52 rows=1 width=18)
   ->  Remote Subquery Scan on all (dn1,dn2)  (cost=15.52..15.52 rows=1 width=18)
         ->  Limit  (cost=15.52..15.52 rows=1 width=18)
               ->  Sort  (cost=15.52..15.52 rows=1 width=18)
                     Sort Key: blocks.score
                     ->  Nested Loop  (cost=4.21..15.51 rows=1 width=18)
                           Join Filter: (users.uid = blocks.blockee)
                           ->  Remote Subquery Scan on all (dn1)  (cost=104.21..114.45 rows=3 width=16)
                                 Distribute results by H: blockee
                                 ->  Bitmap Heap Scan on blocks  (cost=4.21..14.39 rows=3 width=16)
                                       Recheck Cond: (blocker = 193)
                                       Filter: (score > 0)
                                       ->  Bitmap Index Scan on blocker_idx  (cost=0.00..4.21 rows=8 width=0)
                                             Index Cond: (blocker = 193)
                           ->  Materialize  (cost=100.00..101.08 rows=2 width=18)
                                 ->  Remote Subquery Scan on all (dn1,dn2)  (cost=100.00..101.07 rows=2 width=18)
                                       Distribute results by H: uid
                                       ->  Seq Scan on users  (cost=0.00..1.02 rows=2 width=18)

```
So the question is, why is lib-pq so slow with this query?

I'm using the latest lib-pq version from github and running Postgres-XL cluster.

**Comment by ainar-g** [comment]
Immediate questions are:
* Are $1 and $2 the same in both cases?
* Are there any inserts right before the select?
* Are you sure that psql's result is not due to cache?

**Comment by mannol** [comment]
@ainar-g 
- yes, they are exactly the same
- yes, there are inserts for both tables
- cache or not, we are talking about 10 seconds difference for a query that works on miniscule dataset (as said before, 1 row for each table)

**Comment by mannol** [comment]
I have observed that there are some factors affecting the execution of this query that are unrelated to lib/pq. It's probably related to GTM being confused due to deleting all entries from table right before inserting and selecting others. Closing as it doesn't happen in my other tests in which tables are not cleared and modified so quickly.
