### ISSUE TITLE
syntax error at or near "$1"

### ISSUE THREAD

**Issue by yurevich1** [lib/pq#672]
`res, err := psdb.Exec("DROP TABLE $1;", "Users" )`

This line sets err as `syntax error at or near "$1"`

Simple "DROP TABLE Users" works.

Why?

If this feature is not supported for table names how can I escape the string using this library?

**Comment by mjibson** [comment]
Postgres doesn't support placeholders for `drop table`. (Most databases don't.) This isn't a lib/pq bug.
