### ISSUE TITLE
Querying time field with 24:00 value silently fails

### ISSUE THREAD

**Issue by Jukurrpa** [lib/pq#689]
I have a table with `TIME WITHOUT TIME ZONE` fields. For some reason, when querying on it I don't get any results if there are values of `24:00:00`.

Here's the code I tested with:
```
// t is TIME WITHOUT TIME ZONE column
rows, err := db.Query(`SELECT t FROM time_test`)

if err != nil {
	log.Errorf("SQL Error: ", err.Error())
	return
}

defer rows.Close()

var t time.Time

for rows.Next() {
	err := rows.Scan(&t)

	if err != nil {
		log.Errorf("Scan error: %s", err.Error())
		continue
	}

	log.Debugf("%v", t)
}
```

When the table contains only one entry with `23:00:00` as value, I get the result. If I insert a value of `24:00:00` (valid per PSQL), I don't get any results (not even the `23:00:00` one) and no error happens when querying or scanning.

Is this a bug or am I missing something?

**Comment by cbandy** [comment]
Check `rows.Err()` after the loop.

**Comment by Jukurrpa** [comment]
Never realized rows.Err() had to be checked after looping on it, thanks.
