### ISSUE TITLE
Support SQL placeholder parameters inside array literals

### ISSUE THREAD

**Issue by myartsev** [lib/pq#691]
When inside an array literal, SQL placeholder parameters do not get evaluated and are passed as-is to the query.

```
v := 1
_, err := db.Exec("SELECT * FROM foo WHERE an_array @> '{$1}';", v)
```
_pq: invalid input syntax for integer: "$1"_

I end up wrapping the query with fmt to make it work.
```
v := 1
_, err := db.Exec(fmt.Sprintf("SELECT * FROM foo WHERE an_array @> '{%d}';", v))
```

**Comment by myartsev** [comment]
Is this a limitation of PostreSQL itself or in the driver?

**Comment by rogerhub** [comment]
Just a shot in the dark... but have you tried `db.Exec("SELECT * FROM foo WHERE an_array @> $1", []int{v})`?

**Comment by cbandy** [comment]
PostgreSQL. It does not look inside the literal value (inside the single quotes) for placeholders.

You can use `Array` to send an array value:

```go
db.Exec(`SELECT ... WHERE an_array @> $1`, pq.Array([]int{v}))
```

**Comment by myartsev** [comment]
Good to know!
