### ISSUE TITLE
error with Exec on create database

### ISSUE THREAD

**Issue by adamdecaf** [lib/pq#694]
Are only certain statements prepared? I'm going a bit crazy wondering why DB.Exec (and DB.Query) aren't preparing the following statement as I'd expect. 

From go's stdlib it looks like `DB.Exec` can take placeholders: https://golang.org/pkg/database/sql/#DB.Exec

I'm running postgres in a docker image:
```
docker run -p 5432:5432 -it postgres
```

```go
package main

import (
	"fmt"
	"database/sql"
	_ "github.com/lib/pq"
)

func main() {
	conninfo := "user=postgres host=127.0.0.1 sslmode=disable"
	db, _ := sql.Open("postgres", conninfo)
	_, err := db.Exec(`create database $1`, "foo")
	// _, err := db.Exec(`create database ?`, "foo") // doesn't work
	// _, err := db.Exec(fmt.Sprintf(`create database %s`, "foo")) // works 
	fmt.Println(err)
}
```
Output:

```
$ go run /tmp/db.go 
pq: syntax error at or near "$1"
```

**Comment by adamdecaf** [comment]
Looking through a bunch of code on github this seems to be a common problem that people just `fmt.Sprintf` their way around.

Example: https://github.com/dsblox/pim/blob/e27dc2aaa4f1f322c109f54bdeecdd61fdfbc6ad/taskmapperpg.go#L105

Search: https://github.com/search?p=1&q=language%3Ago+%22db.Exec%22+%22create+database%22&type=Code&utf8=%E2%9C%93

**Comment by mjibson** [comment]
This is a limitation of postgres, not lib/pq. Only some types of statements support parameters. Generally anything that modifies schemas doesn't support them.

**Comment by adamdecaf** [comment]
Oh. That's no good. Do you have any advice for how to build that query? I wrapped a regex around the name for now.

**Comment by shoukry1** [comment]
concat the string itself instead...
`db.Exec("create database " + "foo")`

**Comment by cbandy** [comment]
When the name is input (not hard-coded) remember to use [`pq.QuoteIdentifier`](https://godoc.org/github.com/lib/pq#QuoteIdentifier).
