### ISSUE TITLE
Listener.resync can spin forever due to race condition

### ISSUE THREAD

**Issue by lmb** [lib/pq#699]
It is possible for both resync and resync.func1 to block indefinitely:

- Listener.connect creates a new connection, and schedules ListenerConn.listenerConnMain
- listenerConnMain detects an error and closes l.notificationChan
- connect calls resync
- resync schedules resync.func1, which is a closure over notificationChan. However func1 is not immediately run
- resync detects that notificationChan is closed, and sets it to nil (race happens here)
- resync now waits on doneChan
- func1 is scheduled and cn.Listen returns false, error
- func1 attemps to range over notificationChan, which is nil by now
- range over a nil chan blocks
- doneChan is never written to
- both resync and resync.func1 are deadlocked

**Comment by johto** [comment]
This looks correct to me.

**Comment by lmb** [comment]
Is there anything you want me to change before merging this?

**Comment by johto** [comment]
> Is there anything you want me to change before merging this?

I was waiting for someone else to push this, but I guess I can push it myself since this is mostly my code anyway.  I'm giving it until the end of the day though, in case someone else wants to review it.
