### ISSUE TITLE
::bool creates 't' or 'f' instead of true or false, which Postgres expects, producing error.

### ISSUE THREAD

**Issue by votezilla** [lib/pq#707]
::bool in a query should produces correct true or false values in the generated SQL, and work correctly (like ::bigint does).  It current creates 't' or 'f' values, which are not boolean values and produces errors when used as a boolean value in a Postgres SQL statement.

**Comment by johto** [comment]
I have no idea what you think the problem is.

Can you show us code that demonstrates the problem you're experiencing?

**Comment by votezilla** [comment]
Never mind, everything works okay.  I was having a different bug, and getting confused by a different Postgres logged error.
