### ISSUE TITLE
Please modify driver's registration logic.

### ISSUE THREAD

**Issue by awly** [lib/pq#71]
Please modify driver's registration logic.
If I want to work with database/sql package only (which in my opinion is the "better" way) currently I have to add 
    import  _ "github.com/bmizerany/pq"
to trigger pq's [init()](https://github.com/bmizerany/pq/blob/master/conn.go#L32) to call the driver registration on line 33.

I believe that _ imports are in general  "bad" as a design decision, and using standard go's lib's sql package is the preferred way to work with sql databases.

At the very least, please put a note in the readme to avoid confusion caused by the lack of (exported) Driver.

Proposed solutions:
- export the driver, remove sql.Register from init()
- add explicit func Register(), remove sql.Register from init()
- leave as is, but document somewhere

**Comment by gabsn** [comment]
I am currently a wrapper for database/sql and like @awly said, you should at least export the driver, so that we can wrap it.

**Comment by tamird** [comment]
@gabsn that's already done https://github.com/lib/pq/pull/585.
