### ISSUE TITLE
What would it take to support the Interval Type in lib/pq?

### ISSUE THREAD

**Issue by lrosenman** [lib/pq#710]
I have a go library for the AmbientWeather.net API, and I write those responses to a PostgreSQL database.  One of the fields returned is time.Duration which I was putting into an interval field.

In order to satisfy pq, I had to fmt.Sprintf("%v",time.DurationField).  

I was wondering if there was any objection to my trying to hack/add support for interval/duration support into this library.

**Comment by cbandy** [comment]
They aren't exactly compatible. See discussion in #78.

To control how `sql.DB` interprets a type, implement the [`driver.Valuer` interface](https://golang.org/pkg/database/sql/driver/#Valuer).

**Comment by lrosenman** [comment]
Thanks.  I hadn't done much research, and in my case, I'm just dealing with milliseconds from a response time call (see https://github.com/lrosenman/ambient in the API*.ResponseTime fields). 

Thanks!
