### ISSUE TITLE
function st_geomfromtext(unknown) does not exist

### ISSUE THREAD

**Issue by maym86** [lib/pq#712]
When I try the following code I get an error:

```

pos := "'POINTZ(-109.366424 -27.121192 12.1)'"
cmd = `INSERT INTO table (id, ts, pos, type, lat_s, lon_s, height_s, track_id) VALUES ($1, to_timestamp($2::double precision / 1000), ST_GeomFromText($3), $4, $5, $6, $7, $8);`

res, err = signEstimateService.postgresSession.Exec(cmd, deviceID, ts, pos, signType, latSigma, lonSigma, heightSigma, trackingID)
```

> **pq: function st_geomfromtext(unknown) does not exist**

This works when I do it directly using sql as follows:

```
INSERT INTO table (id, ts, pos, type, lat_s, lon_s, height_s, track_id)
					VALUES ('TEST', to_timestamp((1517986955612)::double precision / 1000), 
					ST_GeomFromText('POINTZ(-109.366424 -27.121192 12.1)'), 2, 0.03, 0.03, 0.03, 0);
```

Am I doing something wrong or is the function somehow not supported?

**Comment by johto** [comment]
> Am I doing something wrong or is the function somehow not supported?

There's nothing special about this particular function (or any function, for that matter, as far as the driver is concerned).  My guess is that you're connected to a different database or your effective search_path is different when you're trying it "manually".

**Comment by maym86** [comment]
You're right. I specifically added the schema to the go insert statement and it works. Thanks
