### ISSUE TITLE
uint64 values with high bit set are not supported

### ISSUE THREAD

**Issue by paddycarver** [lib/pq#72]
When trying to use [noeq](/noeq/noeq) as an ID generator and pq as a data persistence layer, it's possible to generate an ID that can't be stored. PostgreSQL only supports bigint (int64), not uint64. From what I understand, database/sql converts uint64s to int64s transparently, but throws an error when the uint64 is above the limit of int64, effectively wasting half the space in the uint64:

```
sql: converting argument #1's type: uint64 values with high bit set are not supported
```

Seeing as @bmizerany worked on both the ID generator and the database driver, I figured he may have a solution, workaround, or suggestion for using uint64 IDs with pq. Any ideas?

**Comment by azr** [comment]
Hello there, so I just got the same error; the thing is I was trying to store that uint64 into a `NUMERIC(20, 0)` is there a way to avoid that error from getting triggered ?
