### ISSUE TITLE
Further support for arrays in queries

### ISSUE THREAD

**Issue by ralphking** [lib/pq#721]
pq.Array() does not return a value that can be used as an array in all situations.

Using `pq.Array([]int{1,2})` as `$1` for these examples.

This works as expected:
```
SELECT * from some_table WHERE some_column = ANY($1)
``` 

This does not:
```
SELECT * from some_table WHERE some_column IN($1)
``` 

This does not:
```
SELECT * from some_table WHERE some_column BETWEEN $1[1] AND $1[2]
``` 

Postgres complains that the type isn't actually an array, which is true.

There are plenty of ways around the issue, but is this something that anyone else would want support for?

**Comment by cbandy** [comment]
Have you tried these queries outside of lib/pq? It seems to me none of these are supported by _PostgreSQL_.

```
psql=> SELECT * FROM generate_series(1,5) t(c) WHERE c = IN(ARRAY[1,2]);
ERROR:  syntax error at or near "IN"
LINE 1: SELECT * FROM generate_series(1,5) t(c) WHERE c = IN(ARRAY[1...
                                                          ^

psql=> SELECT * FROM generate_series(1,5) t(c) WHERE c = IN('{1,2}');
ERROR:  syntax error at or near "IN"
LINE 1: SELECT * FROM generate_series(1,5) t(c) WHERE c = IN('{1,2}'...
                                                          ^
```
```
psql=> SELECT * FROM generate_series(1,5) t(c) WHERE c BETWEEN ARRAY[1,2][1] AND ARRAY[1,2][2];
ERROR:  syntax error at or near "["
LINE 1: ...nerate_series(1,5) t(c) WHERE c BETWEEN ARRAY[1,2][1] AND AR...
                                                             ^

psql=> SELECT * FROM generate_series(1,5) t(c) WHERE c BETWEEN '{1,2}'[1] AND '{1,2}'[2];
ERROR:  syntax error at or near "["
LINE 1: ... generate_series(1,5) t(c) WHERE c BETWEEN '{1,2}'[1] AND '{...
                                                             ^
```

**Comment by ralphking** [comment]
Apologies, you're correct on the first. Note you don't use an `=` with `IN` though which is what your syntax error was.

The important one though for me is the second, your example works if you include parentheses:

```
SELECT * FROM generate_series(1,5) t(c) WHERE c BETWEEN (ARRAY[1,2])[1] AND (ARRAY[1,2])[2];
```

I guess the question is, what is the best way to do this without having to split the arguments up first?

**Comment by cbandy** [comment]
Indeed!

```
psql=> SELECT * FROM generate_series(1,5) t(c) WHERE c IN(ARRAY[1,2]);
ERROR:  operator does not exist: integer = integer[]
LINE 1: SELECT * FROM generate_series(1,5) t(c) WHERE c IN(ARRAY[1,2...
                                                        ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

psql=> SELECT * FROM generate_series(1,5) t(c) WHERE c IN('{1,2}');
ERROR:  invalid input syntax for integer: "{1,2}"
LINE 1: SELECT * FROM generate_series(1,5) t(c) WHERE c IN('{1,2}');
                                                           ^
```

```
psql=> SELECT * FROM generate_series(1,5) t(c) WHERE c BETWEEN (ARRAY[1,2])[1] AND (ARRAY[1,2])[2];
 c 
---
 1
 2
(2 rows)

psql=> SELECT * FROM generate_series(1,5) t(c) WHERE c BETWEEN ('{1,2}')[1] AND ('{1,2}')[2];
ERROR:  cannot subscript type unknown because it is not an array
```

**Comment by cbandy** [comment]
> I guess the question is, what is the best way to do this without having to split the arguments up first?

Add explicit type casts. There's a tip in the documentation for [`PQexecParams`][] with the same advice.

```sql
SELECT * FROM generate_series(1,5) t(c) WHERE c BETWEEN ($1::int[])[1] AND ($1::int[])[2];
```

> Or at least, PSQL doesn't think the value returned from pq.Array is actually an array, which might cause issues in other places.

This is a limitation of the PostgreSQL wire protocol. Using parameters _effectively_ involves calling [`PREPARE`][] then `EXECUTE`. During the preparation, lib/pq doesn't send any type information because, for a long time, that wasn't possible with database/sql. This may have changed with the addition of [driver.NamedValueChecker][] in Go 1.9.

[driver.NamedValueChecker]: https://golang.org/pkg/database/sql/driver/#NamedValueChecker
[`PQexecParams`]: https://www.postgresql.org/docs/current/static/libpq-exec.html#LIBPQ-PQEXECPARAMS
[`PREPARE`]: https://www.postgresql.org/docs/current/static/sql-prepare.html

**Comment by ralphking** [comment]
Thanks!
