### ISSUE TITLE
Postgres driver does not connect over an exported docker port on 'localhost', it works ok on 127.0.0.1 or exposed service addresses. 

### ISSUE THREAD

**Issue by phiroict** [lib/pq#727]
Issue (which is a bit of an edge case but raising it anyway for your discretion ) , after calling Open on a database it returns without an error and a database object when connecting over one of the exposed docker interfaces (localhost). Each and every next call to the database connection fails by hanging. No errors are ever raised or thrown. 
If you enter invalid credentials it reacts the same so it would appear an invalid db object is returned. 

Now, the database runs as an container with exposed port. In this case running on a local swarm: 
The database can be reached over localhost (jdbc connection works fine here) and the docker interface (In this case 172.17.0.1 but that is dynamic)  On 172.17.0.1 it works fine, also on 127.0.0.1 but not on 'localhost'. 

Expected: Normal function after a non error Open call on both exposed ip addresses. Or at least an exception/ set error object when connection fails. 
 
Details: 
Golang: go version go1.10 linux/amd64
OS : Linux ubuntu 4.15.0-12-generic #13-Ubuntu SMP Thu Mar 8 06:24:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 18.04, gnome 3.26)
Postgres lib: 88edab0803230a3898347e77b474f8c1820a1f20  (github.com/lib/pq)
Postgres db 10.3 from docker container: postgres:10.3-alpine, was connectable with the same credentials from jdbc. 
Build from ;
```
# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:10.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
 
```
Create tables: 
```
create database golang_test;

create table "NAME"
(
	"ID" serial not null
		constraint "NAME_ID"
			primary key
		constraint "NAME_ID_fkey"
			references "ADDRESS",
	"FIRST_NAME" text not null,
	"LAST_NAME" text not null,
	"ADDRESS_ID" integer not null
)
;
INSERT INTO public."NAME" ("ID", "FIRST_NAME", "LAST_NAME", "ADDRESS_ID") VALUES (1, 'Jan', 'Pieterse', 1);

create table "ADDRESS"
(
	"ID" serial not null
		constraint "ADDRESS_ID"
			primary key,
	"STREET" varchar not null,
	"SUBURB" varchar not null,
	"CITY" varchar not null,
	"COUNTRY" varchar not null,
	"POSTCODE" char(12) not null
)
;

INSERT INTO public."ADDRESS" ("ID", "STREET", "SUBURB", "CITY", "COUNTRY", "POSTCODE") VALUES (1, '220 Petrov Place', 'Bayview', 'Sheffield', 'GB', 'AB1234X');

```
The SQL statement in the example would work.
Example project: 
```
package db

import (
	"fmt"
	"database/sql"
)

type PersonData struct {
	Id int
	FirstName string
	LastName string
	Street string
}

// Template data for the output page
type PageData struct {
	Title   string
	Message string
	Persons []PersonData
}



func Main(){
	var data *PageData
	data = new(PageData)
        // "localhost" fails, "127.0.0.1" and "172.17.0.1" works fine.
	dbinfo := fmt.Sprintf("host=localhost user=%s password=%s dbname=%s sslmode=disable port=5432",
		"postgres", "example", "golang_test")
	db,err := sql.Open("postgres", dbinfo)    // Successful whatever credentials
	_, err = db.Exec("BEGIN")                      // Each next call with db hangs. 

	if err == nil {
		rows, rowError := db.Query("SELECT n.\"ID\",n.\"FIRST_NAME\", n.\"LAST_NAME\", a.\"STREET\" FROM \"NAME\" n JOIN \"ADDRESS\" a ON n.\"ADDRESS_ID\"=a.\"ID\"")
		if rowError != nil {
			fmt.Printf("Error in retrieving rows : %s", rowError)
			return
		}
		for rows.Next(){
			var uid int
			var firstName string
			var lastName string
			var street string
			rows.Scan(&uid, &firstName, &lastName,&street)
			var pd = new(PersonData)
			pd.Id = uid
			pd.FirstName = firstName
			pd.LastName = lastName
			pd.Street = street
			data.Persons = append(data.Persons, *pd)
		}
	}
	db.Exec("COMMIT")
}
```

**Comment by cbandy** [comment]
As described in the docs, [`sql.Open`][] doesn't actually connect to the database. I expect you'll experience a similar hang when you call `Ping`.

I think you've stated that IP addresses work fine, but domain names do not. This package delegates completely to [`net.Dial`][] and [`net.DialTimeout`][] for name resolution. What happens when you call `net.LookupHost("localhost")` in your environment?

[`net.Dial`]: https://golang.org/pkg/net/#Dial
[`net.DialTimeout`]: https://golang.org/pkg/net/#DialTimeout
[`sql.Open`]: https://golang.org/pkg/database/sql/#Open

**Comment by phiroict** [comment]
Thanks for the tip @cbandy, working this this I found this. The docker swarm service-stack database I use seem to be the cause of the issue: 

# Checking localhost
```net.LookupHost("localhost")```  returns ```[::1 127.0.0.1]``` so with arr[1] passed to the connection string it works fine (As would be expected). 

# IPv4 vs IPv6
Now the first ip address returned from the call is the ipv6 address ```::1```. So when running with arr[0] it hangs in the same way...   Looks like the `localhost` is resolved to the first value it finds which happens to be an ipv6 address. My Postgres container does not listen on ipv6 so that is why it fails.

# Docker service issue
The hanging seems to be caused by docker in this case: 

```Quote: One additional thing, when a service has a port exposed then that port is accessible via IPv4 but a connection via IPv6 connects as docker is listening to that port but then hangs as it cannot connect to the underlying container as that's not listening on IPv6```
 (https://github.com/moby/moby/issues/24379)
# Conclusion
This lib can't do much about another component hanging so this bug can be closed, but it may remain here to guide others where to look when it fails.
