### ISSUE TITLE
Commit on broken transaction hangs

### ISSUE THREAD

**Issue by stub42** [lib/pq#731]
If you attempt to Commit a broken transaction, the Commit call hangs, blocking indefinitely. If the transaction was opened with a context, the context cancellation is ignored.

This is easy to accidentally reproduce by forgetting to check the error returned when executing an SQL statement.

```go
package main

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	_ "github.com/lib/pq"
)

func hang() error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	conn, err := sql.Open("postgres", "")
	if err != nil {
		return err
	}

	tx, err := conn.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	const q = `BROKEN SQL TO FAIL`
	_, err = tx.ExecContext(ctx, q)
	if err == nil {
		return errors.New("failed to break transaction!")
	}

	fmt.Printf("Attempting to commit broken transaction\n")

	commitCh := make(chan error, 1)
	go func() {
		commitCh <- tx.Commit()
	}()

	select {
	case err := <-commitCh:
		return err
	case <-time.After(10 * time.Second):
		fmt.Printf("Commit has hung. ctx.Err()==%v\n", ctx.Err())
	}

	return <-commitCh
}

func main() {
	err := hang()
	fmt.Printf("hang returned %v\n", err)
}
```

**Comment by timbunce** [comment]
I've encountered, but never diagnosed, behaviour like this. Thanks.

**Comment by itizir** [comment]
Also encountered this, it's a bit annoying indeed.

The reason is that Commit calls Rollback in that case and it results in two calls to the connection's `txnFinish` function, which may only be called once the way it's set up at the moment.

Suggesting a fix here: https://github.com/lib/pq/pull/829

**Comment by markwaddle** [comment]
this is a problem for me. is there a way to ask the transaction if it is broken?

**Comment by aschade92** [comment]
Also having the same issue. It causes requests to hang indefinitely and breaks error handling.
