### ISSUE TITLE
scanning to time.Time is not implemented

### ISSUE THREAD

**Issue by mholt** [lib/pq#738]
Hi -- it seems that it is not possible to store `time.Time` values into TIME or TIMESTAMP fields, despite documentation to the contrary. This is my first time using this package so I could be wrong, but:

```
sql: Scan error on column index 0: pq: parsing array element index 0: pq: scanning to time.Time is not implemented; only sql.Scanner
```

This is the error when scanning a `TIME[]` or `TIMESTAMP[]` field into a `[]time.Time` struct field using code like this:

```go
rows, err := db.Query(`SELECT times FROM sample`)
if err != nil {
	return nil, err // no error here
}
for rows.Next() {
	var s struct {
		ListOfTimes []time.Time
	}
	err := rows.Scan(pq.Array(&s.ListOfTimes))
	if err != nil {
		return nil, err // error here
	}
}
```

Am I doing it wrong? Or is this in fact a bug (as far as I can tell, time.Time is supposed to be supported).

**Comment by shawnsmithdev** [comment]
This may have to do with the arrays, as I know something like this works as expected.

```go
var stmt
// stmt is previously prepared statement
// taking two arguments ('?') and returning a (TIMESTAMP, VARCHAR) row.

// Values to store results from the query
var statDatetime time.Time
var stat string

// Scan values into the values
err = stmt.QueryRow(prepStmtArg1, prepStmtArg2).Scan(&statDatetime, &stat)
```

**Comment by mholt** [comment]
Ah, you know, it's not obvious, but when scanning arrays, it seems you have to do something like this:

```
var times []pq.NullTime
for rows.Next() {
	err := rows.Scan(pq.Array(&times))
	if err != nil {
		return nil, err // no error now
	}
}
s.ListOfTimes := make([]time.Time, len(times))
for i, t := range times {
	if !t.Valid {
		continue
	}
	s.ListOfTimes[i] = t.Time
}
```

It's ugly, but it does the job. Maybe there is a better way. Same thing has to be done for other types like string and int but using `sql.NullString` and `sql.NullInt64` types, respectively.

Doesn't seem to be a bug in this package after all -- but maybe clarifying the docs would be useful.

**Comment by dhui** [comment]
@mholt Were you able to get `[]pq.NullTime` working?

In my Postgres DB/table, I have a row with a timestamp array with non-null (and valid) timestamps. However, when the row is scanned w/ `[]pq.NullTime`, the `NullTime` has `Valid` as false.

Looking at the `NullTime.Scan()` implementation, it looks like the cast to `time.Time` is failing since the underlying type is a `[]uint8` which is the unparsed timestamp string.

**Comment by dhui** [comment]
This issue (https://github.com/lib/pq/issues/536) seems to be tracking support of time.Time in arrays
I have an implementation using custom types here: https://github.com/lib/pq/issues/536#issuecomment-397849980
