### ISSUE TITLE
Support for $HOME/.pgpass

### ISSUE THREAD

**Issue by freeekanayaka** [lib/pq#75]
See:

http://www.postgresql.org/docs/9.1/static/libpq-pgpass.html

I see there's a comment in conn.go:

		// skip PGPASSFILE, PGSERVICE, PGSERVICEFILE,
		// PGREALM

so I take that it was kind of planned to support it?

Thanks.

**Comment by petere** [comment]
How is one supposed to supply passwords other than by hardcoding them into the code then?

**Comment by johto** [comment]
> How is one supposed to supply passwords other than by hardcoding them into the code then?

You can still load one from a file and add it to the connection string yourself.  Or load the entire connection string from a file.  Or even use PGPASSWORD (with caveats, obviously).

But I'd be glad to review a patch adding support for .pgpass.

**Comment by petere** [comment]
The connection string shows up in `ps` output.

**Comment by fdr** [comment]
What do you mean? Only if the program using the driver reads connection information directly out of argv, which is not a concern of a driver like this one...

**Comment by petere** [comment]
But then I have to build a configuration file mechanism into even the most trivial program using this driver.

**Comment by cbandy** [comment]
> But then I have to build a configuration file mechanism into even the most trivial program using this driver.


You could build it once and submit it as a pull request here.

**Comment by freeekanayaka** [comment]
Adding those few environment variables should be less complex than adding code for handing a config file. More importantly, each application/consumer will typically want control on its own config file format, so it doesn't feel like a great idea to me.

My 2c.

**Comment by GeertJohan** [comment]
I'm not sure if this package already depends on cgo, but to retrieve the user's homedir location while avoiding the need of cgo use https://github.com/mitchellh/go-homedir

**Comment by johto** [comment]
> More importantly, each application/consumer will typically want control on its own config file format, so it doesn't feel like a great idea to me.

.pgpass is quite standard in the libpq land, so supporting it would be a good idea.  The problem just seems to be that nobody's willing to do the work.

**Comment by fazalmajid** [comment]
I implemented .pgpass and PGPASSFILE support (see commit above). I did not implement Windows pgpass.conf support as I don't have a machine to test on.

I unit-tested manually but I am not sure how to write an automated unit test for this, as the unit tests for in conn_test.go seem to assume the DB is configured in trust mode. @fdr: any guidance? Would you accept a pull request?

**Comment by tg** [comment]
@fazalmajid I'm not part of lib/pq team, but made a package for handling pgpass files myself (https://github.com/tg/pgpass) and would like to give you some feedback here – I believe the proper unit test would be to provide a pgpass file with a few corner cases and make sure the intended password is propagated to connection options (no need to establish the actual connection with database).

Speaking of corner cases, you should allow for colons in all pgpass fields (e.g. username), hence simple `strings.SplitN` won't really cut it. Escaped colons `\:` don't take part in the split, so the safest option is probably to provide your own line parser.

**Comment by johto** [comment]
> @fazalmajid I'm not part of lib/pq team, but made a package for handling pgpass files myself (https://github.com/tg/pgpass)

It's a bit saddening to know that this exists, but hasn't been contributed to this project.

> and would like to give you some feedback here

I didn't look at the code, but the feedback was sound.

**Comment by fazalmajid** [comment]
Yep, I am implementing proper escape handling in the parser, and unit tests.

**Comment by fazalmajid** [comment]
@tg, this may not be relevant for your pgpass library, but it doesn't seem to handle the special case of "localhost" correctly (field 1 == "localhost" should also match the empty string and UNIX socket host strings, e.g. host=/tmp).

**Comment by tg** [comment]
@fazalmajid thanks for pointing this out, never needed it indeed, but definitely should have been implemented.

**Comment by ajvb** [comment]
Shouldn't this be closed with the merging of https://github.com/lib/pq/pull/402 ?

**Comment by uhoh-itsmaciek** [comment]
I think so, yes. Thanks.
