### ISSUE TITLE
syntax error at or near argument for non-trivial WHERE condition 

### ISSUE THREAD

**Issue by joshkendrick** [lib/pq#764]
Hello!

I've run into an issue when trying to do some queries out of our Postgres database. This isn't a huge bug, there are a few ways to work around something like this for now, but wanted to mention it.

We have a query like:
```
rows, err := db.Query(`SELECT id, action, data, EXTRACT(EPOCH FROM created) :: bigint as created FROM commands WHERE action = $1 AND created > (NOW() AT TIME ZONE 'UTC') - INTERVAL $2 HOUR ORDER BY created DESC`, action, interval)
```
action is a `string`, interval is an `int`

this results in:
`ERRO[0002] pq: syntax error at or near "$2"`

And we cannot figure out what's going on.

I've tried a few different things; passing interval in as a string (`"100"`), wrapping (NOW... HOUR in parentheses, wrapping $2 in `""`, wrapping $2 in single quotes `''`, having the whole right side of the condition swapped in instead of just the hour value, .... other things. Can't seem to figure out what's going on.

FWIW, the query by itself does work:
```
SELECT id, action, data, EXTRACT(EPOCH FROM created) :: bigint as created FROM commands WHERE action = 'v1/ACTION' AND created > (NOW() AT TIME ZONE 'UTC') - INTERVAL '100' HOUR ORDER BY created DESC
```

An example table to test the query against:
```
CREATE TABLE commands (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    action      varchar(255) NOT NULL,
    data        bytea,
    created     timestamp
);
```

**Comment by johto** [comment]
This is a duplicate of #656

**Comment by joshkendrick** [comment]
ah, my mistake. i will try that fix and close this.

thanks!

**Comment by joshkendrick** [comment]
FWIW, i worked around it with this:
```
intervalAgo := time.Now().UTC().Add(-interval)

rows, err := db.db.Query(`... sql statement...`, pq.FormatTimestamp(intervalAgo))
```

**Comment by johto** [comment]
$2 * interval '1 hour'  might be a better option in this case.
