### ISSUE TITLE
No way to see an Insert error from QueryRow()

### ISSUE THREAD

**Issue by chris-baynes** [lib/pq#77]
I want to make an insert into a table with constraints. I also want to get the inserted id value if successful. The problem is if QueryRow() with an INSERT...RETURNING fails, then the error is a rather unhelpful `no rows in result set`.

The error I want would be something like: 
`duplicate key violates unique constraint "user_email_unique"` 
which is the error that's returned by Exec() but then I don't get the last inserted id if everything goes well.

**Comment by yudinRazDvaTri** [comment]
I've just faced the same problem. Solution described here https://gist.github.com/chris-baynes/5361728 is nice, but currently I'm trying to write SQL-transaction with RETURNING query and I'm stuck with it. 
This is an example of SQL-transactions which I tried to use https://pseudomuto.com/2018/01/clean-sql-transactions-in-golang/ and an Exec() method was used there. So same story, but my knowledge doesn't allow me to implement something like in the first link. And I'm looking for help, please.
