### ISSUE TITLE
Support custom encode function or register custom types

### ISSUE THREAD

**Issue by onwsk8r** [lib/pq#770]
**Short version**: I have a custom type that extends time.Time (github.com/onwsk8r/gotime - it's about half done) that I'd like to use with lib/pq

**Example use case**:
I'm getting JSON from an API and storing the results in Postgres. The JSON contains an ISO-8601-compatible date, but unfortunately since it does not satisfy the _complete_ ISO-8601, Time.UnmarshalJSON() freaks out, so I made a type that embeds time.Time and has a slightly more scrupulous parser. However, I can't use my `gotime.Time` with this library, so I have to make an intermediate type that embeds the real type and overrides the Date property, which is a real pain.

**So what's the ask**?
It looks like the `encode` function in encode.go is what's making my program choke. If there were something like
```
var EncodeFunction = encode

func encode()...
```
I could C+P the function body to my own program and add the line that I need.

However, it would be much cooler to have a way to register a custom type- maybe something like the pcap library does for registering custom layer types.

**Comment by rogerhub** [comment]
Can you use the [driver.Valuer](https://golang.org/pkg/database/sql/driver/#Valuer) interface to do this?

**Comment by onwsk8r** [comment]
Hey, it worked! Thank you for the heads up. Go just gets cooler every day! :)
