### ISSUE TITLE
Nullable() Scan

### ISSUE THREAD

**Issue by tarekbadrshalaan** [lib/pq#803]
I have an issue when I tried to scan tables (columns,types)
``` 
for _, col := range cols {
  nullable, ok := col.Nullable()
  if !ok {
	fmt.Println("Postgres driver does not support Nullable")
  }
...
```
Any Help ...??

**Comment by andriikushch** [comment]
Hi @tarekbadrshalaan , is this still valid question for you? If yes, please provide a complete example I will try to help you. Otherwise let's close this issue.

Thank you in advance!

**Comment by tarekbadrshalaan** [comment]
thanks @andriikushch for your replay.
what I remember that: the Postgres driver for golang does not support **Nullable** columns.
I might be wrong it has been 6 month.

**Comment by andriikushch** [comment]
You are welcome @tarekbadrshalaan ! Seems that feature still is not there, I will check it more precisely.

**Comment by andriikushch** [comment]
Hi @tarekbadrshalaan ,

It seems that the current wire protocol does not provide such information, according to that:
https://www.postgresql.org/message-id/flat/16334.1289972160%40sss.pgh.pa.us#ba50c00d4cc80f101dc2f4fbb4288b51

And by looking here https://wiki.postgresql.org/wiki/Todo#Wire_Protocol_Changes, it seems that is not ready to be included in version 12.

So we have to postpone this topic.

What do you think?

**Comment by tarekbadrshalaan** [comment]
ok thank you so much for your response
