### ISSUE TITLE
Random errors while running a load test

### ISSUE THREAD

**Issue by diegobernardes** [lib/pq#805]
Really don't know what is this error, but during load tests, I'm getting random errors. They're random, but, all the time they happen at the same line, when i try to create a transaction: 
```golang
postgres.Begin()
```

And this is the error:
```
&net.OpError{
      Op:     "read",
      Net:    "tcp",
      Source: &net.TCPAddr{
          IP:   {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1},
          Port: 55284,
          Zone: "",
      },
      Addr: &net.TCPAddr{
          IP:   {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1},
          Port: 5432,
          Zone: "",
      },
      Err: &os.SyscallError{
          Syscall: "read",
          Err:     syscall.Errno(0x36),
      },
}
```

I'm using `go version go1.11.1 darwin/amd64`, MacOS Mojave, `postgres:11` running inside a Docker container and tested with the latest version of pg and the stable release (1.0.0), on both situations, this error happens.

This is the driver config:
```golang
postgres.SetMaxOpenConns(200)
postgres.SetMaxIdleConns(200)
postgres.SetConnMaxLifetime(time.Second)
```

And I'm testing with `hey`:
```shell
hey -c 50 -z 100s http://localhost:3000
```

With very low concurrency, less then 30, I don't get the errors, then increasing, sometimes the error happens, sometimes don't.

Also the open file descriptors for the Go process is very low:
```
➜  ~ lsof -p 46937 | wc -l
9
```

**Comment by johto** [comment]
> Err: &os.SyscallError{
>     Syscall: "read",
>     Err:     syscall.Errno(0x36),
> },

I don't have a Mojave around, but at least on my OS X this is:

```C
#define	EINPROGRESS	36		/* Operation now in progress */
````

which would suggest that this is not our problem, but a problem in Go.  Can you check what the actual error message is when you print it?

**Comment by diegobernardes** [comment]
```
read tcp [::1]:52025->[::1]:5432: read: connection reset by peer
```

Maybe I hit some kernel limits on MacOS, don't know...

**Comment by diegobernardes** [comment]
Just changed from a Docker Postgres to one running at the system. It's way better, not getting this errors anymore. Maybe it's really some tuning that I'm missing.

The only error that still happens if the concurrency is too high is this:
```golang
&pq.Error{Severity:"FATAL", Code:"53300", Message:"sorry, too many clients already", Detail:"", Hint:"", Position:"", InternalPosition:"", InternalQuery:"", Where:"", Schema:"", Table:"", Column:"", DataTypeName:"", Constraint:"", File:"proc.c", Line:"338", Routine:"InitProcess"} pq: sorry, too many clients already
```

But this is expected, didn't changed the default `max_connections = 100` at the database.
