### ISSUE TITLE
Driver does not work with PostgreSQL 11.1

### ISSUE THREAD

**Issue by svett** [lib/pq#816]
I recently upgraded my PostgreSQL to version 11.1. 

The following error occurs when I try to connect to the database:

```
  <*pq.Error | 0xc000387200>: {
          Severity: "ERROR",
          Code: "XX000",
          Message: "could not load library \"/usr/local/lib/postgresql/plpgsql.so\": dlopen(/usr/local/lib/postgresql/plpgsql.so, 10): Symbol not found: _AllocSetContextCreateExtended\n  Referenced from: /usr
/local/lib/postgresql/plpgsql.so\n  Expected in: /usr/local/opt/postgresql/bin/postgres\n in /usr/local/lib/postgresql/plpgsql.so",
          Detail: "",
          Hint: "",
          Position: "",
          InternalPosition: "",
          InternalQuery: "",
          Where: "",
          Schema: "",
          Table: "",
          Column: "",
          DataTypeName: "",
          Constraint: "",
          File: "dfmgr.c",
          Line: "240",
          Routine: "internal_load_library",
      }
      pq: could not load library "/usr/local/lib/postgresql/plpgsql.so": dlopen(/usr/local/lib/postgresql/plpgsql.so, 10): Symbol not found: _AllocSetContextCreateExtended
        Referenced from: /usr/local/lib/postgresql/plpgsql.so
        Expected in: /usr/local/opt/postgresql/bin/
``

**Comment by cbandy** [comment]
@svett this error looks like it's from PostgreSQL server/backend. To verify, try your query with `psql`.

**Comment by svett** [comment]
It was a problem with my installation. I am closing the issue.

**Comment by dkobia** [comment]
I encountered this problem with postgresql installed via home brew - upgrading from 10.x to 11.x. Here's what I had to do:

* `brew uninstall postgresql`
* `rm -rf rm -rf /usr/local/var/postgres`
* Confirm that PostgreSQL is actually uninstalled - `brew list`
* `brew update`
* `brew install postgres`
* `brew services start postgresql` - if it hasn't already started automatically

**Comment by TAKeanice** [comment]
@dkobia removing the database does not solve the actual problem - creating a new database is always possible, migrating the old one is the actual challenge

**Comment by mytharcher** [comment]
@dkobia I have found a better way to fix it:

~~~shell
psql --version # 11.4 <--- psql cli version
psql -c 'select version();' postgres # 10.2 <--- db version in storage
brew info postgres # check pg info <--- found solution
brew postgresql-upgrade-database # upgrade db version in storage and fixed the issue
~~~

**Comment by chemparparokke** [comment]
@mytharcher thx, it helped!

**Comment by faisalrazap** [comment]
Before database upgrade, I had to remove `/usr/local/var/postgre.old` and stop postgres using `brew services stop postgresql`. Then running upgrade command worked for me:

```
brew postgresql-upgrade-database
brew services start postgresql
```

**Comment by bilal-khaan** [comment]
Before database upgrade, I had to remove old postgres folder using command`rm -R /usr/local/var/postgres.old` and stop postgres using `brew services stop postgresql`. Then running upgrade command worked for me:

```
brew postgresql-upgrade-database
brew services start postgresql
```
