### ISSUE TITLE
Problems with notifications. Listener works unexpected

### ISSUE THREAD

**Issue by rianby64** [lib/pq#823]
```plpgsql
DO
$$
BEGIN
  PERFORM pg_notify('mychannel', 'whatever 0"}');
  PERFORM pg_notify('mychannel', 'whatever 0"}');
  PERFORM pg_notify('mychannel', 'whatever 0"}');
  PERFORM pg_notify('mychannel', 'whatever 0"}');
END;
$$;
```

In this bunch of notifications only one is visible. The rest are invisible for the listener.
As clue, I've to mention that the following bunch of notifications

```plpgsql
DO
$$
BEGIN
  PERFORM pg_notify('mychannel', 'whatever 0"}');
  PERFORM pg_notify('mychannel', 'whatever 1"}');
  PERFORM pg_notify('mychannel', 'whatever 2"}');
  PERFORM pg_notify('mychannel', 'whatever 3"}');
END;
$$;
```

are visible for the listener. Why?

**Comment by johto** [comment]
https://www.postgresql.org/docs/current/sql-notify.html

> If the same channel name is signaled multiple times from the same transaction with identical payload strings, the database server can decide to deliver a single notification only.

**Comment by rianby64** [comment]
oh! nice! thanks a lot
