### ISSUE TITLE
QueryRow run-time panic

### ISSUE THREAD

**Issue by fellz** [lib/pq#826]
Hi, found strange error  when using QueryRow

Example function:

```
func GetUser( name string){
	var user *User
	row := db.QueryRow( `SELECT * FROM users WHERE name = $1`, name )
// Here we got an error
	err := row.Scan(&user.Id, &user.Name, &user.Password, &user.Email, &user.Created_on, &user.Uuid)
	if err != nil{
		log.Fatal("Db error", err)
	}
	fmt.Printf("Get user by name id: %d\n", user.Id)
}

GetUser("Dave")
```
db init 

```
package models
import (
	"database/sql"
	_ "github.com/lib/pq"
	"log"
)

var db *sql.DB

func InitDB(dataSourceName string) {
	var err error
	db, err = sql.Open("postgres", dataSourceName)
	if err != nil {
		log.Panic(err)
	}

	if err = db.Ping(); err != nil {
		log.Panic(err)
	}
}
```
and error is 

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x0 pc=0x656f8e]
> 
> goroutine 1 [running]:
> omlet/models.GetUser(0x6f2145, 0x4)
>         C:/Users/Dave/code/go/omlet/models/users.go:43 +0xce
> main.main()
>         C:/Users/Dave/code/go/omlet/main.go:13 +0x5a
> exit status 2

with `Query` i get no errors. My guess this error with `defer` since Scan in this case use `defer` and i see it in debug mode. Is this a bug ?
Go 1.11.4
Postgresql 11

**Comment by johto** [comment]
Your user variable is a pointer to nil.  Instead of `var user *User`, try e.g. `user := &User{}` or simply `var user User`.

**Comment by fellz** [comment]
thanks need to work on pointers )
