### ISSUE TITLE
ENCODING option for COPY

### ISSUE THREAD

**Issue by youngjoon-lee** [lib/pq#830]
The current `pg.CopyIn()` just returns a query string like `COPY ... FROM STDIN` without any options of the COPY query. 

However, my application parses CSV files with various encoding, and pass each fields to `Exec()`. 
So, I would like to specify `ENCODING` option like `COPY ... FROM STDIN ENCODING UTF-16`. 

In my application, I’m appending an option to the return value of `pq.CopyIn()`, but it’s not good way because I shouldn’t know how the query returned from `pq.CopyIn()` really looks like. 

```go
query := pq.CopyIn(“table”, “col0”, “col1”)
return fmt.Sprintf(“%s ENCODING %s”, query, encoding)
```

Of course, I can fully write a COPY query by myself without using `pq.CopyIn()`. 
But it’s also not good because I shouldn’t know how `Prepare()` recognizes COPY query. 

I would suggest additional parameter to `pq.CopyIn()` to pass an encoding option. 
I know there is a issue #213 about enhancing COPY functionality. I also hope I can use `io.Reader` for COPY and I can use `FORMAT CSV` option. 
But, I don’t know how that issue is going on. 

If it’s okay to add a `encoding` parameter to `pq.CopyIn()`, I can start to implement it. 
Please let me know your opinion. 

Thank you.

**Comment by yramanovich** [comment]
You can try to use https://github.com/jackc/pgx lib, which has 
`CopyFromReader(r io.Reader, sql string) error` 
Also pgx implementation hasn't RACE problems unlike tx.Prepare(pq.CopyIn(...)) has.
