### ISSUE TITLE
syntax error when use upsert

### ISSUE THREAD

**Issue by im-here** [lib/pq#858]
I have the following postgresql query which works fine in psql but fails in the pq driver.

``INSERT INTO rank VALUES(1,1,2) ON CONFLICT (uid) DO UPDATE SET total=100``

The corresponding golang code is:

``stmt, err := postgres.Prepare(`INSERT INTO rank VALUES(1,1,2) ON CONFLICT (uid) DO UPDATE SET total=100`)``

the error message is: ``pq: syntax error at or near "ON CONFLICT"``

**Comment by Doca** [comment]
@im-here did you make this working?
