### ISSUE TITLE
cockroachdb 19.1: unable to insert zero-length array

### ISSUE THREAD

**Issue by chappjc** [lib/pq#862]
With CockroachDB 2.1.6, lib/pq had no trouble inserting an empty array, e.g.:

```sql
INSERT INTO tablex (some_strings) VALUES ($1);
```

```go
stmt.QueryRow(pq.StringArray([]string{}))
```

But with CockroachDB 19.1, an error comes back from the crdb connection saying:

```
pq: error in argument for $1: only 1-dimension arrays supported
```

Tracing in the debugger indicates that `data` for the `driver.Value` is `"{}"`, as expected from `(StringArray).Value`.

Perhaps this is a bug or backward-incompatible change in CRDB 19.0, but I am able to do the following with `cockroach sql`:

```sql
> INSERT INTO tablex (some_strings) VALUES ('{}'::TEXT[]);
INSERT 1
```

It is notable that the explicit conversion is required in CRDB, although I believe this was the case with 2.1.6 already:

```sql
> INSERT INTO tablex (some_strings) VALUES ('{}');
pq: value type string doesn't match type STRING[] of column "some_strings"
```

**Comment by cbandy** [comment]
> ```
> pq: error in argument for $1: only 1-dimension arrays supported
> ```

This error is not generated `lib/pq`. You'll need to inquire at CockroachDB.

**Comment by chappjc** [comment]
Thanks.  I have reported the issue at https://github.com/cockroachdb/cockroach/issues/37365.  To understand why `cockroach sql` has no trouble, but this error comes back from cockroach when using `lib/pq`, I may try to compare the wire bytes sent to the server (`lib/pq.(*stmt).exec` vs. whatever `cockroach sql` sends).

**Comment by chappjc** [comment]
Was just fixed in https://github.com/cockroachdb/cockroach/pull/37376, and it's being backported to the 19.1 series: https://github.com/cockroachdb/cockroach/pull/37398
