### ISSUE TITLE
feature: inbuilt support for  for int32/float32/[]byte slices in pq.Array

### ISSUE THREAD

**Issue by Shivam010** [lib/pq#875]
For scanning `int32` or `float32` or `[]byte` slices, we have to wrap a custom scanner/valuer around them to be able to use `Scan/Value`.

pq.Array does not have support for slices of 32 bit-size data-types. 

The support should be added. I have a PR for it

**Comment by guenhter** [comment]
@Shivam010  I guess this can be closed, can't it?

**Comment by Shivam010** [comment]
Yes indeed. Thanks to you, now I can be back to lib/pq instead of my fork.
