### ISSUE TITLE
UUID Support?

### ISSUE THREAD

**Issue by blakesmith** [lib/pq#90]
Has anyone made an attempt at adding UUID type support? Is anyone else interested in support? It looks like pq recognizes the type in the wire protocol, but doesn't attempt to encode / decode.

I'm not sure what kind of type you'd serialize / deserialize into, especially since there are several UUID implementations. I thought about the idea of custom registered types, but that might be complicated.

Thoughts?

**Comment by lknite** [comment]
@the42 could you be more clear on what the solution was for you, as us new folks run into the same issue:
```
id, err := strconv.Atoi(values.Get("id"))
if err != nil {
    log.Println(err)
    w.WriteHeader(http.StatusNotFound)
    w.Write([]byte("error: converting id"))
    return
}
key, err := uuid.Parse(values.Get("key"))
if err != nil {
    log.Println(err)
    w.WriteHeader(http.StatusNotFound)
    w.Write([]byte("error: converting key"))
    return
}
err = db.QueryRowContext(ctx, `SELECT "bIndex" FROM block WHERE "id"=$1 AND "key"=$2`, id, key).Scan(&bigId)
```

pq: invalid input syntax for type integer: "12f6facd-0577-11ef-ba45-c6375db591df"
