### ISSUE TITLE
cant use copyin. sql: expected 0 arguments, got 13

### ISSUE THREAD

**Issue by k1ng440** [lib/pq#901]
here is a strip down code. 

```go
columns := []string{"time", "symbol", "opening_price", "highest_price", "lowest_price", "closing_price" ....}

fmt.Println(pq.CopyIn("tickers", columns...))
stmt, err := txn.Prepare(pq.CopyIn("tickers", columns...))
if err != nil {
	log.Fatal(err)
}

for {
	_, err = stmt.Exec(reqTime, ....)
	if err != nil {
		log.WithContext(ctx).Fatal(err)
	}
}

err = stmt.Close()
if err != nil {
	panic(err)
}

err = txn.Commit()
if err != nil {
	log.WithContext(ctx).Fatal(err)
}
```

**Comment by justclimber** [comment]
@k1ng440 how did you solve this issue? I have the same issue and can't find the solution )

**Comment by k1ng440** [comment]
It's been a couple of years. I have forgotten how I have solved it. Sorry

**Comment by wuhan005** [comment]
> @k1ng440 how did you solve this issue? I have the same issue and can't find the solution )

As https://github.com/jackc/pgx#choosing-between-the-pgx-and-databasesql-interfaces mentioned:
> Many PostgreSQL specific features such as LISTEN / NOTIFY and COPY are not available through the database/sql interface.

Maybe you used the `database/sql` interface which does not support `COPY IN` to connect the database by mistake. Try to use `github.com/jackc/pgx` instead.

FYI: https://pkg.go.dev/github.com/jackc/pgx/v5#hdr-Copy_Protocol

**Comment by darccio** [comment]
As it's possible to prepare and execute a `COPY` statement, and `lib/pq` supports it with a specific implementation, for anybody coming to this issue: this error may happen when your `COPY` statement contains anything that isn't `COPY` as the first characters of the query.

I opened a PR to fix that corner case, as it's not unusual, in #1198.
