### ISSUE TITLE
Latest commit causing issues building code

### ISSUE THREAD

**Issue by kjbass** [lib/pq#917]
```
# github.com/lib/pq
../../lib/pq/conn_go18.go:213:21: not enough arguments in call to st.cn.cancel
	have ()
	want (context.Context)
```
Above is error returned when executing a go get for this.  `go get github.com/lib/pq`

**Comment by masonkirchner** [comment]
Seeing the same issue

**Comment by arhelgens** [comment]
I am seeing the same issue with Docker

Building in the golang:1.12.7-alpine container

`FROM golang:1.12.7-alpine as build`
`RUN apk add --no-cache git && apk add --no-cache build-base && go get github.com/pkg/errors && go get github.com/gorilla/mux && go get github.com/lib/pq`

**Comment by muhlemmer** [comment]
https://github.com/lib/pq/blob/a2bfbdffa369322882bd4f55f284d10da8023b85/conn_go18.go#L213

It was introduced in today merge of #768

**Comment by muhlemmer** [comment]
Looks like its already reverted:  #918. My builds are working again :+1:

**Comment by kjbass** [comment]
Works for me also, I'll mark it as closed.
