### ISSUE TITLE
v1.3.0 - Misleading release description

### ISSUE THREAD

**Issue by burningalchemist** [lib/pq#933]
Hello @mjibson 

There seems to be a misleading description for v1.3.0 release:

```
* Add support for statement QueryContext and ExecContext. 
* Add support for connection PrepareContext. 
* Improved Ping support, now works correctly even during a failed transaction.
```

As far as I understand, first two things have been reverted.

Instead, #888 (Fix nil pointer dereference when calling RowsAffected on the result of a 0-item CopyIn) might be included in the changelog.

Cheers!

**Comment by mjibson** [comment]
Thanks. Fixed. Not sure how I missed those.
