### ISSUE TITLE
pq: syntax error at or near ","

### ISSUE THREAD

**Issue by Doca** [lib/pq#946]
Hello I'm struggeling with a very simple query. Maybe I didn't understand the concept or so but shouldnt this be possible with prepared statements?
I get the error 

> pq: syntax error at or near ","

```
txn, err := db.Begin()
stmt, err := db.Prepare(`INSERT INTO advertiser_per_day (id,advertiser_name,additional,customer_id,site_id,tracking,counter,day,month,year) VALUES (?,?,?,?,?,?,?,?,?,?)`)
```

Is there a way to solve this with prepared statements?

**Comment by johto** [comment]
> Is there a way to solve this with prepared statements?

Postgres doesn't use the inferior question mark syntax for parameters.  See [here](https://www.postgresql.org/docs/current/sql-prepare.html).

**Comment by Doca** [comment]
Thanks a lot this works!
