### ISSUE TITLE
Unable to list the tables

### ISSUE THREAD

**Issue by VineethReddy02** [lib/pq#958]
Usually in postgres. We use ```SHOW TABLES;``` to list the tables. Can I know how can I list using pq client?

`r, err := c.Session.Query(fmt.Sprintf( "SHOW TABLES;"))`

I see an error message saying:

**unrecognized configuration parameter "tables"**

**Comment by peterstace** [comment]
You could use the `information_schema.tables` table, which contains metadata about each table.

**Comment by VineethReddy02** [comment]
@peterstace Is there any way I can list all the tables. something like ```/dt``` & ```SHOW TABLES;```

**Comment by cbandy** [comment]
PostgreSQL doesn't have a `SHOW TABLES`: https://www.postgresql.org/docs/current/sql-commands.html

You can use the `ECHO_HIDDEN` variable in `psql` to show the queries that drive `\dt` and other commands: https://www.postgresql.org/docs/current/app-psql.html

```
psql> \set ECHO_HIDDEN on
psql> \dt
********* QUERY **********
SELECT n.nspname as "Schema",
…
```
